local green = "|cff66cc33"

Atlas_DropDownLayouts_Order = {
	[1] = ATLAS_DDL_CONTINENT,
	[2] = ATLAS_DDL_PARTYSIZE,
	[3] = ATLAS_DDL_LEVEL,
	[4] = ATLAS_DDL_TYPE,
	[5] = ATLAS_DDL_ALL,
	[ATLAS_DDL_CONTINENT] = {
		[1] = ATLAS_DDL_CONTINENT_EASTERN,
		[2] = ATLAS_DDL_CONTINENT_KALIMDOR, 
		[3] = ATLAS_DDL_WORLD,
		[4] = green..ATLAS_DDL_TYPE_ENTRANCE,
		[5] = green..ATLAS_DDL_BGS,
		[6] = green..ATLAS_DDL_DUNGEON_LOCATIONS,
		[7] = green..ATLAS_DDL_FLIGHT_PATHS,
		[8] = green..ATLAS_DDL_TRANSPORT_ROUTES,
	},
	[ATLAS_DDL_PARTYSIZE] = {
		[1] = ATLAS_DDL_PARTYSIZE_5,
		[2] = ATLAS_DDL_PARTYSIZE_10,
		[3] = ATLAS_DDL_PARTYSIZE_20,
		[4] = ATLAS_DDL_PARTYSIZE_40,
		[5] = ATLAS_DDL_WORLD,
		[6] = green..ATLAS_DDL_TYPE_ENTRANCE,
		[7] = green..ATLAS_DDL_BGS,
		[8] = green..ATLAS_DDL_DUNGEON_LOCATIONS,
		[9] = green..ATLAS_DDL_FLIGHT_PATHS,
		[10] = green..ATLAS_DDL_TRANSPORT_ROUTES,
	},
	[ATLAS_DDL_LEVEL] = {
		[1] = ATLAS_DDL_LEVEL_10TO20,
		[2] = ATLAS_DDL_LEVEL_20TO30,
		[3] = ATLAS_DDL_LEVEL_30TO40,
		[4] = ATLAS_DDL_LEVEL_40TO50,
		[5] = ATLAS_DDL_LEVEL_50TO60,
		[6] = ATLAS_DDL_LEVEL_60,
		[7] = ATLAS_DDL_WORLD,
		[8] = green..ATLAS_DDL_TYPE_ENTRANCE,
		[9] = green..ATLAS_DDL_BGS,
		[10] = green..ATLAS_DDL_DUNGEON_LOCATIONS,
		[11] = green..ATLAS_DDL_FLIGHT_PATHS,
		[12] = green..ATLAS_DDL_TRANSPORT_ROUTES,
	},
	[ATLAS_DDL_TYPE] = {
		[1] = ATLAS_DDL_TYPE_DUNGEONS,
		[2] = ATLAS_DDL_TYPE_RAIDS,
		[3] = ATLAS_DDL_WORLD,
		[4] = green..ATLAS_DDL_TYPE_ENTRANCE,
		[5] = green..ATLAS_DDL_BGS,
		[6] = green..ATLAS_DDL_DUNGEON_LOCATIONS,
		[7] = green..ATLAS_DDL_FLIGHT_PATHS,
		[8] = green..ATLAS_DDL_TRANSPORT_ROUTES,
	},
	[ATLAS_DDL_ALL] = {
		[1] = ATLAS_DDL_ALL_MENU1,
		[2] = ATLAS_DDL_ALL_MENU2,
		[3] = ATLAS_DDL_WORLD,
		[4] = green..ATLAS_DDL_TYPE_ENTRANCE,
		[5] = green..ATLAS_DDL_BGS,
		[6] = green..ATLAS_DDL_DUNGEON_LOCATIONS,
		[7] = green..ATLAS_DDL_FLIGHT_PATHS,
		[8] = green..ATLAS_DDL_TRANSPORT_ROUTES,
	}
}

Atlas_DropDownLayouts = {
	[ATLAS_DDL_CONTINENT] = {
		[ATLAS_DDL_CONTINENT_EASTERN] = {
			"BlackrockDepths",
			"BlackrockSpireLower",
			"BlackrockSpireUpper",
			"BlackwingLair",
			"GilneasCity",
			"Gnomeregan",
			"HateforgeQuarry",
			"KarazhanCrypt",
			"TowerofKarazhan",
			"LowerKarazhan",
			"MoltenCore",
			"Naxxramas",
			"Scholomance",
			"ShadowfangKeep",
			"SMArmory",
			"SMCathedral",
			"SMGraveyard",
			"SMLibrary",
			"StormwroughtRuins",
			"StormwindVault",
			"Stratholme",
			"TheDeadmines",
			"TheStockade",
			"TheSunkenTemple",
			"Uldaman",
			"ZulGurub"
		},
		[ATLAS_DDL_CONTINENT_KALIMDOR] = {
			"BlackfathomDeeps",
			"CavernsOfTimeBlackMorass",
			"DireMaulEast",
			"DireMaulNorth",
			"DireMaulWest",
			"EmeraldSanctum",
			"Maraudon",
			"OnyxiasLair",
			"RagefireChasm",
			"RazorfenDowns",
			"RazorfenKraul",
			"TheCrescentGrove",
			"TheRuinsofAhnQiraj",
			"TheTempleofAhnQiraj",
			"WailingCaverns",
			"ZulFarrak"
		},
		[ATLAS_DDL_WORLD] = {
			"Azuregos",
			"FourDragons",
			"LordKazzak",
			"Turtlhu",
			"Nerubian",
			"Reaver",
			"Ostarius",
			"Concavius",
			"CowKing",
			"Clackora",
			"RareMobs",
		},
		[green..ATLAS_DDL_TYPE_ENTRANCE] = {
			"BlackfathomDeepsEnt",
			"BlackrockMountainEnt",
			"DireMaulEnt",
			"GnomereganEnt",
			"MaraudonEnt",
			"SMEnt",
			"TheDeadminesEnt",
			"TheSunkenTempleEnt",
			"UldamanEnt",
			"WailingCavernsEnt",
		},
		[green..ATLAS_DDL_BGS] = {
			"AlteracValleyNorth",
			"AlteracValleySouth",
			"ArathiBasin",
			"WarsongGulch",
		},
		[green..ATLAS_DDL_DUNGEON_LOCATIONS] = {
			"DLEast",
			"DLWest",
		},
		[green..ATLAS_DDL_FLIGHT_PATHS] = {
			"FPAllianceEast",
			"FPAllianceWest",
			"FPHordeEast",
			"FPHordeWest",
		},
		[green..ATLAS_DDL_TRANSPORT_ROUTES] = {
			"TransportRoutes",
		},
	},
	[ATLAS_DDL_PARTYSIZE] = {
		[ATLAS_DDL_PARTYSIZE_5] = {
			"BlackrockDepths",
			"CavernsOfTimeBlackMorass",
			"DireMaulEast",
			"DireMaulNorth",
			"DireMaulWest",
			"GilneasCity",
			"Scholomance",
			"StormwindVault",
			"Stratholme",
			"KarazhanCrypt",
			"BlackrockSpireLower",
			"Gnomeregan",
			"HateforgeQuarry",
			"Maraudon",
			"TheDeadmines",
			"RagefireChasm",
			"RazorfenDowns",
			"RazorfenKraul",
			"ShadowfangKeep",
			"SMArmory",
			"SMCathedral",
			"SMGraveyard",
			"SMLibrary",
			"StormwroughtRuins",
			"TheCrescentGrove",
			"TheStockade",
			"TheSunkenTemple",
			"Uldaman",
			"WailingCaverns",
			"ZulFarrak",
		},
		[ATLAS_DDL_PARTYSIZE_10] = {
			"BlackrockSpireLower",
			"BlackrockSpireUpper",
			"LowerKarazhan",
			"Scholomance",
			"Stratholme",
		},
		[ATLAS_DDL_PARTYSIZE_20] = {
			"TheRuinsofAhnQiraj",
			"ZulGurub",
		},
		[ATLAS_DDL_PARTYSIZE_40] = {
			"MoltenCore",
			"OnyxiasLair",
			"EmeraldSanctum",
			"BlackwingLair",
			"TheTempleofAhnQiraj",
			"Naxxramas",
			"TowerofKarazhan",
		},
		[ATLAS_DDL_WORLD] = {
			"Azuregos",
			"FourDragons",
			"LordKazzak",
			"Turtlhu",
			"Nerubian",
			"Reaver",
			"Ostarius",
			"Concavius",
			"CowKing",
			"Clackora",
			"RareMobs",
		},
		[green..ATLAS_DDL_TYPE_ENTRANCE] = {
			"BlackfathomDeepsEnt",
			"BlackrockMountainEnt",
			"DireMaulEnt",
			"GnomereganEnt",
			"MaraudonEnt",
			"SMEnt",
			"TheDeadminesEnt",
			"TheSunkenTempleEnt",
			"UldamanEnt",
			"WailingCavernsEnt",
		},
		[green..ATLAS_DDL_BGS] = {
			"AlteracValleyNorth",
			"AlteracValleySouth",
			"ArathiBasin",
			"WarsongGulch",
		},
		[green..ATLAS_DDL_DUNGEON_LOCATIONS] = {
			"DLEast",
			"DLWest",
		},
		[green..ATLAS_DDL_FLIGHT_PATHS] = {
			"FPAllianceEast",
			"FPAllianceWest",
			"FPHordeEast",
			"FPHordeWest",
		},
		[green..ATLAS_DDL_TRANSPORT_ROUTES] = {
			"TransportRoutes"
		},
	},
	[ATLAS_DDL_LEVEL] = {
		[ATLAS_DDL_LEVEL_10TO20] = {
			"RagefireChasm",
			"TheDeadmines",
			"TheStockade",
			"WailingCaverns",
		},
		[ATLAS_DDL_LEVEL_20TO30] = {
			"BlackfathomDeeps",
			"Gnomeregan",
			"RazorfenKraul",
			"ShadowfangKeep",
		},
		[ATLAS_DDL_LEVEL_30TO40] = {
			"RazorfenDowns",
			"SMArmory",
			"SMCathedral",
			"SMGraveyard",
			"SMLibrary",
			"StormwroughtRuins",
			"TheCrescentGrove",
			"Uldaman",
		},
		[ATLAS_DDL_LEVEL_40TO50] = {
			"GilneasCity",
			"Maraudon",
			"TheSunkenTemple",
			"ZulFarrak",
		},
		[ATLAS_DDL_LEVEL_50TO60] = {
			"BlackrockDepths",
			"BlackrockSpireLower",
			"CavernsOfTimeBlackMorass",
			"DireMaulEast",
			"DireMaulNorth",
			"DireMaulWest",
			"HateforgeQuarry",
			"KarazhanCrypt",
			"Scholomance",
			"StormwindVault",
			"Stratholme",
		},
		[ATLAS_DDL_LEVEL_60] = {
			"BlackrockSpireUpper",
			"TheRuinsofAhnQiraj",
			"ZulGurub",
			"LowerKarazhan",
			"OnyxiasLair",
			"MoltenCore",
			"EmeraldSanctum",
			"BlackwingLair",
			"TheTempleofAhnQiraj",
			"Naxxramas",
			"TowerofKarazhan",
		},
		[ATLAS_DDL_WORLD] = {
			"Azuregos",
			"FourDragons",
			"LordKazzak",
			"Turtlhu",
			"Nerubian",
			"Reaver",
			"Ostarius",
			"Concavius",
			"CowKing",
			"Clackora",
			"RareMobs",
		},
		[green..ATLAS_DDL_TYPE_ENTRANCE] = {
			"BlackfathomDeepsEnt",
			"BlackrockMountainEnt",
			"DireMaulEnt",
			"GnomereganEnt",
			"MaraudonEnt",
			"SMEnt",
			"TheDeadminesEnt",
			"TheSunkenTempleEnt",
			"UldamanEnt",
			"WailingCavernsEnt",
		},
		[green..ATLAS_DDL_BGS] = {
			"AlteracValleyNorth",
			"AlteracValleySouth",
			"ArathiBasin",
			"WarsongGulch",
		},
		[green..ATLAS_DDL_DUNGEON_LOCATIONS] = {
			"DLEast",
			"DLWest",
		},
		[green..ATLAS_DDL_FLIGHT_PATHS] = {
			"FPAllianceEast",
			"FPAllianceWest",
			"FPHordeEast",
			"FPHordeWest",
		},
		[green..ATLAS_DDL_TRANSPORT_ROUTES] = {
			"TransportRoutes"
		},
	},	
	[ATLAS_DDL_TYPE] = {
		[ATLAS_DDL_TYPE_DUNGEONS] = {
			"BlackfathomDeeps",
			"BlackrockDepths",
			"BlackrockSpireLower",
			"CavernsOfTimeBlackMorass",
			"DireMaulEast",
			"DireMaulNorth",
			"DireMaulWest",
			"GilneasCity",
			"Gnomeregan",
			"HateforgeQuarry",
			"KarazhanCrypt",
			"Maraudon",
			"RagefireChasm",
			"RazorfenDowns",
			"RazorfenKraul",
			"Scholomance",
			"ShadowfangKeep",
			"SMArmory",
			"SMCathedral",
			"SMGraveyard",
			"SMLibrary",
			"StormwroughtRuins",
			"StormwindVault",
			"Stratholme",
			"TheDeadmines",
			"TheCrescentGrove",
			"TheStockade",
			"TheSunkenTemple",
			"Uldaman",
			"WailingCaverns",
			"ZulFarrak",
		},
		[ATLAS_DDL_TYPE_RAIDS] = {
			"BlackrockSpireUpper",
			"TheRuinsofAhnQiraj",
			"ZulGurub",
			"LowerKarazhan",
			"OnyxiasLair",
			"MoltenCore",
			"EmeraldSanctum",
			"BlackwingLair",
			"TheTempleofAhnQiraj",
			"Naxxramas",
			"TowerofKarazhan",
		},
		[ATLAS_DDL_WORLD] = {
			"Azuregos",
			"FourDragons",
			"LordKazzak",
			"Turtlhu",
			"Nerubian",
			"Reaver",
			"Ostarius",
			"Concavius",
			"CowKing",
			"Clackora",
			"RareMobs",
		},
		[green..ATLAS_DDL_TYPE_ENTRANCE] = {
			"BlackfathomDeepsEnt",
			"BlackrockMountainEnt",
			"DireMaulEnt",
			"GnomereganEnt",
			"MaraudonEnt",
			"SMEnt",
			"TheDeadminesEnt",
			"TheSunkenTempleEnt",
			"UldamanEnt",
			"WailingCavernsEnt",
		},
		[green..ATLAS_DDL_BGS] = {
			"AlteracValleyNorth",
			"AlteracValleySouth",
			"ArathiBasin",
			"WarsongGulch",
		},
		[green..ATLAS_DDL_DUNGEON_LOCATIONS] = {
			"DLEast",
			"DLWest",
		},
		[green..ATLAS_DDL_FLIGHT_PATHS] = {
			"FPAllianceEast",
			"FPAllianceWest",
			"FPHordeEast",
			"FPHordeWest"
		},
		[green..ATLAS_DDL_TRANSPORT_ROUTES] = {
			"TransportRoutes"
		},
	},
	[ATLAS_DDL_ALL] = {
		[ATLAS_DDL_ALL_MENU1] = {
			"RagefireChasm",
			"WailingCaverns",
			"TheDeadmines",
			"ShadowfangKeep",
			"BlackfathomDeeps",
			"TheStockade",
			"Gnomeregan",
			"RazorfenKraul",
			"TheCrescentGrove",
			"SMGraveyard",
			"SMLibrary",
			"SMArmory",
			"SMCathedral",
			"RazorfenDowns",
			"Uldaman",
			"GilneasCity",
			"ZulFarrak",
			"Maraudon",
			"HateforgeQuarry",
			"TheSunkenTemple",
			"BlackrockDepths",
			"DireMaulEast",
			"DireMaulWest",
			"DireMaulNorth",
			"CavernsOfTimeBlackMorass",
			"Scholomance",
			"StormwroughtRuins",
			"StormwindVault",
			"Stratholme",
		},
		[ATLAS_DDL_ALL_MENU2] = {
			"KarazhanCrypt",
			"LowerKarazhan",
			"BlackrockSpireLower",
			"BlackrockSpireUpper",
			"ZulGurub",
			"TheRuinsofAhnQiraj",
			"MoltenCore",
			"OnyxiasLair",
			"BlackwingLair",
			"TheTempleofAhnQiraj",
			"EmeraldSanctum",
			"Naxxramas",
			"TowerofKarazhan",
		},
		[ATLAS_DDL_WORLD] = {
			"Azuregos",
			"FourDragons",
			"LordKazzak",
			"Turtlhu",
			"Nerubian",
			"Reaver",
			"Ostarius",
			"Concavius",
			"CowKing",
			"Clackora",
			"RareMobs",
		},
		[green..ATLAS_DDL_TYPE_ENTRANCE] = {
			"BlackfathomDeepsEnt",
			"BlackrockMountainEnt",
			"DireMaulEnt",
			"GnomereganEnt",
			"MaraudonEnt",
			"SMEnt",
			"TheDeadminesEnt",
			"TheSunkenTempleEnt",
			"UldamanEnt",
			"WailingCavernsEnt"
		},
		[green..ATLAS_DDL_BGS] = {
			"AlteracValleyNorth",
			"AlteracValleySouth",
			"ArathiBasin",
			"WarsongGulch",
		},
		[green..ATLAS_DDL_DUNGEON_LOCATIONS] = {
			"DLEast",
			"DLWest"
		},
		[green..ATLAS_DDL_FLIGHT_PATHS] = {
			"FPAllianceEast",
			"FPAllianceWest",
			"FPHordeEast",
			"FPHordeWest"
		},
		[green..ATLAS_DDL_TRANSPORT_ROUTES] = {
			"TransportRoutes"
		},
	}
}