AtlasTW = {
    --constants
    --quest
    QMAXQUESTS = 23,
    QMAXINSTANCES = 98,
    QMAXQUESTITEMS = 6,
    --atlas
    NUM_LINES = 24,
    DEBUGMODE = false,
    MAPPATH = "Interface\\AddOns\\Atlas-TW\\Images\\Maps\\",
    --quest id for instance maps
    INSTANCEMAP = {
        -- Original Instances (1-32)
        ["TheDeadmines"] = 1,
        ["TheDeadminesEnt"] = 1,
        ["WailingCaverns"] = 2,
        ["WailingCavernsEnt"] = 2,
        ["RagefireChasm"] = 3,
        ["Uldaman"] = 4,
        ["UldamanEnt"] = 4,
        ["BlackrockDepths"] = 5,
        ["BlackrockMountainEnt"] = 5,
        ["BlackwingLair"] = 6,
        ["BlackfathomDeeps"] = 7,
        ["BlackfathomDeepsEnt"] = 7,
        ["BlackrockSpireLower"] = 8,
        ["BlackrockSpireUpper"] = 9,
        ["DireMaulEast"] = 10,
        ["DireMaulEnt"] = 10,
        ["DireMaulNorth"] = 11,
        ["DireMaulWest"] = 12,
        ["Maraudon"] = 13,
        ["MaraudonEnt"] = 13,
        ["MoltenCore"] = 14,
        ["Naxxramas"] = 15,
        ["OnyxiasLair"] = 16,
        ["RazorfenDowns"] = 17,
        ["RazorfenKraul"] = 18,
        ["SMLibrary"] = 19,
        ["SMArmory"] = 20,
        ["SMCathedral"] = 21,
        ["SMGraveyard"] = 22,
        ["SMEnt"] = 22,
        ["Scholomance"] = 23,
        ["ShadowfangKeep"] = 24,
        ["Stratholme"] = 25,
        ["TheRuinsofAhnQiraj"] = 26,
        ["TheStockade"] = 27,
        ["TheSunkenTemple"] = 28,
        ["TheSunkenTempleEnt"] = 28,
        ["TheTempleofAhnQiraj"] = 29,
        ["ZulFarrak"] = 30,
        ["ZulGurub"] = 31,
        ["Gnomeregan"] = 32,
        ["GnomereganEnt"] = 32,
        -- Outdoor Raids (33-35)
        ["FourDragons"] = 33,
        ["Azuregos"] = 34,
        ["LordKazzak"] = 35,
        -- Battlegrounds (36-38)
        ["AlteracValleyNorth"] = 36,
        ["AlteracValleySouth"] = 36,
        ["ArathiBasin"] = 37,
        ["WarsongGulch"] = 38,
        -- Turtle-WOW Instances (39-65)
        ["TheCrescentGrove"] = 39,
        ["Concavius"] = 40,
        ["KarazhanCrypt"] = 41,
        ["Nerubian"] = 42,
        ["Reaver"] = 43,
        ["Turtlhu"] = 44,
        ["CavernsOfTimeBlackMorass"] = 45,
        ["HateforgeQuarry"] = 46,
        ["StormwindVault"] = 57,
        ["Ostarius"] = 58,
        ["CowKing"] = 59,
        ["GilneasCity"] = 61,
        ["LowerKarazhan"] = 62,
        ["EmeraldSanctum"] = 63,
        ["TowerofKarazhan"] = 64,
        ["Clackora"] = 65,
        -- Maps and Routes (98)
        ["TransportRoutes"] = 98,
        ["DLEast"] = 98,
        ["DLWest"] = 98,
        ["FPAllianceEast"] = 98,
        ["FPAllianceWest"] = 98,
        ["FPHordeEast"] = 98,
        ["FPHordeWest"] = 98,
        ["RareMobs"] = 98,
    },


    --entrance maps to instance maps
    EntToInstMatches = {
        ["BlackfathomDeepsEnt"] =		{"BlackfathomDeeps"},
        ["BlackrockMountainEnt"] =		{"BlackrockSpireLower","BlackrockSpireUpper","BlackwingLair","BlackrockDepths","MoltenCore"},
        ["GnomereganEnt"] =				{"Gnomeregan"},
        ["MaraudonEnt"] =				{"Maraudon"},
        ["TheDeadminesEnt"] =			{"TheDeadmines"},
        ["TheSunkenTempleEnt"] =		{"TheSunkenTemple"},
        ["UldamanEnt"] =				{"Uldaman"},
        ["WailingCavernsEnt"] =			{"WailingCaverns"},
        ["DireMaulEnt"] =				{"DireMaulEast","DireMaulNorth","DireMaulWest"},
        ["SMEnt"] =						{"SMArmory","SMLibrary","SMCathedral","SMGraveyard"}
    },
    --instance maps to entrance maps
    InstToEntMatches = {
        ["BlackfathomDeeps"] =			{"BlackfathomDeepsEnt"},
        ["BlackrockSpireLower"] =		{"BlackrockMountainEnt"},
        ["BlackrockSpireUpper"] =		{"BlackrockMountainEnt"},
        ["BlackwingLair"] =				{"BlackrockMountainEnt"},
        ["BlackrockDepths"] =			{"BlackrockMountainEnt"},
        ["MoltenCore"] =				{"BlackrockMountainEnt"},
        ["Gnomeregan"] =				{"GnomereganEnt"},
        ["Maraudon"] =					{"MaraudonEnt"},
        ["TheDeadmines"] =				{"TheDeadminesEnt"},
        ["TheSunkenTemple"] =			{"TheSunkenTempleEnt"},
        ["Uldaman"] =					{"UldamanEnt"},
        ["WailingCaverns"] =			{"WailingCavernsEnt"},
        ["DireMaulEast"] =				{"DireMaulEnt"},
        ["DireMaulNorth"] =				{"DireMaulEnt"},
        ["DireMaulWest"] =				{"DireMaulEnt"},
        ["SMArmory"] =					{"SMEnt"},
        ["SMLibrary"] =					{"SMEnt"},
        ["SMCathedral"] =				{"SMEnt"},
        ["SMGraveyard"] =				{"SMEnt"}
    },
    --Default map to auto-select to when no SubZone data is available
    AssocDefaults = {
        ["Dire Maul"] =					"DireMaulNorth",
        ["Blackrock Spire"] =			"BlackrockSpireLower",
        ["Scarlet Monastery"] =			"SMEnt"
    },
    --Links maps together that are part of the same instance
    SubZoneAssoc = {
        ["DireMaulNorth"] =				"Dire Maul",
        ["DireMaulEast"] =				"Dire Maul",
        ["DireMaulWest"] =				"Dire Maul",
        ["DireMaulEnt"] =				"Dire Maul",
        ["BlackrockSpireLower"] =		"Blackrock Spire",
        ["BlackrockSpireUpper"] =		"Blackrock Spire",
        ["BlackrockMountainEnt"] =		"Blackrock Spire",
        ["SMGraveyard"] =				"Scarlet Monastery",
        ["SMLibrary"] =					"Scarlet Monastery",
        ["SMArmory"] =					"Scarlet Monastery",
        ["SMCathedral"] =				"Scarlet Monastery",
        ["SMEnt"] =						"Scarlet Monastery"
    },
    --Links SubZone values with specific instance maps
    SubZoneData = {
        ["Halls of Destruction"] =		"DireMaulNorth",
        ["Gordok's Seat"] =				"DireMaulNorth",
        ["Warpwood Quarter"] =			"DireMaulEast",
        ["The Hidden Reach"] =			"DireMaulEast",
        ["The Conservatory"] =			"DireMaulEast",
        ["The Shrine of Eldretharr"] =	"DireMaulEast",
        ["Capital Gardens"] =			"DireMaulWest",
        ["Court of the Highborne"] =	"DireMaulWest",
        ["Prison of Immol'thar"] =		"DireMaulWest",
        ["The Athenaeum"] =				"DireMaulWest",
        ["Mok'Doom"] =					"BlackrockSpireLower",
        ["Tazz'Alaor"] =				"BlackrockSpireLower",
        ["Skitterweb Tunnels"] =		"BlackrockSpireLower",
        ["The Storehouse"] =			"BlackrockSpireLower",
        ["Chamber of Battle"] =			"BlackrockSpireLower",
        ["Dragonspire Hall"] =			"BlackrockSpireUpper",
        ["Hall of Binding"] =			"BlackrockSpireUpper",
        ["The Rookery"] =				"BlackrockSpireUpper",
        ["Hall of Blackhand"] =			"BlackrockSpireUpper",
        ["Blackrock Stadium"] =			"BlackrockSpireUpper",
        ["The Furnace"] =				"BlackrockSpireUpper",
        ["Hordemar City"] =				"BlackrockSpireUpper",
        ["Spire Throne"] =				"BlackrockSpireUpper",
        ["Chamber of Atonement"] =		"SMGraveyard",
        ["Forlorn Cloister"] =			"SMGraveyard",
        ["Honor's Tomb"] =				"SMGraveyard",
        ["Huntsman's Cloister"] =		"SMLibrary",
        ["Gallery of Treasures"] =		"SMLibrary",
        ["Athenaeum"] =					"SMLibrary",
        ["Training Grounds"] =			"SMArmory",
        ["Footman's Armory"] =			"SMArmory",
        ["Crusader's Armory"] =			"SMArmory",
        ["Hall of Champions"] =			"SMArmory",
        ["Chapel Gardens"] =			"SMCathedral",
        ["Crusader's Chapel"] =			"SMCathedral",
        ["The Grand Vestibule"] =		"SMEnt"
    },
    --Maps to auto-select to from outdoor zones.
    OutdoorZoneToAtlas = {
        ["Ashenvale"] =					"BlackfathomDeepsEnt",
        ["Badlands"] =					"UldamanEnt",
        ["Blackrock Mountain"] =		"BlackrockMountainEnt",
        ["Burning Steppes"] = 			"HateforgeQuarry", -- TurtleWOW
        ["Deadwind Pass"] = 			"KarazhanCrypt",    -- TurtleWOW
        ["Desolace"] =					"MaraudonEnt",
        ["Dun Morogh"] =				"GnomereganEnt",
        ["Feralas"] =					"DireMaulEnt",
        ["Searing Gorge"] =				"BlackrockMountainEnt",
        ["Swamp of Sorrows"] =			"TheSunkenTempleEnt",
        ["Tanaris"] =					"ZulFarrak",
        ["The Barrens"] =				"WailingCavernsEnt",
        ["Gilneas"] =					"GilneasCity", -- TurtleWOW
        ["Tirisfal Glades"]	=			"SMEnt",
        ["Westfall"] =					"TheDeadminesEnt",
        ["Orgrimmar"] =					"RagefireChasm",
        ["Dustwallow Marsh"] =			"OnyxiasLair",
        ["Silithus"] =					"TheTempleofAhnQiraj",
        ["Western Plaguelands"] =		"Scholomance",
        ["Silverpine Forest"] =			"ShadowfangKeep",
        ["Eastern Plaguelands"] =		"Stratholme",
        ["Stormwind City"] =			"TheStockade",
        ["Stranglethorn Vale"] =		"ZulGurub"
    },


    --variables
    --atlas
    Name = "Atlas-TW",
    Version = nil,
    DropDowns = {},
    CurrentLine = 0,
    ScrollList = {},
    --quest
    Q = {},
    isHorde = UnitFactionGroup("player") == "Horde" or false,
    CurrentMap = nil,
    QCurrentPage = 0,
    QCurrentQuest = 0,
    QCurrentButton = 0,
    QCurrentInstance = 0,
}

AtlasTWCharDB = AtlasTWCharDB or { FirstTime = true }