--************************************************
-- Localized Strings
--************************************************
local L = AceLibrary("AceLocale-2.2"):new("Atlas")

AtlasSortIgnore = {"the (.+)"}

BINDING_HEADER_ATLASTW_TITLE = "Atlas-TW Bindings"
BINDING_NAME_ATLASTW_TOGGLE = "Toggle Atlas-TW"
BINDING_NAME_ATLASTW_OPTIONS = "Toggle Options"

ATLAS_STRING_LOCATION = "Location"
ATLAS_STRING_LEVELRANGE = "Level Range"
ATLAS_STRING_PLAYERLIMIT = "Player Limit"
ATLAS_STRING_SELECT_CAT = "Select Category"
ATLAS_STRING_SELECT_MAP = "Select Map"
ATLAS_STRING_SEARCH = "Search"
ATLAS_STRING_CLEAR = "Clear"
ATLAS_STRING_MINLEVEL = "Minimum Level"

ATLAS_OPTIONS_BUTTON = "Options"
ATLAS_OPTIONS_SHOWBUT = "Show Button on Minimap"
ATLAS_OPTIONS_AUTOSEL = "Auto-Select Instance Map"
ATLAS_OPTIONS_BUTPOS = "Button Position"
ATLAS_OPTIONS_TRANS = "Transparency"
ATLAS_OPTIONS_DONE = "Done"
ATLAS_OPTIONS_RCLICK = "Right-Click for World Map"
ATLAS_OPTIONS_SHOWMAPNAME = "Show map name"
ATLAS_OPTIONS_RESETPOS = "Reset Position"
ATLAS_OPTIONS_ACRONYMS = "Display Acronyms"
ATLAS_OPTIONS_SCALE = "Scale"
ATLAS_OPTIONS_BUTRAD = "Button Radius"
ATLAS_OPTIONS_CLAMPED = "Clamp window to screen"
ATLAS_OPTIONS_HELP = "Left-click and drag to move this window."

ATLAS_BUTTON_TOOLTIP_HINT = "Left-click to open Atlas-TW.\nMiddle-click for Atlas-TW options.\nRight-click and drag to move this button."

ATLAS_OPTIONS_CATDD = "Sort Instance Maps by:"
ATLAS_DDL_CONTINENT = "Continent"
ATLAS_DDL_CONTINENT_EASTERN = "Eastern Kingdoms Instances"
ATLAS_DDL_CONTINENT_KALIMDOR = "Kalimdor Instances"
ATLAS_DDL_LEVEL = "Level"
ATLAS_DDL_LEVEL_10TO20 = "Instances level 10-20"
ATLAS_DDL_LEVEL_20TO30 = "Instances level 20-30"
ATLAS_DDL_LEVEL_30TO40 = "Instances level 30-40"
ATLAS_DDL_LEVEL_40TO50 = "Instances level 40-50"
ATLAS_DDL_LEVEL_50TO60 = "Instances level 50-60"
ATLAS_DDL_LEVEL_60 = "Instances 60 level"
ATLAS_DDL_PARTYSIZE = "Party Size"
ATLAS_DDL_PARTYSIZE_5 = "Instances for 5 Players"
ATLAS_DDL_PARTYSIZE_10 = "Instances for 10 Players"
ATLAS_DDL_PARTYSIZE_20 = "Instances for 20 Players"
ATLAS_DDL_PARTYSIZE_40 = "Instances for 40 Players"
ATLAS_DDL_ALL = "All"
ATLAS_DDL_ALL_MENU1 = "Showing all instances_1"
ATLAS_DDL_ALL_MENU2 = "Showing all instances_2"
ATLAS_DDL_TYPE = "Type"
ATLAS_DDL_TYPE_DUNGEONS = "Dungeons"
ATLAS_DDL_TYPE_RAIDS = "Raids"
ATLAS_DDL_WORLD = "World"
ATLAS_DDL_TYPE_ENTRANCE = "Entrances"
ATLAS_DDL_BGS = "Battlegrounds"
ATLAS_DDL_DUNGEON_LOCATIONS = "Dungeon Locations"
ATLAS_DDL_FLIGHT_PATHS = "Flight Path Maps"
ATLAS_DDL_TRANSPORT_ROUTES = "Transport Routes"

ATLAS_INSTANCE_BUTTON = "Instance"
ATLAS_ENTRANCE_BUTTON = "Entrance"
ATLAS_SEARCH_UNAVAIL = "Search Unavailable"

AtlasZoneSubstitutions = {
	["The Temple of Atal'Hakkar"] = "Sunken Temple"
}

L:RegisterTranslations("enUS", function() return {

	--************************************************
	-- Zone Names, Acronyms, and Common Strings
	--************************************************

	--Common strings
	["Atlas Options"] = true,
	--Colors
	["Blue"] = true,
	["Purple"] = true,
	["Red"] = true,
	["Orange"] = true,
	["White"] = true,
	--Mobs types
	["Boss"] = true,
	["Rare"] = true,
	["Bat"] = true,
	["Snake"] = true,
	["Raptor"] = true,
	["Spider"] = true,
	["Tiger"] = true,
	["Panther"] = true,
	["Pet"] = true,
	["Engineer"] = true,
	--Magic types
	["Fire"] = true,
	["Nature"] = true,
	["Frost"] = true,
	["Shadow"] = true,
	["Arcane"] = true,
	--Events
	["Hallow's End"] = true,
	["Scourge Invasion"] = true,
	["Lunar Festival"] = true,
	--Other
	["East"] = true,
	["North"] = true,
	["South"] = true,
	["West"] = true,
	["Battlegrounds"] = true,
	["Lower"] = true,
	["Upper"] = true,
	["Entrance"] = true,
	["Exit"] = true,
	["Chase Begins"] = true,
	["Chase Ends"] = true,
	["AKA"] = true,
	["Attunement Required"] = true,
	["Back"] = true,
	["Blacksmithing Plans"] = true,
	["Brazier of Invocation"] = true,
	["Connection"] = true,
	["Connections"] = true,
	["Damage: "] = true,
	["Tier 0.5 Summon"] = true,
	["Dungeon Locations"] = true,
	["Elevator"] = true,
	["Front"] = true,
	["Front1"] = true,
	["Ghost"] = true,
	["Heroic"] = true,
	["Instances"] = true,
	["Key"] = true,
	["Meeting Stone"] = true,
	["Moonwell"] = true,
	["Neutral"] = true,
	["Optional"] = true,
	["Outside"] = true,
	["Portal"] = true,
	["Random"] = true,
	["Reputation"] = true,
	["Rescued"] = true,
	["Side"] = true,
	["Summon"] = true,
	["Teleport"] = true,
	["through "] = true,
	["Trash Mobs"] = true,
	["Unknown"] = true,
	["Varies"] = true,
	["Various"] = true,
	["Wanders"] = true,

	--Instance names and acronyms
	["Armory"] = true,
	["Cathedral"] = true,
	["Graveyard"] = true,
	["Library"] = true,
	["Sunken Temple"] = true,

	--Set names
	["Set: "] = true,
	["Tier 0/0.5 Sets"] = true,
	["Zul'Gurub Sets"] = true,
	["Zul'Gurub Ring Sets"] = true,
	["Ruins of Ahn'Qiraj Sets"] = true,
	["Temple of Ahn'Qiraj Sets"] = true,
	["Tier 1 Sets"] = true,
	["Tier 2 Sets"] = true,
	["Tier 3 Sets"] = true,

	--************************************************
	-- Kalimdor Instance Data
	--************************************************

	--Ragefire Chasm
	["Maur Grimtotem"] = true,
	["Oggleflint"] = true,

	--Wailing Caverns
	["Mysterious Wailing Caverns Chest"] = true,

	--Blackfathom Deeps
	["Lorgalis Manuscript"] = true,
	["Argent Guard Thaelrid"] = true,
	["Shrine of Gelihast"] = true,
	["Fathom Stone"] = true,
	["Morridune"] = true,
	["Altar of the Deeps"] = true,

	--Razorfen Kraul
	["Razorfen Spearhide"] = true,
	["Willix the Importer"] = true,
	["Heralath Fallowbrook"] = true,

	--Razorfen Downs
	["Henry Stern"] = true,
	["Belnistrasz"] = true,
	["Sah'rhee"] = true,

	--Zul'Farrak
	["Mallet of Zul'Farrak"] = true,
	["Theka the Martyr"] = true,
	["Zul'Farrak Dead Hero"] = true,
	["Nekrum Gutchewer"] = true,
	["Dustwraith"] = true,
	["Sergeant Bly"] = true,
	["Weegli Blastfuse"] = true,
	["Murta Grimgut"] = true,
	["Raven"] = true,
	["Oro Eyegouge"] = true,
	["Sandfury Executioner"] = true,
	["Hydromancer Velratha"] = true,
	["Elder Wildmane"] = true,
	["Zerillis"] = true,
	["Sandarr Dunereaver"] = true,

	--Maraudon	
	["Scepter of Celebras"] = true,
	["Veng"] = true,
	["Maraudos"] = true,
	["Elder Splitrock"] = true,

	--Dire Maul (East)
	["Old Ironbark"] = true,
	["A Dusty Tome"] = true,
	["Felvine Shard"] = true,
	["Dire Maul Books"] = true,

	--Dire Maul (North)
	["Crescent Key"] = true,
	["Gordok Courtyard Key"] = true,
	["Gordok Inner Door Key"] = true,
	--"Library" omitted from here and DM West because of SM: "Library" duplicate
	["Stomper Kreeg"] = true,
	["Knot Thimblejack"] = true,
	["Tribute Run"] = true,

	--Dire Maul (West)
	["J'eevee's Jar"] = true,
	["Pylons"] = true,
	["Shen'dralar Ancient"] = true,
	["Ancient Equine Spirit"] = true,
	["Ferra"] = true,
	["Falrin Treeshaper"] = true,
	["Lorekeeper Lydros"] = true,
	["Lorekeeper Javon"] = true,
	["Lorekeeper Kildrath"] = true,
	["Lorekeeper Mykos"] = true,
	["Shen'dralar Provisioner"] = true,
	["Skeletal Remains of Kariel Winthalus"] = true,
	["The Prince's Chest"] = true,

	--Onyxia's Lair
	["Drakefire Amulet"] = true,
	["Onyxian Warders"] = true,
	["Whelp Eggs"] = true,

	--Temple of Ahn'Qiraj
	["Bug Trio"] = true,
	["Andorgos"] = true,
	["Vethsera"] = true,
	["Kandrostrasz"] = true,
	["Arygos"] = true,
	["Caelestrasz"] = true,
	["Merithra of the Dream"] = true,
	["AQ Enchants"] = true,
	["AQ Opening Quest Chain"] = true,

	--Ruins of Ahn'Qiraj
	["Four Kaldorei Elites"] = true,
	["Captain Qeez"] = true,
	["Captain Tuubid"] = true,
	["Captain Drenn"] = true,
	["Captain Xurrem"] = true,
	["Major Yeggeth"] = true,
	["Major Pakkon"] = true,
	["Colonel Zerran"] = true,
	["Safe Room"] = true,
	["Class Books"] = true,

	--****************************
	-- Eastern Kingdoms Instances
	--****************************

	--Blackrock Depths
	["Shadowforge Key"] = true,
	["Prison Cell Key"] = true,
	["Jail Break!"] = true,
	["Banner of Provocation"] = true,
	["Kharan Mighthammer"] = true,
	["Commander Gor'shak"] = true,
	["Marshal Windsor"] = true,
	["Ring of Law"] = true,
	["Theldren"] = true,
	["Lefty"] = true,
	["Malgen Longspear"] = true,
	["Gnashjaw"] = true,
	["Korv"] = true,
	["Rezznik"] = true,
	["Rotfang"] = true,
	["Snokh Blackspine"] = true,
	["Va'jashni"] = true,
	["Volida"] = true,
	["Elder Morndeep"] = true,
	["High Justice Grimstone"] = true,
	["Monument of Franclorn Forgewright"] = true,
	["The Vault"] = true,
	["The Black Anvil"] = true,
	["Shadowforge Lock"] = true,
	["Field Repair Bot 74A"] = true,
	["The Grim Guzzler"] = true,
	["Lokhtos Darkbargainer"] = true,
	["Mistress Nagmara"] = true,
	["Plugger Spazzring"] = true,
	["Private Rocknot"] = true,
	["Summoner's Tomb"] = true,
	["Chest of The Seven"] = true,
	["The Lyceum"] = true,
	["High Priestess of Thaurissan"] = true,
	["The Black Forge"] = true,
	["Core Fragment"] = true,

	--Blackrock Spire (Lower)
	["Vaelan"] = true,
	["Warosh"] = true,
	["Elder Stonefort"] = true,
	["Roughshod Pike"] = true,
	["Spirestone Butcher"] = true,
	["Spirestone Battle Lord"] = true,
	["Spirestone Lord Magus"] = true,
	["Fifth Mosh'aru Tablet"] = true,
	["Bijou"] = true,
	["Sixth Mosh'aru Tablet"] = true,
	["Bijou's Belongings"] = true,
	["Human Remains"] = true,
	["Unfired Plate Gauntlets"] = true,
	["Urok's Tribute Pile"] = true,
	["Burning Felguard"] = true,

	--Blackrock Spire (Upper)
	["Seal of Ascension"] = true,
	["Father Flame"] = true,
	["Darkstone Tablet"] = true,
	["Doomrigger's Coffer"] = true,
	["Awbee"] = true,
	["Finkle Einhorn"] = true,
	["Drakkisath's Brand"] = true,

	--Blackwing Lair
	["Draconic for Dummies"] = true,
	["Master Elemental Shaper Krixix"] = true,
	["Alchemy Lab"] = true,

	--Gnomeregan
	["Workshop Key"] = true,
	["Blastmaster Emi Shortfuse"] = true,
	["Clean Room"] = true,
	["Tink Sprocketwhistle"] = true,
	["The Sparklematic 5200"] = true,
	["Mail Box"] = true,
	["Kernobee"] = true,
	["Alarm-a-bomb 2600"] = true,
	["Matrix Punchograph 3005-B"] = true,
	["Matrix Punchograph 3005-C"] = true,
	["Matrix Punchograph 3005-D"] = true,

	--Molten Core
	["Aqual Quintessence"] = true,
	["Eternal Quintessence"] = true,
	["Random Boss Loot"] = true,

	--Naxxramas
	["Archmage Tarsis Kir-Moldir"] = true,
	["Mr. Bigglesworth"] = true,
	["Abomination Wing"] = true,
	["Spider Wing"] = true,
	["Deathknight Wing"] = true,
	["Four Horsemen Chest"] = true,
	["Plague Wing"] = true,
	["Frostwyrm Lair"] = true,
	["Icebellow Anvil"] = true,

	--SM: Library
	["Doan's Strongbox"] = true,

	--SM: Armory
	["The Scarlet Key"] = true,--omitted from SM: Cathedral

	--SM: Graveyard
	["Vorrel Sengutz"] = true,

	--Scholomance
	["Skeleton Key"] = true,
	["Viewing Room Key"] = true,
	["Viewing Room"] = true,
	["Blood of Innocents"] = true,
	["Divination Scryer"] = true,
	["Blood Steward of Kirtonos"] = true,
	["The Deed to Southshore"] = true,
	["Journal of Jandice Barov"] = true,
	["The Deed to Tarren Mill"] = true,
	["The Deed to Brill"] = true,
	["The Deed to Caer Darrow"] = true,
	["Torch Lever"] = true,
	["Old Treasure Chest"] = true,

	--Shadowfang Keep
	["Sorcerer Ashcrombe"] = true,
	["Deathstalker Adamant"] = true,
	["Landen Stilwell"] = true,
	["Deathstalker Vincent"] = true,
	["Fel Steed"] = true,
	["Jordan's Hammer"] = true,
	["Crate of Ingots"] = true,
	["Arugal's Voidwalker"] = true,
	["The Book of Ur"] = true,

	--Stratholme
	["Key to the City"] = true,
	["Various Postbox Keys"] = true,
	["Living Side"] = true,
	["Undead Side"] = true,
	["Stratholme Courier"] = true,
	["Fras Siabi"] = true,
	["Atiesh"] = true,
	["Elder Farwhisper"] = true,
	["Malor's Strongbox"] = true,
	["Crimson Hammersmith"] = true,
	["Grand Crusader Dathrohan"] = true,
	["Aurius"] = true,
	["Black Guard Swordsmith"] = true,
	["Ysida Harmon"] = true,
	["Crusaders' Square Postbox"] = true,
	["Market Row Postbox"] = true,
	["Festival Lane Postbox"] = true,
	["Elders' Square Postbox"] = true,
	["King's Square Postbox"] = true,
	["Fras Siabi's Postbox"] = true,
	["Third Postbox Opened"] = true,

	--The Deadmines
	["Sneed's Shredder"] = true,
	["Defias Gunpowder"] = true,

	--The Sunken Temple
	["Yeh'kinya's Scroll"] = true,
	["Balcony Minibosses"] = true,
	["Altar of Hakkar"] = true,
	["Essence Font"] = true,
	["Spawn of Hakkar"] = true,
	["Elder Starsong"] = true,
	["Statue Activation Order"] = true,
	["Malfurion Stormrage"] = true,

	--Uldaman
	["Staff of Prehistoria"] = true,
	["Baelog's Chest"] = true,
	["Conspicuous Urn"] = true,
	["Remains of a Paladin"] = true,
	["Annora"] = true,
	["Tablet of Will"] = true,
	["Shadowforge Cache"] = true,
	["The Discs of Norgannon"] = true,
	["Ancient Treasure"] = true,

	--Zul'Gurub
	["Mudskunk Lure"] = true,
	["Gurubashi Mojo Madness"] = true,
	["Zanza the Restless"] = true,
	["Ohgan"] = true,
	["Edge of Madness"] = true,
	["Zealot Zath"] = true,
	["Zealot Lor'Khan"] = true,
	["Muddy Churning Waters"] = true,
	["Jinxed Hoodoo Pile"] = true,
	["ZG Enchants"] = true,

	--************************************************
	-- Instance Entrance Maps
	--************************************************

	--Blackrock Mountain (Entrance)
	["Bodley"] = true,
	["Orb of Command"] = true,

	--Gnomeregan (Entrance)
	["Transpolyporter"] = true,
	["Matrix Punchograph 3005-A"] = true,

	--Maraudon (Entrance)
	["The Nameless Prophet"] = true,

	--The Deadmines (Entrance)

	--Sunken Temple (Entrance)
	["Jade"] = true,

	--Uldaman (Entrance)
	["Tablet of Ryun'Eh"] = true,
	["Krom Stoutarm's Chest"] = true,
	["Garrett Family Chest"] = true,
	["Digmaster Shovelphlange"] = true,

	--Wailing Caverns (Entrance)
	["Above the Entrance:"] = true,
	["Nalpak"] = true,
	["Kalldan Felmoon"] = true,
	["Waldor"] = true,

	--Dire Maul (Entrance)
	["Dire Pool"] = true,
	["Dire Maul Arena"] = true,
	["Mushgog"] = true,
	["Skarr the Unbreakable"] = true,
	["The Razza"] = true,
	["Elder Mistwalker"] = true,
	["Griniblix the Spectator"] = true,

	--World
	["Emerald Dragons"] = true,
	["Spirit of Azuregos"] = true,
	["Emerald Dragons Trash"] = true,
	["Nethergarde Keep"] = true,

	--Battlegrounds

	--Places
	["Friendly Reputation Rewards"] = true,
	["Honored Reputation Rewards"] = true,
	["Revered Reputation Rewards"] = true,
	["Exalted Reputation Rewards"] = true,

	--Alterac Valley (North)
	["Stormpike Guard"] = true,
	["Dun Baldar"] = true,
	["Vanndar Stormpike"] = true,
	["Dun Baldar North Marshal"] = true,
	["Dun Baldar South Marshal"] = true,
	["West Frostwolf Tower Marshal"] = true,
	["East Frostwolf Tower Marshal"] = true,
	["Warmaster Laggrond"] = true,
	["Thanthaldis Snowgleam"] = true,
	["Icewing Marshal"] = true,
	["Iceblood Marshal"] = true,
	["Stonehearth Marshal"] = true,
	["East Frostwolf Marshal"] = true,
	["West Frostwolf Marshal"] = true,
	["Tower Point Marshal"] = true,
	["Prospector Stonehewer"] = true,
	["Irondeep Mine"] = true,
	["Morloch"] = true,
	["Umi Thorson"] = true,
	["Keetar"] = true,
	["Arch Druid Renferal"] = true,
	["Dun Baldar North Bunker"] = true,
	["Wing Commander Mulverick"] = true,
	["Murgot Deepforge"] = true,
	["Dirk Swindle"] = true,
	["Athramanis"] = true,
	["Lana Thunderbrew"] = true,
	["Stormpike Aid Station"] = true,
	["Stormpike Stable Master"] = true,
	["Stormpike Ram Rider Commander"] = true,
	["Svalbrad Farmountain"] = true,
	["Kurdrum Barleybeard"] = true,
	["Stormpike Quartermaster"] = true,
	["Jonivera Farmountain"] = true,
	["Brogus Thunderbrew"] = true,
	["Wing Commander Ichman"] = true,
	["Wing Commander Slidore"] = true,
	["Wing Commander Vipore"] = true,
	["Dun Baldar South Bunker"] = true,
	["Corporal Noreg Stormpike"] = true,
	["Gaelden Hammersmith"] = true,
	["Stormpike Graveyard"] = true,
	["Icewing Cavern"] = true,
	["Stormpike Banner"] = true,
	["Stormpike Lumber Yard"] = true,
	["Wing Commander Jeztor"] = true,
	["Icewing Bunker"] = true,
	["Wing Commander Guse"] = true,
	["Stonehearth Graveyard"] = true,
	["Stonehearth Outpost"] = true,
	["Captain Balinda Stonehearth"] = true,
	["Snowfall Graveyard"] = true,
	["Korrak the Bloodrager"] = true,
	["Ichman's Beacon"] = true,
	["Mulverick's Beacon"] = true,
	["Stonehearth Bunker"] = true,
	["Ivus the Forest Lord"] = true,
	["Western Crater"] = true,
	["Vipore's Beacon"] = true,
	["Jeztor's Beacon"] = true,
	["Eastern Crater"] = true,
	["Slidore's Beacon"] = true,
	["Guse's Beacon"] = true,
	["Graveyards, Capturable Areas"] = true,
	["Bunkers, Towers, Destroyable Areas"] = true,
	["Assault NPCs, Quest Areas"] = true,
	["Steamsaw"] = true,

	--Alterac Valley (South)
	["Frostwolf Clan"] = true,
	["Frostwolf Keep"] = true,
	["Drek'Thar"] = true,
	["Duros"] = true,
	["Drakan"] = true,
	["West Frostwolf Warmaster"] = true,
	["East Frostwolf Warmaster"] = true,
	["Tower Point Warmaster"] = true,
	["Iceblood Warmaster"] = true,
	["Icewing Warmaster"] = true,
	["Stonehearth Warmaster"] = true,
	["Dun Baldar North Warmaster"] = true,
	["Dun Baldar South Warmaster"] = true,
	["Lokholar the Ice Lord"] = true,
	["Iceblood Garrison"] = true,
	["Captain Galvangar"] = true,
	["Iceblood Tower"] = true,
	["Iceblood Graveyard"] = true,
	["Tower Point"] = true,
	["Coldtooth Mine"] = true,
	["Taskmaster Snivvle"] = true,
	["Masha Swiftcut"] = true,
	["Aggi Rumblestomp"] = true,
	["Frostwolf Graveyard"] = true,
	["Jotek"] = true,
	["Smith Regzar"] = true,
	["Primalist Thurloga"] = true,
	["Sergeant Yazra Bloodsnarl"] = true,
	["Frostwolf Stable Master"] = true,
	["Frostwolf Wolf Rider Commander"] = true,
	["Frostwolf Quartermaster"] = true,
	["West Frostwolf Tower"] = true,
	["East Frostwolf Tower"] = true,
	["Frostwolf Relief Hut"] = true,
	["Wildpaw Cavern"] = true,
	["Frostwolf Banner"] = true,

	--Arathi Basin
	["The Defilers"] = true,
	["The League of Arathor"] = true,
	["Trollbane Hall"] = true,
	["Defiler's Den"] = true,
	["Stables"] = true,
	["Gold Mine"] = true,
	["Blacksmith"] = true,
	["Lumber Mill"] = true,
	["Farm"] = true,

	--Warsong Gulch
	["Warsong Outriders"] = true,
	["Silverwing Sentinels"] = true,
	["Silverwing Hold"] = true,
	["Warsong Lumber Mill"] = true,

	--Flight points
	["Flight Path Maps"] = true,
	["Druid-only"] = true,
	["Aerie Peak"] = true,
	["Astranaar"] = true,
	["Auberdine"] = true,
	["Bloodvenom Post"] = true,
	["Booty Bay"] = true,
	["Brackenwall Village"] = true,
	["Camp Mojache"] = true,
	["Camp Taurajo"] = true,
	["Cenarion Hold"] = true,
	["Chillwind Point"] = true,
	["Crossroads"] = true,
	["Darkshire"] = true,
	["Everlook"] = true,
	["Feathermoon Stronghold"] = true,
	["Flame Crest"] = true,
	["Freewind Post"] = true,
	["Gadgetzan"] = true,
	["Grom'Gol Base Camp"] = true,
	["Hammerfall"] = true,
	["Kargath"] = true,
	["Lakeshire"] = true,
	["Light's Hope Chapel"] = true,
	["Marshal's Refuge"] = true,
	["Menethil Harbor"] = true,
	["Morgan's Vigil"] = true,
	["Nighthaven"] = true,
	["Nijel's Point"] = true,
	["Ratchet"] = true,
	["Refuge Pointe"] = true,
	["Revantusk Village"] = true,
	["Rut'Theran Village"] = true,
	["Sentinel Hill"] = true,
	["Shadowprey Village"] = true,
	["Southshore"] = true,
	["Splintertree Post"] = true,
	["Stonard"] = true,
	["Stonetalon Peak"] = true,
	["Sun Rock Retreat"] = true,
	["Talonbranch Glade"] = true,
	["Talrendis Point"] = true,
	["Tarren Mill"] = true,
	["Thalanaar"] = true,
	["The Sepulcher"] = true,
	["The Shimmering Flats"] = true,
	["Thelsamar"] = true,
	["Theramore Isle"] = true,
	["Thorium Point"] = true,
	["Valormok"] = true,
	["Zoram'gar Outpost"] = true,
	["South of the path along Lake Elune'ara"] = true,
	["West of the path to Timbermaw Hold"] = true,
	["Kalanar's Strongbox"] = true,
	["Caverns of Time"] = true,
	["Arc'tiras / Vault Armory Equipment"] = true,
	["Manuscript of Hydromancy II"] = true,
	["Harlow Family Chest"] = true,
	["Dawnstone Plans"] = true,
	["Greymane Armor"] = true,
	["Engraved Golden Bracelet"] = true,
	["Comfortable Pillow"] = true,
	["Councilman Kyleson"] = true,
	["Lord Ebonlocke"] = true,
	["Obsidian Rod"] = true,
	["Duke Rothlen"] = true,
	["Lower Karazhan Halls Enchants"] = true,
	["Tower of Karazhan Sets"] = true,
	["Incendosaur Skin Armor"] = true,
	["Favor of Erennius (ES Hard Mode)"] = true,
	["Hateforge Chemistry Documents"] = true,
	["Tome of Arcane Intricacies and Magical Phenomenon IX"] = true,

	--Atlasloot
	["AtlasLoot"] = true,
	["Atlas"] = true,
	["No match found for"] = true,
	["Search"] = true,
	["Clear"] = true,
	["Select Loot Table"] = true,
	["Select Sub-Table"] = true,
	["Drop Rate: "] = true,
	["Left-click to open AtlasLoot.\nMiddle-click for AtlasLoot options.\nRight-click and drag to move this button."] = true,
	["Various Locations"] = true,
	["NoticeFrame"] = "If you find anything missing, please report it at |cffbe5effhttps://github.com/KasVital/Atlas-TW/issues/|r.",
	[" is safe."] = true,
	["Server queried for "] = true,
	[". Right click on any other item to refresh the loot page."] = true,
	["Level 60"] = true,
	["Misc"] = true,
	["Test"] = true,
	["Skill:"] = true,
	["Level:"] = true,
	["QuickLook"] = true,
	["Add to QuickLooks:"] = true,
	["Assign this loot table to QuickLook"] = true,
	["Query Server"] = true,
	["Dungeons & Raids"] = true,
	["Button Position"] = true,
	["Button Radius"] = true,
	["Reset Position"] = true,
	["Minimap button has been reset!"] = true,
	["has been reset!"] = true,
	["|cff9d9d9dALT+Click to clear|r"] = true,
	["ALT+Click on item to add or remove it from WishList"] = true,
	["Atlasloot Options"] = true,
	["Safe Chat Links |cff1eff00(recommended)|r"] = true,
	["Enable all Chat Links |cffff0000(use at own risk)|r"] = true,
	["Default Tooltips"] = true,
	["Lootlink Tooltips"] = true,
	["|cff9d9d9dLootlink Tooltips|r"] = true,
	["ItemSync Tooltips"] = true,
	["|cff9d9d9dItemSync Tooltips|r"] = true,
	["Use EquipCompare"] = true,
	["|cff9d9d9dUse EquipCompare|r"] = true,
	["Make Loot Table Opaque"] = true,
	["Show IDs at all times"] = true,
	["Hide AtlasLoot Panel"] = true,
	["Show Minimap Button"] = true,
	["Suppress text spam when querying items"] = true,
	["Done"] = true,
	["Loot Panel"] = true,
	["WishList"] = true,
	["Search Result: %s"] = true,
	["Last Result"] = true,
	["Search options"] = true,
	["Partial matching"] = true,
	["If checked, AtlasLoot searches item names for a partial match."] = true,
	["Queries the server for all items"] = true,
	["on this page. The items will be"] = true,
	["refreshed when you next mouse"] = true,
	["over them."] = true,
	["Default settings applied!"] = true,
	["Default Settings"] = true,
	["AtlasLoot Error!"] = true,
	["To cast "] = true,
	[" the following items are needed:"] = true,
	[" you need this: "] = true,
	["To craft "] = true,
	[" the following reagents are needed:"] = true,
	[" added to the WishList."] = true,
	[" already in the WishList!"] = true,
	[" deleted from the WishList."] = true,
	[" not listed in loot table registry, please report this message to the AtlasLoot forums at https://github.com/KasVital/Atlas-TW/issues"] = true,
	["Options"] = true,
	["Collections"] = true,
	["Factions"] = true,
	["World Events"] = true,
	["Crafting"] = true,
	["Sets"] = true,
	["Priest Sets"] = true,
	["Mage Sets"] = true,
	["Warlock Sets"] = true,
	["Rogue Sets"] = true,
	["Druid Sets"] = true,
	["Hunter Sets"] = true,
	["Shaman Sets"] = true,
	["Paladin Sets"] = true,
	["Warrior Sets"] = true,
	["Crafted Sets - Blacksmithing"] = true,
	["Crafted Sets - Tailoring"] = true,
	["Crafted Sets - Leatherworking"] = true,
	["Setup"] = true,
	["Professions"] = true,
	["ItemID:"] = true,
	["SpellID:"] = true,
	["You can right-click to attempt to query the server. You may be disconnected."] = true,
	["Mount"] = true,
	["Enchant"] = true,
	["Trade Goods"] = true,
	["Scope"] = true,
	["Book"] = true,
	["Banner"] = true,
	["Set"] = true,
	["Token"] = true,
	["Token Hand-Ins"] = true,
	["Fireworks"] = true,
	["Cloak"] = true,
	["Weapon"] = true,
	["Weapons"] = true,
	["Classes"] = true,
	["This Item Begins a Quest"] = true,
	["Quest Item"] = true,
	["Quest Reward"] = true,
	["Shared"] = true,
	["Unique"] = true,
	["Right Half"] = true,
	["Left Half"] = true,
	["vendor"] = true,
	["pickpocketed"] = true,
	["Slot"] = true,
	["28 Slot Bag"] = true,
	["18 Slot Bag"] = true,
	["10 Slot Bag"] = true,
	["24 Slot"] = true,
	["16 Slot"] = true,
	["(185)"] = true,
	["(160)"] = true,
	["(300)"] = true,
	["(295)"] = true,
	["(290)"] = true,
	["(285)"] = true,
	["(275)"] = true,
	["(265)"] = true,
	["(200)"] = true,
	["(250)"] = true,
	["(125)"] = true,
	["(1)"] = true,
	["Schematic: Field Repair Bot 74A"] = true,
	["Container"] = true,
	["Consumable"] = true,
	["Needed to purchase rewards"] = true,
	["Use to purchase rewards"] = true,
	["World"] = true,
	["Rare Mobs"] = true,
	["Tier 1"] = true,
	["Tier 2"] = true,
	["Tier 3"] = true,
	["Used to summon boss"] = true,
	["Coin"] = true,
	["Doll"] = true,
	["Water"] = true,
	["Earth"] = true,
	["Air"] = true,
	["Warpwood Pod"] = true,
	["Scarab Coffer"] = true,
	["Greater Scarab Coffer"] = true,
	["Master Angler"] = true,
	["First Prize"] = true,
	["Rare Fish Rewards"] = true,
	["Rare Fish"] = true,
	["Arena Spoils"] = true,
	["random stats"] = true,
	["random resistance"] = true,
	["random color"] = true,
	["Toy"] = true,
	["Path of the Conqueror"] = true,
	["Path of the Invoker"] = true,
	["Path of the Protector"] = true,
	["Scourge Invasion Bosses"] = true,
	["Dragonscale"] = true,
	["Tribal"] = true,
	["Elemental"] = true,
	["Primal Hakkari Kossack"] = true,
	["Primal Hakkari Shawl"] = true,
	["Primal Hakkari Bindings"] = true,
	["Primal Hakkari Sash"] = true,
	["Primal Hakkari Stanchion"] = true,
	["Primal Hakkari Aegis"] = true,
	["Primal Hakkari Girdle"] = true,
	["Primal Hakkari Armsplint"] = true,
	["Primal Hakkari Tabard"] = true,
	["Qiraji Ornate Hilt"] = true,
	["Qiraji Martial Drape"] = true,
	["Qiraji Magisterial Ring"] = true,
	["Qiraji Ceremonial Ring"] = true,
	["Qiraji Regal Drape"] = true,
	["Qiraji Spiked Hilt"] = true,
	["Qiraji Bindings of Dominance"] = true,
	["Qiraji Bindings of Command"] = true,
	["Vek'nilash's Circlet"] = true,
	["Vek'lor's Diadem"] = true,
	["Ouro's Intact Hide"] = true,
	["Skin of the Great Sandworm"] = true,
	["Husk of the Old God"] = true,
	["Carapace of the Old God"] = true,
	["Zul'Gurub Rings"] = true,
	["The Twin Blades of Hakkari"] = true,
	["Primal Blessing"] = true,
	["AQ40 Class Sets"] = true,
	["AQ20 Class Sets"] = true,
	["Pre 60 Sets"] = true,
	["Crafted Sets"] = true,
	["Crafted Epic Weapons"] = true,
	["AQ20"] = true,
	["AQ40"] = true,
	["Zul'Gurub Class Sets"] = true,
	["Shared Zul'Gurub Priest Drops"] = true,
	["Enchants"] = true,
	["Tier 0.5"] = true,
	["Tier 0.5 Summonable"] = true,
	["Dungeon Sets"] = true,
	["PvP Sets"] = true,
	["PvP Accessories - Alliance"] = true,
	["PvP Accessories - Horde"] = true,
	["PvP Rewards"] = true,
	["PvP Armor Sets"] = true,
	["PvP Weapons"] = true,
	["PvP Accessories"] = true,
	["Collector's Edition"] = true,
	["Plans: Serenity"] = true,
	["Plans: Corruption"] = true,
	["Epic Set"] = true,
	["Rare Set"] = true,
	["Legendary Items"] = true,
	["Artifact Items"] = true,
	["Fire Resistance Gear"] = true,
	["Arcane Resistance Gear"] = true,
	["Nature Resistance Gear"] = true,
	["Rare Pets"] = true,
	["Rare Mounts"] = true,
	["Old Mounts"] = true,
	["PvP Mounts"] = true,
	["Unobtainable Mounts"] = true,
	["Tabards"] = true,
	["World Epics"] = true,
	["World Blues"] = true,
	["Level 30-39"] = true,
	["Level 40-49"] = true,
	["Level 50-60"] = true,
	["Druid of the Fang"] = true,
	["Defias Strip Miner"] = true,
	["Defias Pirate"] = true,
	["Prisoner/Insurgent/Convict"] = true,
	["Defender"] = true,
	["Protector"] = true,
	["Myrmidon"] = true,
	["Champion"] = true,
	["Centurion"] = true,
	["Guardsman"] = true,
	["Scarlet Trainee"] = true,
	["Plagued Hatchling"] = true,
	["Shadowforge Flame Keeper"] = true,
	["Hammered Patron"] = true,
	["Scarshield Warlock"] = true,
	["Crimson Sorcerer"] = true,
	["Thuzadin Shadowcaster"] = true,
	["Crimson Inquisitor"] = true,
	["Crimson Battle Mage"] = true,
	["Ghoul Ravener"] = true,
	["Spectral Citizen"] = true,
	["Spectral Researcher"] = true,
	["Scholomance Adept"] = true,
	["Scholomance Dark Summoner"] = true,
	["Twilight Corrupter"] = true,
	["Blackhand Elite"] = true,
	["Blackhand Assassin"] = true,
	["Firebrand Pyromancer"] = true,
	["Firebrand Invoker"] = true,
	["Firebrand Grunt"] = true,
	["Firebrand Legionnaire"] = true,
	["Death Talon Wyrmguard"] = true,
	["Dark Iron Agent"] = true,
	["Molten Destroyer"] = true,
	["Spire Spider/Spiderling"] = true,
	["Spirestone Warlord"] = true,
	["Spirestone Mystic"] = true,
	["Anvilrage Captain"] = true,
	["Anvilrage Marshal"] = true,
	["Doomforge Arcanasmith"] = true,
	["Weapon Technician"] = true,
	["Doomforge Craftsman"] = true,
	["Murk Worm"] = true,
	["Atal'ai Witch Doctor"] = true,
	["Crimson Templar"] = true,
	["Azure Templar"] = true,
	["Hoary Templar"] = true,
	["Earthen Templar"] = true,
	["The Duke of Cynders"] = true,
	["The Duke of Fathoms"] = true,
	["The Duke of Zephyrs"] = true,
	["The Duke of Shards"] = true,
	["Templars"] = true,
	["Dukes"] = true,
	["High Council"] = true,
	["The Nameles Prophet"] = true,
	["Rajaxx's Captains"] = true,
	["Dark Coffer"] = true,
	["Fengus's Chest"] = true,
	["Unforged Rune Covered Breastplate"] = true,
	["Malor the Zealous"] = true,
	["Gift of Adoration"] = true,
	["Box of Chocolates"] = true,
	["Treat Bag"] = true,
	["Gaily Wrapped Present"] = true,
	["Festive Gift"] = true,
	["Gently Shaken Gift"] = true,
	["Brightly Colored Egg"] = true,
	["Lunar Festival Fireworks Pack"] = true,
	["Lucky Red Envelope"] = true,
	["Small Rocket Recipes"] = true,
	["Large Rocket Recipes"] = true,
	["Cluster Rocket Recipes"] = true,
	["Large Cluster Rocket Recipes"] = true,
	["Tribute Chest"] = true,
	["Abyssal Council"] = true,
	["Children's Week"] = true,
	["Elemental Invasion"] = true,
	["Feast of Winter Veil"] = true,
	["Gurubashi Arena"] = true,
	["Harvest Festival"] = true,
	["Love is in the Air"] = true,
	["Midsummer Fire Festival"] = true,
	["Noblegarden"] = true,
	["Stranglethorn Fishing Extravaganza"] = true,
	["Keys"] = true,
	["Half-Buried Treasure Chest"] = true,
	["Princess Tempestria"] = true,
	["Apprentice"] = true,
	["Journeyman"] = true,
	["Expert"] = true,
	["Artisan"] = true,
	["Master Axesmith"] = true,
	["Master Hammersmith"] = true,
	["Master Swordsmith"] = true,
	["Gnomish Engineering"] = true,
	["Goblin Engineering"] = true,
	["Relic Coffer"] = true,
	["Secret Safe"] = true,
	["Dark Keeper"] = true,
	["LW"] = true,
	["Rank 14 Weapons"] = true,
	["Druid"] = true,
	["Hunter"] = true,
	["Mage"] = true,
	["Paladin"] = true,
	["Priest"] = true,
	["Rogue"] = true,
	["Shaman"] = true,
	["Warlock"] = true,
	["Warrior"] = true,
	["Head"] = true,
	["Neck"] = true,
	["Shoulder"] = true,
	["Chest"] = true,
	["Shirt"] = true,
	["Tabard"] = true,
	["Wrist"] = true,
	["Hands"] = true,
	["Waist"] = true,
	["Legs"] = true,
	["Feet"] = true,
	["Ring"] = true,
	["Trinket"] = true,
	["Held In Off-hand"] = true,
	["Relic"] = true,
	["Relics"] = true,
	["One-Hand"] = true,
	["Two-Hand"] = true,
	["Main Hand"] = true,
	["Off Hand"] = true,
	["Axe"] = true,
	["Bow"] = true,
	["Crossbow"] = true,
	["Dagger"] = true,
	["Gun"] = true,
	["Mace"] = true,
	["Polearm"] = true,
	["Shield"] = true,
	["Staff"] = true,
	["Sword"] = true,
	["Thrown"] = true,
	["Wand"] = true,
	["Fist Weapon"] = true,
	["Idol"] = true,
	["Totem"] = true,
	["Libram"] = true,
	["Arrow"] = true,
	["Bullet"] = true,
	["Quiver"] = true,
	["Ammo Pouch"] = true,
	["Bag"] = true,
	["Potion"] = true,
	["Food"] = true,
	["Drink"] = true,
	["Bandage"] = true,
	["Reagent"] = true,
	["Binds when picked up"] = true,
	["Darkmoon Faire Card"] = true,
	["Fishing Pole"] = true,
	["[27-36] Scarlet Monastery (Graveyard)"] = "|cffffffff[27-36]|cffffd200 Scarlet Monastery (Graveyard)",
	["[32-41] Scarlet Monastery (Armory)"] = "|cffffffff[32-41]|cffffd200 Scarlet Monastery (Armory)",
	["[35-45] Scarlet Monastery (Cathedral)"] = "|cffffffff[35-45]|cffffd200 Scarlet Monastery (Cathedral)",
	["[28-39] Scarlet Monastery (Library)"] = "|cffffffff[28-39]|cffffd200 Scarlet Monastery (Library)",
	["Kara40"] = true,
	["Turtlhu, the Black Turtle of Doom"] = true,
	["Blood Ring Friendly Rewards"] = true,
	["Blood Ring Honored Rewards"] = true,
	["Blood Ring Revered Rewards"] = true,
	["Blood Ring Exalted Rewards"] = true,
	["AB 20-29 Honored Rewards"] = true,
	["AB 30-39 Honored Rewards"] = true,
	["AB 40-49 Honored Rewards"] = true,
	["AB 50-59 Honored Rewards"] = true,
	["AB 20-29 Revered Rewards"] = true,
	["AB 30-39 Revered Rewards"] = true,
	["AB 40-49 Revered Rewards"] = true,
	["AB 50-59 Revered Rewards"] = true,
	["AB Exalted Rewards"] = true,
	["AV Friendly Rewards"] = true,
	["AV Honored Rewards"] = true,
	["AV Revered Rewards"] = true,
	["AV Exalted Rewards"] = true,
	["Friendly"] = true,
	["Honored"] = true,
	["Revered"] = true,
	["Exalted"] = true,
	["Gemstones"] = true,
	["Token of Blood Rewards"] = true,
	["Cloth"] = true,
	["Leather"] = true,
	["Mail"] = true,
	["Plate"] = true,
	["Friendly Rewards"] = true,
	["Honored Rewards"] = true,
	["Revered Rewards"] = true,
	["Exalted Rewards"] = true,
	["PvP Trinkets"] = true,
	["Cooking Fire"] = true,
	["Anvil"] = true,
	["Black Anvil"] = true,
	["Forge"] = true,
	["Black Forge"] = true,
	["Smokywood Pastures Special Gift"] = true,
	["Smokywood Pastures"] = true,
	["Rank 1"] = true,
	["Rank 2"] = true,
	["Rank 3"] = true,
	["Rank 4"] = true,
	["Rank 5"] = true,
	["Rank 6"] = true,
	["Rank 7"] = true,
	["Rank 8"] = true,
	["Rank 9"] = true,
	["Rank 10"] = true,
	["Rank 11"] = true,
	["Rank 12"] = true,
	["Rank 13"] = true,
	["Rank 14"] = true,
	["One-Handed Axes"] = true,
	["Two-Handed Axes"] = true,
	["One-Handed Maces"] = true,
	["Two-Handed Maces"] = true,
	["One-Handed Swords"] = true,
	["Two-Handed Swords"] = true,
	["Fist Weapons"] = true,
	["Polearms"] = true,
	["Staves"] = true,
	["Bows"] = true,
	["Crossbows"] = true,
	["Guns"] = true,
	["Shields"] = true,
	["Wands"] = true,
	["Rings"] = true,
	["Ivus & Lokholar"] = true,
	["Tablet of Ryun'eh"] = true,
	["Gloves"] = true,
	["Boots"] = true,
	["2H Weapon"] = true,
	["Flasks"] = true,
	["Protection Potions"] = true,
	["Healing and Mana Potions"] = true,
	["Transmutes"] = true,
	["Defensive Potions and Elixirs"] = true,
	["Offensive Potions and Elixirs"] = true,
	["Other"] = true,
	["Helm"] = true,
	["Shoulders"] = true,
	["Bracers"] = true,
	["Belt"] = true,
	["Pants"] = true,
	["Bags"] = true,
	["Axes"] = true,
	["Swords"] = true,
	["Maces"] = true,
	["Fist"] = true,
	["Daggers"] = true,
	["Belt Buckles"] = true,
	["Equipment"] = true,
	["Trinkets"] = true,
	["Explosives"] = true,
	["Parts"] = true,
	["Amulets"] = true,
	["Show Source on Tooltips"] = true,
	["Off-hand"] = true,
	["Rank 2-9"] = true,
	["Rank 7-13"] = true,
	["Overseer Taskmaster"] = true,
	["Kara40 Sets"] = "Tower of Karazhan Sets",
	["High Marshal Whirlaxis"] = true,
	["Baron Kazum"] = true,
	["Prince Skaldrenox"] = true,
	["Lord Skwol"] = true,
	["[RAID] Lower Karazhan Halls"] = "|cffff0000[RAID]|cffffd200 Lower Karazhan Halls",
	["[RAID] Emerald Sanctum"] = "|cffff0000[RAID]|cffffd200 Emerald Sanctum",
	["[42-50] Gilneas City"] = "|cffffffff[42-50]|cffffd200 Gilneas City",
	["[RAID] Zul'Gurub"] = "|cffff0000[RAID]|cffffd200 Zul'Gurub",
	["[44-54] Zul'Farrak"] = "|cffffffff[44-54]|cffffd200 Zul'Farrak",
	["[17-24] Wailing Caverns"] = "|cffffffff[17-24]|cffffd200 Wailing Caverns",
	["[40-51] Uldaman"] = "|cffffffff[40-51]|cffffd200 Uldaman",
	["[RAID] Temple of Ahn'Qiraj"] = "|cffff0000[RAID]|cffffd200 Temple of Ahn'Qiraj",
	["[58-60] Stratholme"] = "|cffffffff[58-60]|cffffd200 Stratholme",
	["[22-30] The Stockade"] = "|cffffffff[22-30]|cffffd200 The Stockade",
	["[22-30] Shadowfang Keep"] = "|cffffffff[22-30]|cffffd200 Shadowfang Keep",
	["[58-60] Scholomance"] = "|cffffffff[58-60]|cffffd200 Scholomance",
	["[RAID] Ruins of Ahn'Qiraj"] = "|cffff0000[RAID]|cffffd200 Ruins of Ahn'Qiraj",
	["[29-38] Razorfen Kraul"] = "|cffffffff[29-38]|cffffd200 Razorfen Kraul",
	["[36-46] Razorfen Downs"] = "|cffffffff[36-46]|cffffd200 Razorfen Downs",
	["[13-18] Ragefire Chasm"] = "|cffffffff[13-18]|cffffd200 Ragefire Chasm",
	["[RAID] Onyxia's Lair"] = "|cffff0000[RAID]|cffffd200 Onyxia's Lair",
	["[RAID] Naxxramas"] = "|cffff0000[RAID]|cffffd200 Naxxramas",
	["[RAID] Molten Core"] = "|cffff0000[RAID]|cffffd200 Molten Core",
	["[45-55] Maraudon"] = "|cffffffff[45-55]|cffffd200 Maraudon",
	["[29-38] Gnomeregan"] = "|cffffffff[29-38]|cffffd200 Gnomeregan",
	["[57-60] Dire Maul (West)"] = "|cffffffff[57-60]|cffffd200 Dire Maul (West)",
	["[57-60] Dire Maul (North)"] = "|cffffffff[57-60]|cffffd200 Dire Maul (North)",
	["[55-60] Dire Maul (East)"] = "|cffffffff[55-60]|cffffd200 Dire Maul (East)",
	["[17-24] The Deadmines"] = "|cffffffff[17-24]|cffffd200 The Deadmines",
	["[60] Stormwind Vault"] = "|cffffffff[60]|cffffd200 Stormwind Vault",
	["[60] Caverns of Time: Black Morass"] = "|cffffffff[60]|cffffd200 Caverns of Time: Black Morass",
	["[58-60] Karazhan Crypt"] = "|cffffffff[58-60]|cffffd200 Karazhan Crypt",
	["[32-38] The Crescent Grove"] = "|cffffffff[32-38]|cffffd200 The Crescent Grove",
	["[50-60] Hateforge Quarry"] = "|cffffffff[50-60]|cffffd200 Hateforge Quarry",
	["[RAID] Blackwing Lair"] = "|cffff0000[RAID]|cffffd200 Blackwing Lair",
	["[58-60] Upper Blackrock Spire"] = "|cffffffff[58-60]|cffffd200 Upper Blackrock Spire",
	["[55-60] Lower Blackrock Spire"] = "|cffffffff[55-60]|cffffd200 Lower Blackrock Spire",
	["[52-60] Blackrock Depths"] = "|cffffffff[52-60]|cffffd200 Blackrock Depths",
	["[23-32] Blackfathom Deeps"] = "|cffffffff[23-32]|cffffd200 Blackfathom Deeps",
	["[50-60] The Sunken Temple"] = "|cffffffff[50-60]|cffffd200 The Sunken Temple",
	["[RAID] Tower of Karazhan"] = "|cffff0000[RAID]|cffffd200 Tower of Karazhan",
	["Earthcaller Rezengal"] = true,
	["Graypaw Alpha"] = true,
	["Shade Mage"] = true,
	["Blazespark"] = true,
	["Witch Doctor Tan'zo"] = true,
	["Widow of the Woods"] = true,
	["Dawnhowl"] = true,
	["Maltimor's Prototype"] = true,
	["Bonecruncher"] = true,
	["Duskskitter"] = true,
	["Baron Perenolde"] = true,
	["Kin'Tozo"] = true,
	["Grug'thok the Seer"] = true,
	["M-0L1Y"] = true,
	["Explorer Ashbeard"] = true,
	["Jal'akar"] = true,
	["Embereye"] = true,
	["Ruk'thok the Pyromancer"] = true,
	["Tarangos"] = true,
	["Ripjaw"] = true,
	["Xalvic Blackclaw"] = true,
	["Aquitus"] = true,
	["Firstborn of Arugal"] = true,
	["Letashaz"] = true,
	["Margon the Mighty"] = true,
	["The Wandering Knight"] = true,
	["Stoneshell"] = true,
	["Zareth Terrorblade"] = true,
	["Highvale Silverback"] = true,
	["Mallon The Moontouched"] = true,
	["Blademaster Kargron"] = true,
	["Professor Lysander"] = true,
	["Admiral Barean Westwind"] = true,
	["Azurebeak"] = true,
	["Barkskin Fisher"] = true,
	["Crusader Larsarius"] = true,
	["Shadeflayer Goliath"] = true,
	["Nature, Fire, Arcane, Shadow, Frost"] = true,
	["Ironspine"] = true,
	["Nature, Shadow"] = true,
	["Karazhan Crypt Key"] = true,
	["Mini Bosses"] = true,
} end)