local L = AtlasTW.Local
local BC = AceLibrary("Babble-Class-2.2")
local BS = AceLibrary("Babble-Spell-2.2a")
local BB = AceLibrary("Babble-Boss-2.2a")
local BF = AceLibrary("Babble-Faction-2.2a")
local BZ = AceLibrary("Babble-Zone-2.2a")
local BIS = AceLibrary("Babble-ItemSet-2.2a")

-- AtlasLoot_TableRegistry больше не используется, данные берутся из AtlasMaps
-- Оставлено для совместимости
AtlasLoot_TableRegistry = {
    ["World"] = {
        Name = L["World"],
        Entry = {
            { ID = "WBAzuregos", Title = BB["Azuregos"] },
            { ID = "WBLordKazzak", Title = BB["Lord Kazzak"] },
            { ID = "WBEmeriss", Title = BB["Emeriss"] },
            { ID = "WBLethon", Title = BB["Lethon"] },
            { ID = "WBTaerar", Title = BB["Taerar"] },
            { ID = "WBYsondre", Title = BB["Ysondre"] },
            { ID = "WBTurtlhu", Title = L["Turtlhu, the Black Turtle of Doom"] },
            { ID = "WBNerubian", Title = BB["Nerubian Overseer"] },
            { ID = "WBReaver", Title = BB["Dark Reaver of Karazhan"] },
            { ID = "WBOstarius", Title = BB["Ostarius"] },
            { ID = "WBConcavius", Title = BB["Concavius"] },
            { ID = "WBCowKing", Title = BB["Moo"] },
            { ID = "WBClackora", Title = BB["Cla'ckora"] },
    --        { ID = "WBRareMobs", Title = L["Rare Mobs"] },
            { ID = "ShadeMage", Title = L["Shade Mage"] },
            { ID = "GraypawAlpha", Title = L["Graypaw Alpha"] },
            { ID = "EarthcallerRezengal", Title = L["Earthcaller Rezengal"] },
            { ID = "Blazespark", Title = L["Blazespark"] },
            { ID = "WitchDoctorTanzo", Title = L["Witch Doctor Tan'zo"] },
            { ID = "Dawnhowl", Title = L["Dawnhowl"] },
            { ID = "WidowoftheWoods", Title = L["Widow of the Woods"] },
            { ID = "MaltimorsPrototype", Title = L["Maltimor's Prototype"] },
            { ID = "Bonecruncher", Title = L["Bonecruncher"] },
            { ID = "Duskskitterer", Title = L["Duskskitterer"] },
            { ID = "BaronPerenolde", Title = L["Baron Perenolde"] },
            { ID = "KinTozo", Title = L["Kin'Tozo"] },
            { ID = "M0L1Y", Title = L["M-0L1Y"] },
            { ID = "Grugthok", Title = L["Grug'thok the Seer"] },
            { ID = "Ashbeard", Title = L["Explorer Ashbeard"] },
            { ID = "Jalakar", Title = L["Jal'akar"] },
            { ID = "Ripjaw", Title = L["Ripjaw"] },
            { ID = "Rukthok", Title = L["Ruk'thok the Pyromancer"] },
            { ID = "Embereye", Title = L["Embereye"] },
            { ID = "Xalvic", Title = L["Xalvic Blackclaw"] },
            { ID = "FirstbornofArugal", Title = L["Firstborn of Arugal"] },
            { ID = "MargontheMighty", Title = L["Margon the Mighty"] },
            { ID = "WanderingKnight", Title = L["The Wandering Knight"] },
            { ID = "Letashaz", Title = L["Letashaz"] },
            { ID = "Aquitus", Title = L["Aquitus"] },
            { ID = "Stoneshell", Title = L["Stoneshell"] },
            { ID = "Tarangos", Title = L["Tarangos"] },
            { ID = "Zareth", Title = L["Zareth Terrorblade"] },
            { ID = "HighvaleSilverback", Title = L["Highvale Silverback"] },
            { ID = "Mallon", Title = L["Mallon The Moontouched"] },
            { ID = "ProfessorLysander", Title = L["Professor Lysander"] },
            { ID = "Kargron", Title = L["Blademaster Kargron"] },
            { ID = "Azurebeak", Title = L["Azurebeak"] },
            { ID = "BarkskinFisher", Title = L["Barkskin Fisher"] },
            { ID = "AdmiralBareanWestwind", Title = L["Admiral Barean Westwind"] },
            { ID = "ShadeflayerGoliath", Title = L["Shadeflayer Goliath"] },
            { ID = "CrusaderLarsarius", Title = L["Crusader Larsarius"] },
        },
    },
    ["WorldEvents"] = {
        Name = L["World Events"],
        Entry = {
            { ID = "AbyssalTemplars", Title = L["Abyssal Council"].." - "..L["Templars"] },
            { ID = "AbyssalDukes", Title = L["Abyssal Council"].." - "..L["Dukes"] },
            { ID = "AbyssalLords", Title = L["Abyssal Council"].." - "..L["High Council"] },
            { ID = "ElementalInvasion", Title = L["Elemental Invasion"] },
            { ID = "GurubashiArena", Title = L["Gurubashi Arena"] },
            { ID = "HarvestFestival", Title = L["Harvest Festival"] },
            { ID = "LunarFestival1", Title = L["Lunar Festival"].." 1" },
            { ID = "LunarFestival2", Title = L["Lunar Festival"].." 2" },
            { ID = "Noblegarden", Title = L["Noblegarden"] },
            { ID = "FishingExtravaganza", Title = L["Stranglethorn Fishing Extravaganza"] },
            { ID = "ChildrensWeek", Title = L["Children's Week"] },
            { ID = "Winterviel1", Title = L["Feast of Winter Veil"].." 1" },
            { ID = "Winterviel2", Title = L["Feast of Winter Veil"].." 2" },
            { ID = "WintervielSnowball", Title = L["Snowball"] },
            { ID = "Halloween1", Title = L["Hallow's End"].." 1" },
            { ID = "Halloween2", Title = L["Hallow's End"].." 2" },
            { ID = "Valentineday", Title = L["Love is in the Air"] },
            { ID = "MidsummerFestival", Title = L["Midsummer Fire Festival"] },
            { ID = "ScourgeInvasionEvent1", Title = L["Scourge Invasion"] },
            { ID = "ScourgeInvasionEvent2", Title = L["Scourge Invasion Bosses"] },
        }
    },
    ["Collections"] = {
        Name = L["Collections"],
        Entry = {
--[[             { ID = "Pre60Set", Title = L["Pre 60 Sets"] },
            { ID = "ZgSet", Title = L["Zul'Gurub Sets"] },
            { ID = "Aq20Set", Title = L["Ruins of Ahn'Qiraj Sets"] },
            { ID = "Aq40Set", Title = L["Temple of Ahn'Qiraj Sets"] },
            { ID = "K40Set", Title = L["Tower of Karazhan Sets"] },
            { ID = "PriestSet", Title = "|cffffffff"..L["Priest Sets"] },
            { ID = "MageSet", Title = "|cff68ccef"..L["Mage Sets"] },
            { ID = "WarlockSet", Title = "|cff9382c9"..L["Warlock Sets"] },
            { ID = "RogueSet", Title = "|cfffff468"..L["Rogue Sets"] },
            { ID = "DruidSet", Title = "|cff9382c9"..L["Druid Sets"] },
            { ID = "HunterSet", Title = "|cff9382c9"..L["Hunter Sets"] },
            { ID = "ShamanSet", Title = "|cff9382c9"..L["Shaman Sets"] },
            { ID = "PaladinSet", Title = "|cff9382c9"..L["Paladin Sets"] },
            { ID = "WarriorSet", Title = "|cff9382c9"..L["Warrior Sets"] },
            { ID = "T0Set", Title = L["Tier 0/0.5 Sets"] },
            { ID = "T1Set", Title = L["Tier 1 Sets"] },
            { ID = "T2Set", Title = L["Tier 2 Sets"] },
            { ID = "T3Set", Title = L["Tier 3 Sets"] },
            { ID = "WorldBlues", Title = L["World Blues"] },]]
            { ID = "WorldEpics1", Title = L["World Epics"] .. " 30-39" },
            { ID = "WorldEpics2", Title = L["World Epics"] .. " 40-49" },
            { ID = "WorldEpics3", Title = L["World Epics"] .. " 50-60" },
            { ID = "Legendaries", Title = L["Legendary Items"] },
            { ID = "Artifacts", Title = L["Artifact Items"] },
            { ID = "RarePets1", Title = L["Rare Pets"].." 1" },
            { ID = "RarePets2", Title = L["Rare Pets"].." 2" },
            { ID = "RareMounts", Title = L["Rare Mounts"] },
            { ID = "OldMounts", Title = L["Old Mounts"] },
            { ID = "UnobMounts", Title = L["Unobtainable Mounts"] },
            { ID = "Tabards", Title = L["Tabards"] },
        },
    },
    ["WorldBlues"] = {
        Name = L["World Blues"],
        Entry = {
            { ID = "WorldBluesHead", Title = L["Head"] },
            { ID = "WorldBluesNeck", Title = L["Neck"] },
            { ID = "WorldBluesShoulder", Title = L["Shoulder"] },
            { ID = "WorldBluesBack", Title = L["Back"] },
            { ID = "WorldBluesChest", Title = L["Chest"] },
            { ID = "WorldBluesWrist", Title = L["Wrist"] },
            { ID = "WorldBluesHands", Title = L["Hands"] },
            { ID = "WorldBluesWaist", Title = L["Waist"] },
            { ID = "WorldBluesLegs", Title = L["Legs"] },
            { ID = "WorldBluesFeet", Title = L["Feet"] },
            { ID = "WorldBluesRing", Title = L["Ring"] },
            { ID = "WorldBluesTrinket", Title = L["Trinket"] },
            { ID = "WorldBluesWand", Title = L["Wand"] },
            { ID = "WorldBluesHeldInOffhand", Title = L["Held In Off-hand"] },
            { ID = "WorldBlues1HAxes", Title = L["One-Handed Axes"] },
            { ID = "WorldBlues1HMaces", Title = L["One-Handed Maces"] },
            { ID = "WorldBlues1HSwords", Title = L["One-Handed Swords"] },
            { ID = "WorldBlues2HAxes", Title = L["Two-Handed Axes"] },
            { ID = "WorldBlues2HMaces", Title = L["Two-Handed Maces"] },
            { ID = "WorldBlues2HSwords", Title = L["Two-Handed Swords"] },
            { ID = "WorldBluesDaggers", Title = L["Daggers"] },
            { ID = "WorldBluesFistWeapons", Title = L["Fist Weapons"] },
            { ID = "WorldBluesPolearms", Title = L["Polearms"] },
            { ID = "WorldBluesStaves", Title = L["Staves"] },
            { ID = "WorldBluesBows", Title = L["Bows"] },
            { ID = "WorldBluesCrossbows", Title = L["Crossbows"] },
            { ID = "WorldBluesGuns", Title = L["Guns"] },
            { ID = "WorldBluesShields", Title = L["Shields"] },
        }
    },
--[[     ["WorldEpics"] = {
        Name = L["World Epics"],
        Entry = {
            { ID = "WorldEpics1", Title = L["World Epics"] .. " 30-39" },
            { ID = "WorldEpics2", Title = L["World Epics"] .. " 40-49" },
            { ID = "WorldEpics3", Title = L["World Epics"] .. " 50-60" },
        }
    }, ]]
    ["Factions"] = {
        Name = L["Factions"],
        Entry = {
            { ID = "Argent1", Title = BF["Argent Dawn"].." 1" },
            { ID = "Argent2", Title = BF["Argent Dawn"].." 2" },
            { ID = "Argent3", Title = BF["Argent Dawn"].." 3" },
            { ID = "AQBroodRings", Title = BF["Brood of Nozdormu"] },
            { ID = "Darkmoon", Title = BF["Darkmoon Faire"] },
            { ID = "WaterLords1", Title = BF["Hydraxian Waterlords"] },
            { ID = "Thorium1", Title = BF["Thorium Brotherhood"].." 1" },
            { ID = "Thorium2", Title = BF["Thorium Brotherhood"].." 2" },
            { ID = "Wintersaber1", Title = BF["Wintersaber Trainers"] },
            { ID = "Wildhammer", Title = BF["Wildhammer Clan"] },
            { ID = "LeagueofArathor", Title = BF["The League of Arathor"] },
            { ID = "Stormpike1", Title = BF["Stormpike Guard"] },
            { ID = "Dalaran", Title = BZ["Dalaran"] },
            { ID = "Helf", Title = BF["Silvermoon Remnant"] },
            { ID = "Ironforge", Title = BF["Ironforge"] },
            { ID = "Darnassus", Title = BF["Darnassus"] },
            { ID = "Stormwind", Title = BF["Stormwind"] },
            { ID = "GnomereganExiles", Title = BF["Gnomeregan Exiles"] },
            { ID = "Bloodsail1", Title = BF["Bloodsail Buccaneers"] },
            { ID = "Cenarion1", Title = BF["Cenarion Circle"].." 1" },
            { ID = "Cenarion2", Title = BF["Cenarion Circle"].." 2" },
            { ID = "Cenarion3", Title = BF["Cenarion Circle"].." 3" },
            { ID = "Cenarion4", Title = BF["Cenarion Circle"].." 4" },
            { ID = "GelkisClan1", Title = BF["Gelkis Clan Centaur"] },
            { ID = "MagramClan1", Title = BF["Magram Clan Centaur"] },
            { ID = "Timbermaw", Title = BF["Timbermaw Hold"] },
            { ID = "Zandalar1", Title = BF["Zandalar Tribe"].." 1" },
            { ID = "Zandalar2", Title = BF["Zandalar Tribe"].." 2" },
            { ID = "Warderns1", Title = BF["Wardens of Time"].." 1" },
            { ID = "Warderns2", Title = BF["Wardens of Time"].." 2" },
            { ID = "Frostwolf1", Title = BF["Frostwolf Clan"] },
            { ID = "DarkspearTrolls", Title = BF["Darkspear Trolls"] },
            { ID = "Revantusk", Title = BF["Revantusk Trolls"].." 1" },
            { ID = "Revantusk2", Title = BF["Revantusk Trolls"].." 2" },
            { ID = "Revantusk3", Title = BF["Revantusk Trolls"].." 3" },
            { ID = "DurotarLaborUnion", Title = BF["Durotar Labor Union"] },
            { ID = "Undercity", Title = BZ["Undercity"] },
            { ID = "Orgrimmar", Title = BZ["Orgrimmar"] },
            { ID = "ThunderBluff", Title = BZ["Thunder Bluff"] },
        },
    },
    ["PvP"] = {
        Name = L["PvP Rewards"],
        Entry = {
         --   { ID = "AlteracValley",             Title = BZ["Alterac Valley"] },
         --   { ID = "ArathiBasin",               Title = BZ["Arathi Basin"] },
        --    { ID = "WarsongGulch",              Title = BZ["Warsong Gulch"] },
         --   { ID = "BloodRing",                 Title = BZ["Blood Ring"] },
            { ID = "PvPMountsPvP",              Title = L["PvP Mounts"] },
            { ID = "PvP60Accessories1",         Title = L["PvP Accessories"] },
            { ID = "PvP60Accessories2",         Title = L["PvP Accessories - Alliance"] },
            { ID = "PvP60Accessories3",         Title = L["PvP Accessories - Horde"]  },
         --   { ID = "PvPSet",                    Title = L["PvP Armor Sets"] },
            { ID = "PVPWeapons1",               Title = L["Rank 14 Weapons"].." 1" },
            { ID = "PVPWeapons2",               Title = L["Rank 14 Weapons"].." 2" },
        },
    },
    ["AlteracValley"] = {
        Name = BZ["Alterac Valley"],
        Entry = {
            { ID = "AVRepFriendly",             Title = L["Friendly Reputation Rewards"] },
            { ID = "AVRepHonored",              Title = L["Honored Reputation Rewards"] },
            { ID = "AVRepRevered",              Title = L["Revered Reputation Rewards"] },
            { ID = "AVRepExalted",              Title = L["Exalted Reputation Rewards"] },
            { ID = "AVKorrak",                  Title = L["Korrak the Bloodrager"] },
            { ID = "AVLokholarIvus",            Title = L["Ivus & Lokholar"] },
        },
    },
    ["ArathiBasin"] = {
        Name = BZ["Arathi Basin"],
        Entry = {
            { ID = "ABRepFriendly2029",         Title = L["Friendly"].." 20-29" },
            { ID = "ABRepFriendly3039",         Title = L["Friendly"].." 30-39" },
            { ID = "ABRepFriendly4049",         Title = L["Friendly"].." 40-49" },
            { ID = "ABRepFriendly5059",         Title = L["Friendly"].." 50-59" },
            { ID = "ABRepHonored2029",          Title = L["Honored"].." 20-29" },
            { ID = "ABRepHonored3039",          Title = L["Honored"].." 30-39" },
            { ID = "ABRepHonored4049",          Title = L["Honored"].." 40-49" },
            { ID = "ABRepHonored5059",          Title = L["Honored"].." 50-59" },
            { ID = "ABRepRevered2029",          Title = L["Revered"].." 20-29" },
            { ID = "ABRepRevered3039",          Title = L["Revered"].." 30-39" },
            { ID = "ABRepRevered4049",          Title = L["Revered"].." 40-49" },
            { ID = "ABRepRevered5059",          Title = L["Revered"].." 50-59" },
            { ID = "ABRepExalted",              Title = L["Exalted"].." 60" },
        }
    },
    ["WarsongGulch"] = {
        Name = BZ["Warsong Gulch"],
        Entry = {
            { ID = "WSGRepFriendly2029",        Title = L["Friendly"].." 20-29" },
            { ID = "WSGRepFriendly3039",        Title = L["Friendly"].." 30-39" },
            { ID = "WSGRepFriendly4049",        Title = L["Friendly"].." 40-49" },
            { ID = "WSGRepFriendly5059",        Title = L["Friendly"].." 50-59" },
            { ID = "WSGRepHonored1019",         Title = L["Honored"].." 10-19" },
            { ID = "WSGRepHonored2029",         Title = L["Honored"].." 20-29" },
            { ID = "WSGRepHonored3039",         Title = L["Honored"].." 30-39" },
            { ID = "WSGRepHonored4049",         Title = L["Honored"].." 40-49" },
            { ID = "WSGRepHonored5059",         Title = L["Honored"].." 50-59" },
            { ID = "WSGRepRevered1019",         Title = L["Revered"].." 10-19" },
            { ID = "WSGRepRevered2029",         Title = L["Revered"].." 20-29" },
            { ID = "WSGRepRevered3039",         Title = L["Revered"].." 30-39" },
            { ID = "WSGRepRevered4049",         Title = L["Revered"].." 40-49" },
            { ID = "WSGRepRevered5059",         Title = L["Revered"].." 50-59" },
            { ID = "WSGRepExalted4049",         Title = L["Exalted"].." 40-49" },
            { ID = "WSGRepExalted5059",         Title = L["Exalted"].." 50-59" },
            { ID = "WSGRepExalted60",           Title = L["Exalted"].." 60" },
        },
    },
    ["BloodRing"] = {
        Name = BZ["Blood Ring"],
        Entry = {
            { ID = "BRRepFriendly",             Title = L["Friendly Reputation Rewards"] },
            { ID = "BRRepHonored",              Title = L["Honored Reputation Rewards"] },
            { ID = "BRRepRevered",              Title = L["Revered Reputation Rewards"] },
            { ID = "BRRepExalted",              Title = L["Exalted Reputation Rewards"] },
            { ID = "BRRepTokens",               Title = L["Token of Blood Rewards"] },
        },
    },
    ["PvPSet"] = {
        Name = L["PvP Armor Sets"],
        Entry = {
            { ID = "PVPPriest",                 Title = BC["Priest"].." - "..L["PvP Sets"] },
            { ID = "PVPMage",                   Title = BC["Mage"].." - "..L["PvP Sets"] },
            { ID = "PVPWarlock",                Title = BC["Warlock"].." - "..L["PvP Sets"] },
            { ID = "PVPRogue",                  Title = BC["Rogue"].." - "..L["PvP Sets"] },
            { ID = "PVPDruid",                  Title = BC["Druid"].." - "..L["PvP Sets"] },
            { ID = "PVPHunter",                 Title = BC["Hunter"].." - "..L["PvP Sets"] },
            { ID = "PVPShaman",                 Title = BC["Shaman"].." - "..L["PvP Sets"] },
            { ID = "PVPWarrior",                Title = BC["Warrior"].." - "..L["PvP Sets"] },
        },
    },
    ["Crafting"] = {
        Name = BS["First Aid"],
        Entry = {
            { ID = "Herbalism1", Title = BS["Herbalism"].." 1 - 250" },
            { ID = "Herbalism2", Title = BS["Herbalism"].." 260+" },
            { ID = "FirstAid1", Title = BS["First Aid"] },
            { ID = "Poisons1", Title = BS["Poisons"] },
            { ID = "CraftedWeapons1", Title = L["Crafted Epic Weapons"] },
        }
    },
    ["Alchemy"] = {
        Name = BS["Alchemy"],
        Entry = {
            { ID = "AlchemyApprentice1", Title = BS["Alchemy"]..": "..L["Apprentice"] },
            { ID = "AlchemyJourneyman1", Title = BS["Alchemy"]..": "..L["Journeyman"] },
            { ID = "AlchemyExpert1", Title = BS["Alchemy"]..": "..L["Expert"] },
            { ID = "AlchemyArtisan1", Title = BS["Alchemy"]..": "..L["Artisan"] },
            { ID = "AlchemyArtisan2", Title = BS["Alchemy"]..": "..L["Artisan"] },
            { ID = "AlchemyFlasks1", Title = L["Flasks"] },
            { ID = "AlchemyProtectionPots1", Title = L["Protection Potions"] },
            { ID = "AlchemyHealingAndMana1", Title = L["Healing and Mana Potions"] },
            { ID = "AlchemyTransmutes1", Title = L["Transmutes"] },
            { ID = "AlchemyDefensive1", Title = L["Defensive Potions and Elixirs"] },
            { ID = "AlchemyOffensive1", Title = L["Offensive Potions and Elixirs"] },
            { ID = "AlchemyOther1", Title = L["Other"] },
        }
    },
    ["Blacksmithing"] = {
        Name = BS["Blacksmithing"],
        Entry = {
            { ID = "SmithingApprentice1", Title = BS["Blacksmithing"]..": "..L["Apprentice"] },
            { ID = "SmithingJourneyman1", Title = BS["Blacksmithing"]..": "..L["Journeyman"] },
            { ID = "SmithingJourneyman2", Title = BS["Blacksmithing"]..": "..L["Journeyman"] },
            { ID = "SmithingExpert1", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingExpert2", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingExpert3", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingArtisan1", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan2", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan3", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan4", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingHelm1", Title = BS["Blacksmithing"]..": "..L["Helm"] },
            { ID = "SmithingShoulders1", Title = BS["Blacksmithing"]..": "..L["Shoulders"] },
            { ID = "SmithingChest1", Title = BS["Blacksmithing"]..": "..L["Chest"] },
            { ID = "SmithingChest2", Title = BS["Blacksmithing"]..": "..L["Chest"] },
            { ID = "SmithingBracers1", Title = BS["Blacksmithing"]..": "..L["Bracers"] },
            { ID = "SmithingGloves1", Title = BS["Blacksmithing"]..": "..L["Gloves"] },
            { ID = "SmithingBelt1", Title = BS["Blacksmithing"]..": "..L["Belt"] },
            { ID = "SmithingPants1", Title = BS["Blacksmithing"]..": "..L["Pants"] },
            { ID = "SmithingBoots1", Title = BS["Blacksmithing"]..": "..L["Boots"] },
            { ID = "SmithingBuckles1", Title = BS["Blacksmithing"]..": "..L["Belt Buckles"] },
            { ID = "SmithingAxes1", Title = BS["Blacksmithing"]..": "..L["Axes"] },
            { ID = "SmithingSwords1", Title = BS["Blacksmithing"]..": "..L["Swords"] },
            { ID = "SmithingMaces1", Title = BS["Blacksmithing"]..": "..L["Maces"] },
            { ID = "SmithingFist1", Title = BS["Blacksmithing"]..": "..L["Fist"] },
            { ID = "SmithingDaggers1", Title = BS["Blacksmithing"]..": "..L["Daggers"] },
            { ID = "SmithingMisc1", Title = BS["Blacksmithing"]..": "..L["Misc"] },
            { ID = "SmithingMisc2", Title = BS["Blacksmithing"]..": "..L["Misc"] },
            { ID = "Armorsmith1", Title = BS["Armorsmith"] },
            { ID = "Weaponsmith1", Title = BS["Weaponsmith"] },
            { ID = "Axesmith1", Title = L["Master Axesmith"] },
            { ID = "Hammersmith1", Title = L["Master Hammersmith"] },
            { ID = "Swordsmith1", Title = L["Master Swordsmith"] },
        }
    },
    ["Enchanting"] = {
        Name = BS["Enchanting"],
        Entry = {
            { ID = "EnchantingApprentice1", Title = BS["Enchanting"]..": "..L["Apprentice"] },
            { ID = "EnchantingJourneyman1", Title = BS["Enchanting"]..": "..L["Journeyman"] },
            { ID = "EnchantingJourneyman2", Title = BS["Enchanting"]..": "..L["Journeyman"] },
            { ID = "EnchantingExpert1", Title = BS["Enchanting"]..": "..L["Expert"] },
            { ID = "EnchantingExpert2", Title = BS["Enchanting"]..": "..L["Expert"] },
            { ID = "EnchantingArtisan1", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingArtisan2", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingArtisan3", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingCloak1", Title = BS["Enchanting"]..": "..L["Cloak"] },
            { ID = "EnchantingChest1", Title = BS["Enchanting"]..": "..L["Chest"] },
            { ID = "EnchantingBracer1", Title = BS["Enchanting"]..": "..L["Bracers"] },
            { ID = "EnchantingGlove1", Title = BS["Enchanting"]..": "..L["Gloves"] },
            { ID = "EnchantingBoots1", Title = BS["Enchanting"]..": "..L["Boots"] },
            { ID = "Enchanting2HWeapon1", Title = BS["Enchanting"]..": "..L["2H Weapon"] },
            { ID = "EnchantingWeapon1", Title = BS["Enchanting"]..": "..L["Weapon"] },
            { ID = "EnchantingShield1", Title = BS["Enchanting"]..": "..L["Shield"] },
            { ID = "EnchantingMisc1", Title = BS["Enchanting"]..": "..L["Misc"] },
        }
    },
    ["Engineering"] = {
        Name = BS["Engineering"],
        Entry = {
            { ID = "EngineeringApprentice1", Title = BS["Engineering"]..": "..L["Apprentice"] },
            { ID = "EngineeringJourneyman1", Title = BS["Engineering"]..": "..L["Journeyman"] },
            { ID = "EngineeringJourneyman2", Title = BS["Engineering"]..": "..L["Journeyman"] },
            { ID = "EngineeringExpert1", Title = BS["Engineering"]..": "..L["Expert"] },
            { ID = "EngineeringExpert2", Title = BS["Engineering"]..": "..L["Expert"] },
            { ID = "EngineeringArtisan1", Title = BS["Engineering"]..": "..L["Artisan"] },
            { ID = "EngineeringArtisan2", Title = BS["Engineering"]..": "..L["Artisan"] },
            { ID = "EngineeringEquipment1", Title = BS["Engineering"]..": "..L["Equipment"] },
            { ID = "EngineeringTrinkets1", Title = BS["Engineering"]..": "..L["Trinkets"] },
            { ID = "EngineeringExplosives1", Title = BS["Engineering"]..": "..L["Explosives"] },
            { ID = "EngineeringWeapons1", Title = BS["Engineering"]..": "..L["Weapons"] },
            { ID = "EngineeringParts1", Title = BS["Engineering"]..": "..L["Parts"] },
            { ID = "EngineeringMisc1", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "EngineeringMisc2", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "EngineeringMisc3", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "Gnomish1", Title = L["Gnomish Engineering"] },
            { ID = "Goblin1", Title = L["Goblin Engineering"] },
        }
    },
    ["Leatherworking"] = {
        Name = BS["Leatherworking"],
        Entry = {
            { ID = "LeatherApprentice1", Title = BS["Leatherworking"]..": "..L["Apprentice"] },
            { ID = "LeatherJourneyman1", Title = BS["Leatherworking"]..": "..L["Journeyman"] },
            { ID = "LeatherJourneyman2", Title = BS["Leatherworking"]..": "..L["Journeyman"] },
            { ID = "LeatherExpert1", Title = BS["Leatherworking"]..": "..L["Expert"] },
            { ID = "LeatherExpert2", Title = BS["Leatherworking"]..": "..L["Expert"] },
            { ID = "LeatherArtisan1", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherArtisan2", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherArtisan3", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherHelm1", Title = BS["Leatherworking"]..": "..L["Helm"] },
            { ID = "LeatherShoulders1", Title = BS["Leatherworking"]..": "..L["Shoulders"] },
            { ID = "LeatherCloak1", Title = BS["Leatherworking"]..": "..L["Cloak"] },
            { ID = "LeatherChest1", Title = BS["Leatherworking"]..": "..L["Chest"] },
            { ID = "LeatherChest2", Title = BS["Leatherworking"]..": "..L["Chest"] },
            { ID = "LeatherBracers1", Title = BS["Leatherworking"]..": "..L["Bracers"] },
            { ID = "LeatherGloves1", Title = BS["Leatherworking"]..": "..L["Gloves"] },
            { ID = "LeatherGloves2", Title = BS["Leatherworking"]..": "..L["Gloves"] },
            { ID = "LeatherBelt1", Title = BS["Leatherworking"]..": "..L["Belt"] },
            { ID = "LeatherPants1", Title = BS["Leatherworking"]..": "..L["Pants"] },
            { ID = "LeatherPants2", Title = BS["Leatherworking"]..": "..L["Pants"] },
            { ID = "LeatherBoots1", Title = BS["Leatherworking"]..": "..L["Boots"] },
            { ID = "LeatherBags1", Title = BS["Leatherworking"]..": "..L["Bags"] },
            { ID = "LeatherMisc1", Title = BS["Leatherworking"]..": "..L["Misc"] },
            { ID = "Dragonscale1", Title = BS["Dragonscale Leatherworking"] },
            { ID = "Elemental1", Title = BS["Elemental Leatherworking"] },
            { ID = "Tribal1", Title = BS["Tribal Leatherworking"] },
        }
    },
    ["Mining"] = {
        Name = BS["Mining"],
        Entry = {
            { ID = "Mining1", Title = BS["Mining"] },
            { ID = "Mining2", Title = BS["Mining"] },
            { ID = "Smelting1", Title = BS["Smelting"] },
        }
    },
    ["Tailoring"] = {
        Name = BS["Tailoring"],
        Entry = {
            { ID = "TailoringApprentice1", Title = BS["Tailoring"]..": "..L["Apprentice"] },
            { ID = "TailoringApprentice2", Title = BS["Tailoring"]..": "..L["Apprentice"] },
            { ID = "TailoringJourneyman1", Title = BS["Tailoring"]..": "..L["Journeyman"] },
            { ID = "TailoringJourneyman2", Title = BS["Tailoring"]..": "..L["Journeyman"] },
            { ID = "TailoringExpert1", Title = BS["Tailoring"]..": "..L["Expert"] },
            { ID = "TailoringExpert2", Title = BS["Tailoring"]..": "..L["Expert"] },
            { ID = "TailoringArtisan1", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan2", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan3", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan4", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan5", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringHelm1", Title = BS["Tailoring"]..": "..L["Helm"] },
            { ID = "TailoringShoulders1", Title = BS["Tailoring"]..": "..L["Shoulders"] },
            { ID = "TailoringCloak1", Title = BS["Tailoring"]..": "..L["Cloak"] },
            { ID = "TailoringChest1", Title = BS["Tailoring"]..": "..L["Chest"] },
            { ID = "TailoringChest2", Title = BS["Tailoring"]..": "..L["Chest"] },
            { ID = "TailoringBracers1", Title = BS["Tailoring"]..": "..L["Bracers"] },
            { ID = "TailoringGloves1", Title = BS["Tailoring"]..": "..L["Gloves"] },
            { ID = "TailoringBelt1", Title = BS["Tailoring"]..": "..L["Belt"] },
            { ID = "TailoringPants1", Title = BS["Tailoring"]..": "..L["Pants"] },
            { ID = "TailoringBoots1", Title = BS["Tailoring"]..": "..L["Boots"] },
            { ID = "TailoringShirt1", Title = BS["Tailoring"]..": "..L["Shirt"] },
            { ID = "TailoringBags1", Title = BS["Tailoring"]..": "..L["Bags"] },
            { ID = "TailoringMisc1", Title = BS["Tailoring"]..": "..L["Misc"] },
        }
    },
    ["Jewelcrafting"] = {
        Name = BS["Jewelcrafting"],
        Entry = {
            { ID = "JewelcraftingApprentice1", Title = BS["Jewelcrafting"]..": "..L["Apprentice"] },
            { ID = "JewelcraftingJourneyman1", Title = BS["Jewelcrafting"]..": "..L["Journeyman"] },
            { ID = "JewelcraftingJourneyman2", Title = BS["Jewelcrafting"]..": "..L["Journeyman"] },
            { ID = "JewelcraftingExpert1", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingExpert2", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingExpert3", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingArtisan1", Title = BS["Jewelcrafting"]..": "..L["Artisan"] },
            { ID = "JewelcraftingArtisan2", Title = BS["Jewelcrafting"]..": "..L["Artisan"] },
            { ID = "JewelcraftingGemstones1", Title = BS["Jewelcrafting"]..": "..L["Gemstones"] },
            { ID = "JewelcraftingRings1", Title = BS["Jewelcrafting"]..": "..L["Rings"] },
            { ID = "JewelcraftingRings2", Title = BS["Jewelcrafting"]..": "..L["Rings"] },
            { ID = "JewelcraftingAmulets1", Title = BS["Jewelcrafting"]..": "..L["Amulets"] },
            { ID = "JewelcraftingHelm1", Title = BS["Jewelcrafting"]..": "..L["Head"] },
            { ID = "JewelcraftingBracers1", Title = BS["Jewelcrafting"]..": "..L["Bracers"] },
            { ID = "JewelcraftingOffHands1", Title = BS["Jewelcrafting"]..": "..L["Off-hand"] },
            { ID = "JewelcraftingStaves1", Title = BS["Jewelcrafting"]..": "..L["Staff"] },
            { ID = "JewelcraftingTrinkets1", Title = BS["Jewelcrafting"]..": "..L["Trinkets"] },
            { ID = "JewelcraftingMisc1", Title = BS["Jewelcrafting"]..": "..L["Misc"] },
            { ID = "JewelcraftingGemology1", Title = BS["Jewelcrafting"]..": "..BS["Gemology"] },
            { ID = "JewelcraftingGoldsmithing1", Title = BS["Jewelcrafting"]..": "..BS["Goldsmithing"] },
        }
    },
    ["Cooking"] = {
        Name = BS["Cooking"],
        Entry = {
            { ID = "CookingApprentice1", Title = BS["Cooking"]..": "..L["Apprentice"] },
            { ID = "CookingJourneyman1", Title = BS["Cooking"]..": "..L["Journeyman"] },
            { ID = "CookingExpert1", Title = BS["Cooking"]..": "..L["Expert"] },
            { ID = "CookingArtisan1", Title = BS["Cooking"]..": "..L["Artisan"] },
        }
    },
    ["Survival"] = {
        Name = BS["Survival"],
        Entry = {
            { ID = "Survival1", Title = BS["Survival"] },
            { ID = "Survival2", Title = BS["Garderning"] },
        }
    },
    ["CraftSet"] = {
        Name = L["Crafted Sets"],
        Entry = {
            { ID = "AugerersAttire", Title = BIS["Augerer's Attire"] },
            { ID = "ShadoweaveSet", Title = BIS["Shadoweave"] },
            { ID = "DivinersGarments", Title = BIS["Diviner's Garments"] },
            { ID = "PillagersGarb", Title = BIS["Pillager's Garb"] },
            { ID = "MoonclothRegalia", Title = BIS["Mooncloth Regalia"] },
            { ID = "BloodvineG", Title = BIS["Bloodvine Garb"] },
            { ID = "FlarecoreRegalia", Title = BIS["Flarecore Regalia"] },
            { ID = "DreamthreadRegalia", Title = BIS["Dreamthread Regalia"] },
            { ID = "GriftersArmor", Title = BIS["Grifter's Armor"] },
            { ID = "PrimalistsTrappings", Title = BIS["Primalist's Trappings"] },
            { ID = "VolcanicArmor", Title = BIS["Volcanic Armor"] },
            { ID = "IronfeatherArmor", Title = BIS["Ironfeather Armor"] },
            { ID = "StormshroudArmor", Title = BIS["Stormshroud Armor"] },
            { ID = "DevilsaurArmor", Title = BIS["Devilsaur Armor"] },
            { ID = "BloodTigerH", Title = BIS["Blood Tiger Harness"] },
            { ID = "PrimalBatskin", Title = BIS["Primal Batskin"] },
            { ID = "ConvergenceoftheElements", Title = BIS["Convergence of the Elements"] },
            { ID = "DreamhideBattlegarb", Title = BIS["Dreamhide Battlegarb"] },
        }
    },
    ["CraftSet2"] = {
        Name = L["Crafted Sets"].." II",
        Entry = {
            { ID = "RedDragonM", Title = BIS["Red Dragon Mail"] },
            { ID = "GreenDragonM", Title = BIS["Green Dragon Mail"] },
            { ID = "BlueDragonM", Title = BIS["Blue Dragon Mail"] },
            { ID = "BlackDragonM", Title = BIS["Black Dragon Mail"] },
            { ID = "BloodsoulEmbrace", Title = BIS["Bloodsoul Embrace"] },
            { ID = "HateforgeArmor", Title = BIS["Hateforge Armor"] },
            { ID = "TowerforgeBattlegear", Title = BIS["Towerforge Battlegear"] },
            { ID = "SteelPlate", Title = BIS["Steel Plate"] },
            { ID = "ImperialPlate", Title = BIS["Imperial Plate"] },
            { ID = "RuneEtchedArmor", Title = BIS["Rune-Etched Armor"] },
            { ID = "TheDarksoul", Title = BIS["The Darksoul"] },
            { ID = "DreamsteelArmor", Title = BIS["Dreamsteel Armor"] },
        }
    },
    ["BlackfathomDeeps"] = {
        Name = BZ["Blackfathom Deeps"],
        Entry = {
            { ID = "BFDGhamoora", Title = BB["Ghamoo-ra"] },
            { ID = "BFDLadySarevess", Title = BB["Lady Sarevess"] },
            { ID = "BFDGelihast", Title = BB["Gelihast"] },
            { ID = "BFDBaronAquanis", Title = BB["Baron Aquanis"] },
            { ID = "BFDTwilightLordKelris", Title = BB["Twilight Lord Kelris"] },
            { ID = "BFDOldSerrakis", Title = BB["Old Serra'kis"] },
            { ID = "BFDAkumai", Title = BB["Aku'mai"] },
            { ID = "BFDTrash", Title = L["Trash Mobs"] },
        }
    },
    ["TheDeadmines"] = {
        Name = BZ["The Deadmines"],
        Entry = {
            { ID = "DMJaredVoss", Title = BB["Jared Voss"] },
            { ID = "DMRhahkZor", Title = BB["Rhahk'Zor"] },
            { ID = "DMMinerJohnson", Title = BB["Miner Johnson"].." ("..L["Rare"]..")" },
            { ID = "DMSneed", Title = BB["Sneed"] },
            { ID = "DMSneedsShredder", Title = L["Sneed's Shredder"] },
            { ID = "DMGilnid", Title = BB["Gilnid"] },
            { ID = "DMHarvester", Title = BB["Masterpiece Harvester"] },
            { ID = "DMMrSmite", Title = BB["Mr. Smite"] },
            { ID = "DMCookie", Title = BB["Cookie"] },
            { ID = "DMCaptainGreenskin", Title = BB["Captain Greenskin"] },
            { ID = "DMVanCleef", Title = BB["Edwin VanCleef"] },
            { ID = "DMTrash", Title = L["Trash Mobs"] },
        }
    },
    ["RagefireChasm"] = {
        Name = BZ["Ragefire Chasm"],
        Entry = {
            { ID = "RFCOggleflint", Title = BB["Oggleflint"] },
            { ID = "RFCTaragaman", Title = BB["Taragaman the Hungerer"] },
            { ID = "RFCJergosh", Title = BB["Jergosh the Invoker"] },
            { ID = "RFCBazzalan", Title = BB["Bazzalan"] },
            { ID = "RFCTrash", Title = L["Trash Mobs"] },
        },
    },
    ["ShadowfangKeep"] = {
        Name = BZ["Shadowfang Keep"],
        Entry = {
            { ID = "SFKRethilgore", Title = BB["Rethilgore"] },
            { ID = "SFKFelSteed", Title = L["Fel Steed"] },
            { ID = "SFKRazorclawtheButcher", Title = BB["Razorclaw the Butcher"] },
            { ID = "SFKSilverlaine", Title = BB["Baron Silverlaine"] },
            { ID = "SFKSpringvale", Title = BB["Commander Springvale"] },
            { ID = "SFKSever", Title = BB["Sever"].." (".."Scourge Invasion"..")" },
            { ID = "SFKOdotheBlindwatcher", Title = BB["Odo the Blindwatcher"] },
            { ID = "SFKDeathswornCaptain", Title = BB["Deathsworn Captain"].." ("..L["Rare"]..")" },
            { ID = "SFKFenrustheDevourer", Title = BB["Fenrus the Devourer"] },
            { ID = "SFKArugalsVoidwalker", Title = BB["Archmage Arugal's Voidwalker"] },
            { ID = "SFKBookofUr", Title = L["The Book of Ur"] },
            { ID = "SFKWolfMasterNandos", Title = BB["Wolf Master Nandos"] },
            { ID = "SFKArchmageArugal", Title = BB["Archmage Arugal"] },
            { ID = "SFKPrelate", Title = BB["Prelate Ironmane"] },
            { ID = "SFKTrash", Title = L["Trash Mobs"] },
        }
    },
    ["TheStockade"] = {
        Name = BZ["The Stockade"],
        Entry = {
            { ID = "SWStTargorr", Title = BB["Targorr the Dread"] },
            { ID = "SWStKamDeepfury", Title = BB["Kam Deepfury"] },
            { ID = "SWStHamhock", Title = BB["Hamhock"] },
            { ID = "SWStBazil", Title = BB["Bazil Thredd"] },
            { ID = "SWStDextren", Title = BB["Dextren Ward"] },
            { ID = "SWStBruegalIronknuckle", Title = BB["Bruegal Ironknuckle"].." ("..L["Rare"]..")" },
            { ID = "SWStTrash", Title = L["Trash Mobs"] },
        }
    },
    ["WailingCaverns"] = {
        Name = BZ["Wailing Caverns"],
        Entry = {
            { ID = "WCLordCobrahn", Title = BB["Lord Cobrahn"] },
            { ID = "WCLadyAnacondra", Title = BB["Lady Anacondra"] },
            { ID = "WCKresh", Title = BB["Kresh"] },
            { ID = "WCZandara", Title = BB["Zandara Windhoof"] },
            { ID = "WCLordPythas", Title = BB["Lord Pythas"] },
            { ID = "WCSkum", Title = BB["Skum"] },
            { ID = "WCVangros", Title = BB["Vangros"] },
            { ID = "WCLordSerpentis", Title = BB["Lord Serpentis"] },
            { ID = "WCVerdan", Title = BB["Verdan the Everliving"] },
            { ID = "WCMutanus", Title = BB["Mutanus the Devourer"] },
            { ID = "WCDeviateFaerieDragon", Title = BB["Deviate Faerie Dragon"].." ("..L["Rare"]..")" },
            { ID = "WCTrash", Title = L["Trash Mobs"] },
        }
    },
	["TheCrescentGrove"] = {
		Name = BZ["The Crescent Grove"],
		Entry = {
			{ ID = "TCGGrovetenderEngryss", Title = BB["Grovetender Engryss"] },
			{ ID = "TCGKeeperRanathos", Title = BB["Keeper Ranathos"] },
			{ ID = "TCGHighPriestessAlathea", Title = BB["High Priestess A'lathea"] },
			{ ID = "TCGFenektistheDeceiver", Title = BB["Fenektis the Deceiver"] },
			{ ID = "TCGMasterRaxxieth", Title = BB["Master Raxxieth"] },
			{ ID = "TCGTrash", Title = L["Trash Mobs"] },
		},
	},
    ["Gnomeregan"] = {
        Name = BZ["Gnomeregan"],
        Entry = {
            { ID = "GnGrubbis", Title = BB["Grubbis"] },
            { ID = "GnViscousFallout", Title = BB["Viscous Fallout"] },
            { ID = "GnElectrocutioner6000", Title = BB["Electrocutioner 6000"] },
            { ID = "GnCrowdPummeler960", Title = BB["Crowd Pummeler 9-60"] },
            { ID = "GnDIAmbassador", Title = BB["Dark Iron Ambassador"] },
            { ID = "GnMekgineerThermaplugg", Title = BB["Mekgineer Thermaplugg"] },
            { ID = "GnTrash", Title = L["Trash Mobs"] },
        }
    },
    ["RazorfenKraul"] = {
        Name = BZ["Razorfen Kraul"],
        Entry = {
            { ID = "RFKAggem", Title = BB["Aggem Thorncurse"] },
            { ID = "RFKDeathSpeakerJargba", Title = BB["Death Speaker Jargba"] },
            { ID = "RFKOverlordRamtusk", Title = BB["Overlord Ramtusk"] },
            { ID = "RFKRazorfenSpearhide", Title = L["Razorfen Spearhide"].." ("..L["Rare"]..")" },
            { ID = "RFKAgathelos", Title = BB["Agathelos the Raging"] },
            { ID = "RFKBlindHunter", Title = BB["Blind Hunter"].." ("..L["Rare"]..")" },
            { ID = "RFKCharlgaRazorflank", Title = BB["Charlga Razorflank"] },
            { ID = "RFKEarthcallerHalmgar", Title = BB["Earthcaller Halmgar"].." ("..L["Rare"]..")" },
            { ID = "RFKTrash", Title = L["Trash Mobs"] },
        }
    },
    ["ScarletMonasteryGraveyard"] = {
        Name = BZ["Scarlet Monastery (Graveyard)"],
        Entry = {
            { ID = "SMVishas", Title = BB["Interrogator Vishas"] },
            { ID = "SMScorn", Title = BB["Scorn"].." (".."Scourge Invasion"..")" },
            { ID = "SMBloodmageThalnos", Title = BB["Bloodmage Thalnos"] },
            { ID = "SMIronspine", Title = BB["Ironspine"].." ("..L["Rare"]..")" },
            { ID = "SMAzshir", Title = BB["Azshir the Sleepless"].." ("..L["Rare"]..")" },
            { ID = "SMFallenChampion", Title = BB["Fallen Champion"].." ("..L["Rare"]..")" },
            { ID = "SMDukeDreadmoore", Title = BB["Duke Dreadmoore"] },
            { ID = "SMGTrash", Title = L["Trash Mobs"] },
        },
    },
    ["ScarletMonasteryLibrary"] = {
        Name = BZ["Scarlet Monastery (Library)"],
        Entry = {
            { ID = "SMHoundmasterLoksey", Title = BB["Houndmaster Loksey"] },
            { ID = "SMDoan", Title = BB["Arcanist Doan"] },
            { ID = "SMBrotherWystan", Title = BB["Brother Wystan"] },
            { ID = "SMLTrash", Title = L["Trash Mobs"] },
        },
    },
    ["ScarletMonasteryArmory"] = {
        Name = BZ["Scarlet Monastery (Armory)"],
        Entry = {
            { ID = "SMHerod", Title = BB["Herod"] },
            { ID = "SMQuartermasterDaghelm", Title = BB["Armory Quartermaster Daghelm"] },
            { ID = "SMATrash", Title = L["Trash Mobs"] },
        },
    },
    ["StormwroughtRuins"] = {
        Name = BZ["Stormwrought Ruins"],
        Entry = {
        --	{ ID = "SWRTrash", Title = L["Trash Mobs"] }, -- TODO when realese patch
        },
    },
    ["GilneasCity"] = {
        Name = BZ["Gilneas City"],
        Entry = {
            { ID = "GCMatthiasHoltz", Title = BB["Matthias Holtz"] },
            { ID = "GCPackmasterRagetooth", Title = BB["Packmaster Ragetooth"] },
            { ID = "GCJudgeSutherland", Title = BB["Judge Sutherland"] },
            { ID = "GCDustivanBlackcowl", Title = BB["Dustivan Blackcowl"] },
            { ID = "GCMarshalMagnusGreystone", Title = BB["Marshal Magnus Greystone"] },
            { ID = "GCHorsemasterLevvin", Title = BB["Horsemaster Levvin"] },
            { ID = "GCHarlowFamilyChest", Title = L["Harlow Family Chest"] },
            { ID = "GCGennGreymane", Title = BB["Genn Greymane"] },
            { ID = "GCTrash", Title = L["Trash Mobs"] },
        },
    },
    ["RazorfenDowns"] = {
        Name = BZ["Razorfen Downs"],
        Entry = {
            { ID = "RFDTutenkash", Title = BB["Tuten'kash"] },
            { ID = "RFDHenryStern", Title = L["Henry Stern"] },
            { ID = "RFDLadyF", Title = BB["Lady Falther'ess"].." ("..L["Scourge Invasion"]..")" },
            { ID = "RFDMordreshFireEye", Title = BB["Mordresh Fire Eye"] },
            { ID = "RFDGlutton", Title = BB["Glutton"] },
            { ID = "RFDRagglesnout", Title = BB["Ragglesnout"].." ("..L["Rare"]..")" },
            { ID = "RFDAmnennar", Title = BB["Amnennar the Coldbringer"] },
            { ID = "RFDPlaguemaw", Title = BB["Plaguemaw the Rotting"] },
            { ID = "RFDTrash", Title = L["Trash Mobs"] },
        }
    },
    ["ScarletMonasteryCathedral"] = {
        Name = BZ["Scarlet Monastery (Cathedral)"],
        Entry = {
            { ID = "SMFairbanks", Title = BB["High Inquisitor Fairbanks"] },
            { ID = "SMMograine", Title = BB["Scarlet Commander Mograine"] },
            { ID = "SMWhitemane", Title = BB["High Inquisitor Whitemane"] },
            { ID = "SMCTrash", Title = L["Trash Mobs"] },
        },
    },
    ["SunkenTemple"] = {
        Name = BZ["The Temple of Atal'Hakkar"],
        Entry = {
            { ID = "STBalconyMinibosses", Title = L["Balcony Minibosses"] },
            { ID = "STAtalalarion", Title = BB["Atal'alarion"] },
            { ID = "STSpawnOfHakkar", Title = L["Spawn of Hakkar"] },
            { ID = "STAvatarofHakkar", Title = BB["Avatar of Hakkar"] },
            { ID = "STJammalan", Title = BB["Jammal'an the Prophet"] },
            { ID = "STOgom", Title = BB["Ogom the Wretched"] },
            { ID = "STDreamscythe", Title = BB["Dreamscythe"] },
            { ID = "STWeaver", Title = BB["Weaver"] },
            { ID = "STMorphaz", Title = BB["Morphaz"] },
            { ID = "STHazzas", Title = BB["Hazzas"] },
            { ID = "STEranikus", Title = BB["Shade of Eranikus"] },
            { ID = "STTrash", Title = L["Trash Mobs"] },
        }
    },
    ["Uldaman"] = {
        Name = BZ["Uldaman"],
        Entry = {
            { ID = "UldBaelog", Title = BB["Baelog"] },
            { ID = "UldEric", Title = BB["Eric \"The Swift\""] },
            { ID = "UldOlaf", Title = BB["Olaf"] },
            { ID = "UldRevelosh", Title = BB["Revelosh"] },
            { ID = "UldIronaya", Title = BB["Ironaya"] },
            { ID = "UldObsidian", Title = BB["Obsidian Sentinel"] },
            { ID = "UldAncients", Title = BB["Ancient Stone Keeper"] },
            { ID = "UldGalgannFirehammer", Title = BB["Galgann Firehammer"] },
            { ID = "UldGrimlok", Title = BB["Grimlok"] },
            { ID = "UldArchaedas", Title = BB["Archaedas"] },
            { ID = "UldTrash", Title = L["Trash Mobs"] },
        }
    },
    ["ZulFarrak"] = {
        Name = BZ["Zul'Farrak"],
        Entry = {
            { ID = "ZFAntusul", Title = BB["Antu'sul"] },
            { ID = "ZFWitchDoctorZumrah", Title = BB["Witch Doctor Zum'rah"] },
            { ID = "ZFShadowpriestSezziz", Title = BB["Shadowpriest Sezz'ziz"] },
            { ID = "ZFDustwraith", Title = L["Dustwraith"].." ("..L["Rare"]..")" },
            { ID = "ZFGahzrilla", Title = BB["Gahz'rilla"] },
            { ID = "ZFChiefUkorzSandscalp", Title = BB["Chief Ukorz Sandscalp"] },
            { ID = "ZFZerillis", Title = L["Zerillis"].." ("..L["Rare"]..")" },
            { ID = "ZFTrash", Title = L["Trash Mobs"] },
        },
    },
    ["BlackrockDepths"] = {
        Name = BZ["Blackrock Depths"],
        Entry = {
            { ID = "BRDLordRoccor", Title = BB["Lord Roccor"] },
            { ID = "BRDHighInterrogatorGerstahn", Title = BB["High Interrogator Gerstahn"] },
            { ID = "BRDAnubshiah", Title = BB["Anub'shiah"] },
            { ID = "BRDEviscerator", Title = BB["Eviscerator"] },
            { ID = "BRDGorosh", Title = BB["Gorosh the Dervish"] },
            { ID = "BRDGrizzle", Title = BB["Grizzle"] },
            { ID = "BRDHedrum", Title = BB["Hedrum the Creeper"] },
            { ID = "BRDOkthor", Title = BB["Ok'thor the Breaker"] },
            { ID = "BRDTheldren", Title = L["Theldren"] },
            { ID = "BRDHoundmaster", Title = BB["Houndmaster Grebmar"] },
            { ID = "BRDPyromancerLoregrain", Title = BB["Pyromancer Loregrain"].." ("..L["Rare"]..")" },
            { ID = "BRDTheVault", Title = L["The Vault"] },
            { ID = "BRDWarderStilgiss", Title = BB["Warder Stilgiss"].." ("..L["Rare"]..")" },
            { ID = "BRDVerek", Title = BB["Verek"].." ("..L["Rare"]..")" },
            { ID = "BRDFineousDarkvire", Title = BB["Fineous Darkvire"] },
            { ID = "BRDLordIncendius", Title = BB["Lord Incendius"] },
            { ID = "BRDBaelGar", Title = BB["Bael'Gar"] },
            { ID = "BRDGeneralAngerforge", Title = BB["General Angerforge"] },
            { ID = "BRDGolemLordArgelmach", Title = BB["Golem Lord Argelmach"] },
            { ID = "BRDGuzzler", Title = L["The Grim Guzzler"] },
            { ID = "BRDFlamelash", Title = BB["Ambassador Flamelash"] },
            { ID = "BRDPanzor", Title = BB["Panzor the Invincible"].." ("..L["Rare"]..")" },
            { ID = "BRDTomb", Title = L["Summoner's Tomb"] },
            { ID = "BRDMagmus", Title = BB["Magmus"] },
            { ID = "BRDPrincess", Title = BB["Princess Moira Bronzebeard"] },
            { ID = "BRDEmperorDagranThaurissan", Title = BB["Emperor Dagran Thaurissan"] },
            { ID = "BRDTrash", Title = L["Trash Mobs"] },
        }
    },
    ["CavernsOfTimeBlackMorass"] = {
        Name = BZ["Caverns of Time: Black Morass"],
        Entry = {
            { ID = "COTBMChronar", Title = BB["Chronar"] },
            { ID = "COTBMEpidamu", Title = BB["Epidamu"] },
            { ID = "COTBMDriftingAvatar", Title = L["Drifting Avatar of Time"] },
            { ID = "COTBMTimeLordEpochronos", Title = BB["Time-Lord Epochronos"] },
            { ID = "COTBMMossheart", Title = BB["Mossheart"] },
            { ID = "COTBMRotmaw", Title = BB["Rotmaw"] },
            { ID = "COTBMAntnormi", Title = BB["Antnormi"] },
            { ID = "COTTrash", Title = L["Trash Mobs"] },
        }
    },
    ["DireMaulEast"] = {
        Name = BZ["Dire Maul (East)"],
        Entry = {
            { ID = "DMEPusillin", Title = BB["Pusillin"] },
            { ID = "DMEZevrimThornhoof", Title = BB["Zevrim Thornhoof"] },
            { ID = "DMEHydro", Title = BB["Hydrospawn"] },
            { ID = "DMELethtendris", Title = BB["Lethtendris"] },
            { ID = "DMEPimgib", Title = BB["Pimgib"] },
            { ID = "DMEAlzzin", Title = BB["Alzzin the Wildshaper"] },
            { ID = "DMEIsalien", Title = BB["Isalien"] },
            { ID = "DMEShard", Title = L["Felvine Shard"] },
            { ID = "DMETrash", Title = L["Trash Mobs"] },
        }
    },
    ["DireMaulNorth"] = {
        Name = BZ["Dire Maul (North)"],
        Entry = {
            { ID = "DMNGuardMoldar", Title = BB["Guard Mol'dar"] },
            { ID = "DMNStomperKreeg", Title = BB["Stomper Kreeg"] },
            { ID = "DMNGuardFengus", Title = BB["Guard Fengus"] },
            { ID = "DMNThimblejack", Title = L["Knot Thimblejack"] },
            { ID = "DMNGuardSlipkik", Title = BB["Guard Slip'kik"] },
            { ID = "DMNCaptainKromcrush", Title = BB["Captain Kromcrush"] },
            { ID = "DMNKingGordok", Title = BB["King Gordok"] },
            { ID = "DMNChoRush", Title = BB["Cho'Rush the Observer"] },
            { ID = "DMNTRIBUTERUN", Title = L["Tribute Run"] },
            { ID = "DMNTrash", Title = L["Trash Mobs"] },
        }
    },
    ["DireMaulWest"] = {
        Name = BZ["Dire Maul (West)"],
        Entry = {
            { ID = "DMWTendrisWarpwood", Title = BB["Tendris Warpwood"] },
            { ID = "DMWIllyannaRavenoak", Title = BB["Illyanna Ravenoak"] },
            { ID = "DMWMagisterKalendris", Title = BB["Magister Kalendris"] },
            { ID = "DMWTsuzee", Title = BB["Tsu'zee"].." ("..L["Rare"]..")" },
            { ID = "DMWImmolthar", Title = BB["Immol'thar"] },
            { ID = "DMWHelnurath", Title = BB["Lord Hel'nurath"].." ("..L["Rare"]..")" },
            { ID = "DMWPrinceTortheldrin", Title = BB["Prince Tortheldrin"] },
            { ID = "DMWRevanchion", Title = BB["Revanchion"].." (".."Scourge Invasion"..")" },
            { ID = "DMWTrash", Title = L["Trash Mobs"] },
        }
    },
    ["HateforgeQuarry"] = {
        Name = BZ["Hateforge Quarry"],
        Entry = {
            { ID = "HQHighForemanBargulBlackhammer", Title = BB["High Foreman Bargul Blackhammer"] },
            { ID = "HQEngineerFiggles", Title = BB["Engineer Figgles"] },
            { ID = "HQCorrosis", Title = BB["Corrosis"] },
            { ID = "HQHatereaverAnnihilator", Title = BB["Hatereaver Annihilator"] },
            { ID = "HQHargeshDoomcaller", Title = BB["Har'gesh Doomcaller"] },
            { ID = "HQTrash", Title = L["Trash Mobs"] },
        }
    },
    ["KarazhanCrypt"] = {
        Name = BZ["Karazhan Crypt"],
        Entry = {
            { ID = "KCMarrowspike", Title = BB["Marrowspike"] },
            { ID = "KCHivaxxis", Title = BB["Hivaxxis"] },
            { ID = "KCCorpsemuncher", Title = BB["Corpsemuncher"] },
            { ID = "KCGuardCaptainGort", Title = BB["Guard Captain Gort"] },
            { ID = "KCArchlichEnkhraz", Title = BB["Archlich Enkhraz"] },
            { ID = "KCCommanderAndreon", Title = BB["Commander Andreon"] },
            { ID = "KCAlarus", Title = BB["Alarus"] },
            { ID = "KCTreasure", Title = L["Half-Buried Treasure Chest"] },
            { ID = "KCTrash", Title = L["Trash Mobs"] },
        }
    },
    ["LowerBlackrockSpire"] = {
        Name = BZ["Lower Blackrock Spire"],
        Entry = {
            { ID = "LBRSSpirestoneButcher", Title = L["Spirestone Butcher"].." ("..L["Rare"]..")" },
            { ID = "LBRSOmokk", Title = BB["Highlord Omokk"] },
            { ID = "LBRSSpirestoneBattleLord", Title = L["Spirestone Battle Lord"].." ("..L["Rare"]..")" },
            { ID = "LBRSSpirestoneLordMagus", Title = L["Spirestone Lord Magus"].." ("..L["Rare"]..")" },
            { ID = "LBRSVosh", Title = BB["Shadow Hunter Vosh'gajin"] },
            { ID = "LBRSVoone", Title = BB["War Master Voone"] },
            { ID = "LBRSGrayhoof", Title = BB["Mor Grayhoof"] },
            { ID = "LBRSGrimaxe", Title = BB["Bannok Grimaxe"].." ("..L["Rare"]..")" },
            { ID = "LBRSSmolderweb", Title = BB["Mother Smolderweb"] },
            { ID = "LBRSCrystalFang", Title = BB["Crystal Fang"].." ("..L["Rare"]..")" },
            { ID = "LBRSDoomhowl", Title = BB["Urok Doomhowl"] },
            { ID = "LBRSZigris", Title = BB["Quartermaster Zigris"] },
            { ID = "LBRSHalycon", Title = BB["Halycon"] },
            { ID = "LBRSSlavener", Title = BB["Gizrul the Slavener"] },
            { ID = "LBRSBashguud", Title = BB["Ghok Bashguud"].." ("..L["Rare"]..")" },
            { ID = "LBRSWyrmthalak", Title = BB["Overlord Wyrmthalak"] },
            { ID = "LBRSFelguard", Title = L["Burning Felguard"].." ("..L["Rare"]..")" },
            { ID = "LBRSTrash", Title = L["Trash Mobs"] },
        }
    },
    ["LowerKarazhan"] = {
        Name = BZ["Lower Karazhan Halls"],
        Entry = {
            { ID = "LKHRolfen", Title = BB["Master Blacksmith Rolfen"] },
            { ID = "LKHBroodQueenAraxxna", Title = BB["Brood Queen Araxxna"] },
            { ID = "LKHGrizikil", Title = BB["Grizikil"] },
            { ID = "LKHClawlordHowlfang", Title = BB["Clawlord Howlfang"] },
            { ID = "LKHLordBlackwaldII", Title = BB["Lord Blackwald II"] },
            { ID = "LKHMoroes", Title = BB["Moroes"] },
            { ID = "LKHEnchants", Title = L["Lower Karazhan Halls Enchants"] },
        	{ ID = "LKHTrash", Title = L["Trash Mobs"] },
        }
    },
    ["Maraudon"] = {
        Name = BZ["Maraudon"],
        Entry = {
            { ID = "MaraNoxxion", Title = BB["Noxxion"] },
            { ID = "MaraRazorlash", Title = BB["Razorlash"] },
            { ID = "MaraLordVyletongue", Title = BB["Lord Vyletongue"] },
            { ID = "MaraMeshlok", Title = BB["Meshlok the Harvester"] },
            { ID = "MaraCelebras", Title = BB["Celebras the Cursed"] },
            { ID = "MaraLandslide", Title = BB["Landslide"] },
            { ID = "MaraTinkerer", Title = BB["Tinkerer Gizlock"] },
            { ID = "MaraRotgrip", Title = BB["Rotgrip"] },
            { ID = "MaraPrincess", Title = BB["Princess Theradras"] },
            { ID = "MaraTrash", Title = L["Trash Mobs"] },
        },
    },
    ["Scholomance"] = {
        Name = BZ["Scholomance"],
        Entry = {
            { ID = "SCHOLOBlood", Title = L["Blood Steward of Kirtonos"] },
            { ID = "SCHOLOKirtonostheHerald", Title = BB["Kirtonos the Herald"] },
            { ID = "SCHOLOJandiceBarov", Title = BB["Jandice Barov"] },
            { ID = "SCHOLOLordBlackwood", Title = BB["Lord Blackwood"].." (".."Scourge Invasion"..")" },
            { ID = "SCHOLORattlegore", Title = BB["Rattlegore"] },
            { ID = "SCHOLODeathKnight", Title = BB["Death Knight Darkreaver"] },
            { ID = "SCHOLOMarduk", Title = BB["Marduk Blackpool"] },
            { ID = "SCHOLOVectus", Title = BB["Vectus"] },
            { ID = "SCHOLORasFrostwhisper", Title = BB["Ras Frostwhisper"] },
            { ID = "SCHOLOKormok", Title = BB["Kormok"] },
            { ID = "SCHOLOInstructorMalicia", Title = BB["Instructor Malicia"] },
            { ID = "SCHOLODoctorTheolenKrastinov", Title = BB["Doctor Theolen Krastinov"] },
            { ID = "SCHOLOLorekeeperPolkelt", Title = BB["Lorekeeper Polkelt"] },
            { ID = "SCHOLOTheRavenian", Title = BB["The Ravenian"] },
            { ID = "SCHOLOLordAlexeiBarov", Title = BB["Lord Alexei Barov"] },
            { ID = "SCHOLOLadyIlluciaBarov", Title = BB["Lady Illucia Barov"] },
            { ID = "SCHOLODarkmasterGandling", Title = BB["Darkmaster Gandling"] },
            { ID = "SCHOLOTrash", Title = L["Trash Mobs"] },
        },
    },
    ["StormwindVault"] = {
        Name = BZ["Stormwind Vault"],
        Entry = {
            { ID = "SWVAszoshGrimflame", Title = BB["Aszosh Grimflame"] },
            { ID = "SWVThamGrarr", Title = BB["Tham'Grarr"] },
            { ID = "SWVBlackBride", Title = BB["Black Bride"] },
            { ID = "SWVDamian", Title = BB["Damian"] },
            { ID = "SWVVolkanCruelblade", Title = BB["Volkan Cruelblade"] },
            { ID = "SWVVaultArmoryEquipment", Title = L["Arc'tiras / Vault Armory Equipment"] },
            { ID = "SWVTrash", Title = L["Trash Mobs"] },
        }
    },
    ["Stratholme"] = {
        Name = BZ["Stratholme"],
        Entry = {
            { ID = "STRATSkull", Title = BB["Skul"] },
            { ID = "STRATStratholmeCourier", Title = BB["Stratholme Courier"] },
            { ID = "STRATFrasSiabi", Title = L["Fras Siabi"] },
            { ID = "STRATAtiesh", Title = BB["Atiesh"] },
            { ID = "STRATBalzaphon", Title = BB["Balzaphon"] },
            { ID = "STRATHearthsingerForresten", Title = BB["Hearthsinger Forresten"] },
            { ID = "STRATTheUnforgiven", Title = BB["The Unforgiven"] },
            { ID = "STRATTimmytheCruel", Title = BB["Timmy the Cruel"] },
            { ID = "STRATCrimsonHammersmith", Title = L["Crimson Hammersmith"].." (Summon)" },
            { ID = "STRATBSPlansSerenity", Title = L["Blacksmithing Plans"] },
            { ID = "STRATCannonMasterWilley", Title = BB["Cannon Master Willey"] },
            { ID = "STRATArchivistGalford", Title = BB["Archivist Galford"] },
            { ID = "STRATBalnazzar", Title = BB["Balnazzar"] },
            { ID = "STRATSothosJarien", Title = BB["Sothos"].." & "..BB["Jarien"] },
            { ID = "STRATMagistrateBarthilas", Title = BB["Magistrate Barthilas"] },
            { ID = "STRATStonespine", Title = BB["Stonespine"] },
            { ID = "STRATBaronessAnastari", Title = BB["Baroness Anastari"] },
            { ID = "STRATBlackGuardSwordsmith", Title = L["Black Guard Swordsmith"] },
            { ID = "STRATBSPlansCorruption", Title = L["Blacksmithing Plans"] },
            { ID = "STRATNerubenkan", Title = BB["Nerub'enkan"] },
            { ID = "STRATMalekithePallid", Title = BB["Maleki the Pallid"] },
            { ID = "STRATRamsteintheGorger", Title = BB["Ramstein the Gorger"] },
            { ID = "STRATBaronRivendare", Title = BB["Baron Rivendare"] },
            { ID = "STRATPostmaster", Title = BB["Postmaster Malown"] },
            { ID = "STRATTrash", Title = L["Trash Mobs"] },
        }
    },
    ["UpperBlackrockSpire"] = {
        Name = BZ["Upper Blackrock Spire"],
        Entry = {
            { ID = "UBRSEmberseer", Title = BB["Pyroguard Emberseer"] },
            { ID = "UBRSSolakar", Title = BB["Solakar Flamewreath"] },
            { ID = "UBRSFlame", Title = L["Father Flame"] },
            { ID = "UBRSRunewatcher", Title = BB["Jed Runewatcher"].." ("..L["Rare"]..")" },
            { ID = "UBRSAnvilcrack", Title = BB["Goraluk Anvilcrack"].." ("..L["Rare"]..")" },
            { ID = "UBRSRend", Title = BB["Warchief Rend Blackhand"] },
            { ID = "UBRSGyth", Title = BB["Gyth"] },
            { ID = "UBRSBeast", Title = BB["The Beast"] },
            { ID = "UBRSValthalak", Title = BB["Lord Valthalak"] },
            { ID = "UBRSDrakkisath", Title = BB["General Drakkisath"] },
            { ID = "UBRSTrash", Title = L["Trash Mobs"] },
        }
    },
    ["BlackwingLair"] = {
        Name = BZ["Blackwing Lair"],
        Entry = {
            { ID = "BWLRazorgore", Title = BB["Razorgore the Untamed"] },
            { ID = "BWLVaelastrasz", Title = BB["Vaelastrasz the Corrupt"] },
            { ID = "BWLLashlayer", Title = BB["Broodlord Lashlayer"] },
            { ID = "BWLFiremaw", Title = BB["Firemaw"] },
            { ID = "BWLEbonroc", Title = BB["Ebonroc"] },
            { ID = "BWLFlamegor", Title = BB["Flamegor"] },
            { ID = "BWLChromaggus", Title = BB["Chromaggus"] },
            { ID = "BWLNefarian", Title = BB["Nefarian"] },
            { ID = "BWLTrashMobs", Title = L["Trash Mobs"] },
        },
    },
    ["EmeraldSanctum"] = {
        Name = BZ["Emerald Sanctum"],
        Entry = {
            { ID = "ESErennius", Title = BB["Erennius"] },
            { ID = "ESSolnius", Title = BB["Solnius the Awakener"] },
            { ID = "ESHardMode", Title = L["Favor of Erennius (ES Hard Mode)"] },
            { ID = "ESTrash", Title = L["Trash Mobs"] },
        },
    },
    ["MoltenCore"] = {
        Name = BZ["Molten Core"],
        Entry = {
            { ID = "MCLucifron", Title = BB["Lucifron"] },
            { ID = "MCMagmadar", Title = BB["Magmadar"] },
            { ID = "MCGehennas", Title = BB["Gehennas"] },
            { ID = "MCGarr", Title = BB["Garr"] },
            { ID = "MCGeddon", Title = BB["Shazzrah"] },
            { ID = "MCShazzrah", Title = BB["Baron Geddon"] },
            { ID = "MCGolemagg", Title = BB["Golemagg the Incinerator"] },
            { ID = "MCSulfuron", Title = BB["Sulfuron Harbinger"] },
            { ID = "MCMajordomo", Title = BB["Majordomo Executus"] },
            { ID = "MCRagnaros", Title = BB["Ragnaros"] },
            { ID = "MCRANDOMBOSSDROPS", Title = L["Random Boss Loot"] },
            { ID = "MCTrashMobs", Title = L["Trash Mobs"] },
        },
    },
    ["Naxxramas"] = {
        Name = BZ["Naxxramas"],
        Entry = {
            { ID = "NAXPatchwerk", Title = BB["Patchwerk"] },
            { ID = "NAXGrobbulus", Title = BB["Grobbulus"] },
            { ID = "NAXGluth", Title = BB["Gluth"] },
            { ID = "NAXThaddius", Title = BB["Thaddius"] },
            { ID = "NAXAnubRekhan", Title = BB["Anub'Rekhan"] },
            { ID = "NAXGrandWidowFaerlina", Title = BB["Grand Widow Faerlina"] },
            { ID = "NAXMaexxna", Title = BB["Maexxna"] },
            { ID = "NAXNoththePlaguebringer", Title = BB["Noth the Plaguebringer"] },
            { ID = "NAXHeigantheUnclean", Title = BB["Heigan the Unclean"] },
            { ID = "NAXLoatheb", Title = BB["Loatheb"] },
            { ID = "NAXInstructorRazuvious", Title = BB["Instructor Razuvious"] },
            { ID = "NAXGothiktheHarvester", Title = BB["Gothik the Harvester"] },
            { ID = "NAXTheFourHorsemen", Title = BB["The Four Horsemen"] },
            { ID = "NAXSapphiron", Title = BB["Sapphiron"] },
            { ID = "NAXKelThuzard", Title = BB["Kel'Thuzad"] },
            { ID = "NAXTrash", Title = L["Trash Mobs"] },
        },
    },
    ["Onyxia"] = {
        Name = BZ["Onyxia's Lair"],
        Entry = {
            { ID = "Onyxia", Title = BB["Onyxia"] },
        },
    },
    ["AhnQirajRuins"] = {
        Name = BZ["Ruins of Ahn'Qiraj"],
        Entry = {
            { ID = "AQ20Kurinnaxx", Title = BB["Kurinnaxx"] },
            { ID = "AQ20Rajaxx", Title = BB["General Rajaxx"] },
            { ID = "AQ20Moam", Title = BB["Moam"] },
            { ID = "AQ20Buru", Title = BB["Buru the Gorger"] },
            { ID = "AQ20Ayamiss", Title = BB["Ayamiss the Hunter"] },
            { ID = "AQ20Ossirian", Title = BB["Ossirian the Unscarred"] },
            { ID = "AQ20Trash", Title = L["Trash Mobs"] },
        },
    },
    ["AhnQirajTemple"] = {
        Name = BZ["Temple of Ahn'Qiraj"],
        Entry = {
            { ID = "AQ40Skeram", Title = BB["The Prophet Skeram"] },
            { ID = "AQ40Trio", Title = BB["The Bug Family"] },
            { ID = "AQ40Sartura", Title = BB["Battleguard Sartura"] },
            { ID = "AQ40Fankriss", Title = BB["Fankriss the Unyielding"] },
            { ID = "AQ40Viscidus", Title = BB["Viscidus"] },
            { ID = "AQ40Huhuran", Title = BB["Princess Huhuran"] },
            { ID = "AQ40Emperors", Title = BB["The Twin Emperors"] },
            { ID = "AQ40Ouro", Title = BB["Ouro"] },
            { ID = "AQ40CThun", Title = BB["C'Thun"] },
            { ID = "AQ40Trash1", Title = L["Trash Mobs"].." 1" },
            { ID = "AQ40Trash2", Title = L["Trash Mobs"].." 2" },
        }
    },
    ["TowerofKarazhan"] = {
        Name = BZ["Tower of Karazhan"],
        Entry = {
            { ID = "K40Gnarlmoon", Title = BB["Keeper Gnarlmoon"] },
            { ID = "K40Incantagos", Title = BB["Ley-Watcher Incantagos"] },
            { ID = "K40Anomalus", Title = BB["Anomalus"] },
            { ID = "K40EchoofMedivh", Title = BB["Echo of Medivh"] },
            { ID = "K40King", Title = BB["King"] },
            { ID = "K40SanvTasdal", Title = BB["Sanv Tas'dal"] },
            { ID = "K40Rupturan", Title = BB["Rupturan the Broken"] },
            { ID = "K40Kruul", Title = BB["Kruul"] },
            { ID = "K40Mephistroth", Title = BB["Mephistroth"] },
            { ID = "K40Trash", Title = L["Trash Mobs"] },
        },
    },
    ["ZulGurub"] = {
        Name = BZ["Zul'Gurub"],
        Entry = {
            { ID = "ZGJeklik", Title = BB["High Priestess Jeklik"] },
            { ID = "ZGVenoxis", Title = BB["High Priest Venoxis"] },
            { ID = "ZGMarli", Title = BB["High Priestess Mar'li"] },
            { ID = "ZGMandokir", Title = BB["Bloodlord Mandokir"] },
            { ID = "ZGGrilek", Title = BB["Gri'lek"] },
            { ID = "ZGHazzarah", Title = BB["Hazza'rah"] },
            { ID = "ZGRenataki", Title = BB["Renataki"] },
            { ID = "ZGWushoolay", Title = BB["Wushoolay"] },
            { ID = "ZGGahzranka", Title = BB["Gahz'ranka"] },
            { ID = "ZGThekal", Title = BB["High Priest Thekal"] },
            { ID = "ZGArlokk", Title = BB["High Priestess Arlokk"] },
            { ID = "ZGJindo", Title = BB["Jin'do the Hexxer"] },
            { ID = "ZGHakkar", Title = BB["Hakkar"] },
            { ID = "ZGTrash1", Title = L["Trash Mobs"].." 1" },
            { ID = "ZGTrash2", Title = L["Trash Mobs"].." 2" },
        },
    },
}