local L = AceLibrary("AceLocale-2.2"):new("Atlas")
local BC = AceLibrary("Babble-Class-2.2")
local BS = AceLibrary("Babble-Spell-2.2a")
local BB = AceLibrary("Babble-Boss-2.2a")
local BF = AceLibrary("Babble-Faction-2.2a")
local BZ = AceLibrary("Babble-Zone-2.2a")
local BIS = AceLibrary("Babble-ItemSet-2.2a")

AtlasLoot_ButtonRegistry = {
    ["HateforgeQuarry"] = {
        Name = "Hateforge Quarry",
        Entry = {
            { ID = "HQHighForemanBargulBlackhammer", Title = "High Foreman Bargul Blackhammer" },
            { ID = "HQEngineerFiggles", Title = "Engineer Figgles" },
            { ID = "HQCorrosis", Title = "Corrosis" },
            { ID = "HQHatereaverAnnihilator", Title = "Hatereaver Annihilator" },
            { ID = "HQHargeshDoomcaller", Title = "Hargesh Doomcaller" },
            { ID = "HQTrash", Title = L["Trash Mobs"] },
        }
    },
    ["BlackrockDepths"] = {
        Name = BZ["Blackrock Depths"],
        Entry = {
            { ID = "BRDLordRoccor", Title = "Lord Roccor" },
            { ID = "BRDHighInterrogatorGerstahn", Title = "High Interrogator Gerstahn" },
            { ID = "BRDAnubshiah", Title = "Anub'shiah" },
            { ID = "BRDEviscerator", Title = "Eviscerator" },
            { ID = "BRDGorosh", Title = "Gorosh the Dervish" },
            { ID = "BRDGrizzle", Title = "Grizzle" },
            { ID = "BRDHedrum", Title = "Hedrum the Creeper" },
            { ID = "BRDOkthor", Title = "Ok'thor the Breaker" },
            { ID = "BRDTheldren", Title = "Theldren" },
            { ID = "BRDHoundmaster", Title = "Houndmaster Grebmar" },
            { ID = "BRDPyromancerLoregrain", Title = "Pyromancer Loregrain".." ("..L["Rare"]..")" },
            { ID = "BRDTheVault", Title = "The Vault" },
            { ID = "BRDWarderStilgiss", Title = "Warder Stilgiss".." ("..L["Rare"]..")" },
            { ID = "BRDVerek", Title = "Verek".." ("..L["Rare"]..")" },
            { ID = "BRDFineousDarkvire", Title = "Fineous Darkvire" },
            { ID = "BRDLordIncendius", Title = "Lord Incendius" },
            { ID = "BRDBaelGar", Title = "Bael'Gar" },
            { ID = "BRDGeneralAngerforge", Title = "General Angerforge" },
            { ID = "BRDGolemLordArgelmach", Title = "Golem Lord Argelmach" },
            { ID = "BRDGuzzler", Title = "The Grim Guzzler" },
            { ID = "BRDFlamelash", Title = "Ambassador Flamelash" },
            { ID = "BRDPanzor", Title = "Panzor the Invincible".." ("..L["Rare"]..")" },
            { ID = "BRDTomb", Title = "Summoner's Tomb" },
            { ID = "BRDMagmus", Title = "Magmus" },
            { ID = "BRDPrincess", Title = "Princess Moira Bronzebeard" },
            { ID = "BRDEmperorDagranThaurissan", Title = "Emperor Dagran Thaurissan" },
            { ID = "BRDTrash", Title = "Trash Mobs" },
        }
    },
    ["LowerBlackrockSpire"] = {
        Name = BZ["Lower Blackrock Spire"],
        Entry = {
            { ID = "LBRSSpirestoneButcher", Title = "Spirestone Butcher".." ("..L["Rare"]..")" },
            { ID = "LBRSSpirestoneBattleLord", Title = "Spirestone Battle Lord".." ("..L["Rare"]..")" },
            { ID = "LBRSSpirestoneLordMagus", Title = "Spirestone Lord Magus".." ("..L["Rare"]..")" },
            { ID = "LBRSOmokk", Title = "Highlord Omokk" },
            { ID = "LBRSVosh", Title = "Shadow Hunter Vosh'gajin" },
            { ID = "LBRSVoone", Title = "War Master Voone" },
            { ID = "LBRSFelguard", Title = "Burning Felguard".." ("..L["Rare"]..")" },
            { ID = "LBRSGrayhoof", Title = "Mor Grayhoof" },
            { ID = "LBRSGrimaxe", Title = "Bannok Grimaxe".." ("..L["Rare"]..")" },
            { ID = "LBRSSmolderweb", Title = "Mother Smolderweb" },
            { ID = "LBRSCrystalFang", Title = "Crystal Fang".." ("..L["Rare"]..")" },
            { ID = "LBRSDoomhowl", Title = "Urok Doomhowl" },
            { ID = "LBRSZigris", Title = "Quartermaster Zigris" },
            { ID = "LBRSHalycon", Title = "Halycon" },
            { ID = "LBRSSlavener", Title = "Gizrul the Slavener" },
            { ID = "LBRSBashguud", Title = "Ghok Bashguud".." ("..L["Rare"]..")" },
            { ID = "LBRSWyrmthalak", Title = "Overlord Wyrmthalak" },
            { ID = "LBRSTrash", Title = "Trash Mobs" },
        }
    },
    ["UpperBlackrockSpire"] = {
        Name = BZ["Upper Blackrock Spire"],
        Entry = {
            { ID = "UBRSEmberseer", Title = "Pyroguard Emberseer" },
            { ID = "UBRSSolakar", Title = "Solakar Flamewreath" },
            { ID = "UBRSFlame", Title = "Father Flame" },
            { ID = "UBRSRunewatcher", Title = "Jed Runewatcher".." ("..L["Rare"]..")" },
            { ID = "UBRSAnvilcrack", Title = "Goraluk Anvilcrack".." ("..L["Rare"]..")" },
            { ID = "UBRSRend", Title = "Warchief Rend Blackhand" },
            { ID = "UBRSGyth", Title = "Gyth" },
            { ID = "UBRSBeast", Title = "The Beast" },
            { ID = "UBRSValthalak", Title = "Lord Valthalak" },
            { ID = "UBRSDrakkisath", Title = "General Drakkisath" },
            { ID = "UBRSTrash", Title = "Trash Mobs" },
        }
    },
    ["KarazhanCrypt"] = {
        Name = BZ["Karazhan Crypt"],
        Entry = {
            { ID = "KCTrash", Title = L["Trash Mobs"] },
            { ID = "KCMarrowspike", Title = BB["Marrowspike"] },
            { ID = "KCHivaxxis", Title = BB["Hivaxxis"] },
            { ID = "KCCorpsemuncher", Title = BB["Corpsemuncher"] },
            { ID = "KCGuardCaptainGort", Title = BB["Guard Captain Gort"] },
            { ID = "KCArchlichEnkhraz", Title = BB["Archlich Enkhraz"] },
            { ID = "KCCommanderAndreon", Title = BB["Commander Andreon"] },
            { ID = "KCAlarus", Title = BB["Alarus"] },
            { ID = "KCTreasure", Title = L["Half-Buried Treasure Chest"] },
        }
    },
    ["CavernsOfTimeBlackMorass"] = {
        Name = BZ["Caverns of Time: Black Morass"],
        Entry = {
            { ID = "COTTrash", Title = L["Trash Mobs"] },
            { ID = "COTBMChronar", Title = "Chronar" },
            { ID = "COTBMEpidamu", Title = "Epidamu" },
            { ID = "COTBMDriftingAvatar", Title = "Drifting Avatar of Time" },
            { ID = "COTBMTimeLordEpochronos", Title = "Time-Lord Epochronos" },
            { ID = "COTBMMossheart", Title = "Mossheart" },
            { ID = "COTBMRotmaw", Title = "Rotmaw" },
            { ID = "COTBMAntnormi", Title = "Antnormi" },
        }
    },
    ["StormwindVault"] = {
        Name = BZ["Stormwind Vault"],
        Entry = {
            { ID = "SWVTrash", Title = L["Trash Mobs"] },
            { ID = "SWVAszoshGrimflame", Title = BB["Aszosh Grimflame"] },
            { ID = "SWVThamGrarr", Title = BB["Tham'Grarr"] },
            { ID = "SWVBlackBride", Title = BB["Black Bride"] },
            { ID = "SWVDamian", Title = BB["Damian"] },
            { ID = "SWVVolkanCruelblade", Title = BB["Volkan Cruelblade"] },
            { ID = "SWVVaultArmoryEquipment", Title = L["Arc'tiras / Vault Armory Equipment"] },
        }
    },
    ["BlackwingLair"] = {
        Name = BZ["Blackwing Lair"],
        Entry = {
            { ID = "BWLTrashMobs", Title = L["Trash Mobs"] },
            { ID = "BWLRazorgore", Title = BB["Razorgore the Untamed"] },
            { ID = "BWLVaelastrasz", Title = BB["Vaelastrasz the Corrupt"] },
            { ID = "BWLLashlayer", Title = BB["Broodlord Lashlayer"] },
            { ID = "BWLFiremaw", Title = BB["Firemaw"] },
            { ID = "BWLEbonroc", Title = BB["Ebonroc"] },
            { ID = "BWLFlamegor", Title = BB["Flamegor"] },
            { ID = "BWLChromaggus", Title = BB["Chromaggus"] },
            { ID = "BWLNefarian", Title = BB["Nefarian"] },
        }
    },
    ["TheDeadmines"] = {
        Name = BZ["The Deadmines"],
        Entry = {
            { ID = "DMTrash", Title = L["Trash Mobs"] },
            { ID = "DMJaredVoss", Title = BB["Jared Voss"] },
            { ID = "DMRhahkZor", Title = BB["Rhahk'Zor"] },
            { ID = "DMMinerJohnson", Title = BB["Miner Johnson"].." ("..L["Rare"]..")" },
            { ID = "DMSneed", Title = BB["Sneed"] },
            { ID = "DMSneedsShredder", Title = L["Sneed's Shredder"] },
            { ID = "DMHarvester", Title = BB["Masterpiece Harvester"] },
            { ID = "DMGilnid", Title = BB["Gilnid"] },
            { ID = "DMMrSmite", Title = BB["Mr. Smite"] },
            { ID = "DMCookie", Title = BB["Cookie"] },
            { ID = "DMCaptainGreenskin", Title = BB["Captain Greenskin"] },
            { ID = "DMVanCleef", Title = BB["Edwin VanCleef"] },
        }
    },
    ["WorldBosses"] = {
        Name = L["World"],
        Entry = {
            { ID = "WBAzuregos", Title = BB["Azuregos"] },
            { ID = "WBLordKazzak", Title = BB["Lord Kazzak"] },
            { ID = "WBEmeriss", Title = BB["Emeriss"] },
            { ID = "WBLethon", Title = BB["Lethon"] },
            { ID = "WBTaerar", Title = BB["Taerar"] },
            { ID = "WBYsondre", Title = BB["Ysondre"] },
            { ID = "WBTurtlhu", Title = L["Turtlhu, the Black Turtle of Doom"] },
            { ID = "WBNerubian", Title = BB["Nerubian Overseer"] },
            { ID = "WBReaver", Title = BB["Dark Reaver of Karazhan"] },
            { ID = "WBOstarius", Title = BB["Ostarius"] },
            { ID = "WBConcavius", Title = BB["Concavius"] },
            { ID = "WBCowKing", Title = BB["Moo"] },
            { ID = "WBClackora", Title = BB["Cla'ckora"] },
        }
    },
    ["Onyxia"] = {
        Name = BZ["Onyxia's Lair"],
        Entry = {
            { ID = "ONYTrash", Title = L["Trash Mobs"] },
            { ID = "ONYOnyxia", Title = BB["Onyxia"] },
        }
    },
    ["MoltenCore"] = {
        Name = BZ["Molten Core"],
        Entry = {
            { ID = "MCTrash", Title = L["Trash Mobs"] },
            { ID = "MCLucifron", Title = BB["Lucifron"] },
            { ID = "MCMagmadar", Title = BB["Magmadar"] },
            { ID = "MCGehennas", Title = BB["Gehennas"] },
            { ID = "MCGarr", Title = BB["Garr"] },
            { ID = "MCShazzrah", Title = BB["Baron Geddon"] },
            { ID = "MCGeddon", Title = BB["Shazzrah"] },
            { ID = "MCSulfuron", Title = BB["Sulfuron Harbinger"] },
            { ID = "MCGolemagg", Title = BB["Golemagg the Incinerator"] },
            { ID = "MCMajordomo", Title = BB["Majordomo Executus"] },
            { ID = "MCRagnaros", Title = BB["Ragnaros"] },
        }
    },
    ["ZulGurub"] = {
        Name = BZ["Zul'Gurub"],
        Entry = {
            { ID = "ZGTrash", Title = L["Trash Mobs"] },
            { ID = "ZGJeklik", Title = BB["High Priestess Jeklik"] },
            { ID = "ZGVenoxis", Title = BB["High Priest Venoxis"] },
            { ID = "ZGMarli", Title = BB["High Priestess Mar'li"] },
            { ID = "ZGThekal", Title = BB["High Priest Thekal"] },
            { ID = "ZGArlokk", Title = BB["High Priestess Arlokk"] },
            { ID = "ZGHakkar", Title = BB["Hakkar"] },
            { ID = "ZGGahzranka", Title = BB["Gahz'ranka"] },
            { ID = "ZGMandokir", Title = BB["Bloodlord Mandokir"] },
            { ID = "ZGJindo", Title = BB["Jin'do the Hexxer"] },
            { ID = "ZGHazzarah", Title = BB["Hazza'rah"] },
            { ID = "ZGRenataki", Title = BB["Renataki"] },
            { ID = "ZGWushoolay", Title = BB["Wushoolay"] },
            { ID = "ZGGrilek", Title = BB["Gri'lek"] },
        }
    },
    ["Scholomance"] = {
        Name = BZ["Scholomance"],
        Entry = {
            { ID = "SCHOLOTrash", Title = L["Trash Mobs"] },
            { ID = "SCHOLOBlood", Title = L["Blood Steward of Kirtonos"] },
            { ID = "SCHOLOKirtonostheHerald", Title = BB["Kirtonos the Herald"] },
            { ID = "SCHOLOJandiceBarov", Title = BB["Jandice Barov"] },
            { ID = "SCHOLOLordBlackwood", Title = BB["Lord Blackwood"].." (".."Scourge Invasion"..")" },
            { ID = "SCHOLORattlegore", Title = BB["Rattlegore"] },
            { ID = "SCHOLODeathKnight", Title = BB["Death Knight Darkreaver"] },
            { ID = "SCHOLOMarduk", Title = BB["Marduk Blackpool"] },
            { ID = "SCHOLOVectus", Title = BB["Vectus"] },
            { ID = "SCHOLORasFrostwhisper", Title = BB["Ras Frostwhisper"] },
            { ID = "SCHOLOKormok", Title = BB["Kormok"] },
            { ID = "SCHOLOInstructorMalicia", Title = BB["Instructor Malicia"] },
            { ID = "SCHOLODoctorTheolenKrastinov", Title = BB["Doctor Theolen Krastinov"] },
            { ID = "SCHOLOLorekeeperPolkelt", Title = BB["Lorekeeper Polkelt"] },
            { ID = "SCHOLOTheRavenian", Title = BB["The Ravenian"] },
            { ID = "SCHOLOLordAlexeiBarov", Title = BB["Lord Alexei Barov"] },
            { ID = "SCHOLOLadyIlluciaBarov", Title = BB["Lady Illucia Barov"] },
            { ID = "SCHOLODarkmasterGandling", Title = BB["Darkmaster Gandling"] },
        }
    },
    ["Stratholme"] = {
        Name = BZ["Stratholme"],
        Entry = {
            { ID = "STRATTrash", Title = L["Trash Mobs"] },
            { ID = "STRATUnforgiven", Title = BB["The Unforgiven"] },
            { ID = "STRATTimmy", Title = BB["Timmy the Cruel"] },
            { ID = "STRATCannon", Title = BB["Cannon Master Willey"] },
            { ID = "STRATArchivist", Title = BB["Archivist Galford"] },
            { ID = "STRATMalor", Title = BB["Hearthsinger Forresten"] },
            { ID = "STRATPostmaster", Title = BB["Postmaster Malown"] },
            { ID = "STRATAnastari", Title = BB["Stonespine"] },
            { ID = "STRATBlackGuard", Title = L["Black Guard Swordsmith"] },
            { ID = "STRATNerubenkan", Title = BB["Nerub'enkan"] },
            { ID = "STRATMaleki", Title = BB["Maleki the Pallid"] },
            { ID = "STRATRamstein", Title = BB["Ramstein the Gorger"] },
            { ID = "STRATAndrew", Title = BB["Baroness Anastari"] },
            { ID = "STRATBareon", Title = BB["Baron Rivendare"] },
        }
    },
    ["AhnQirajRuins"] = {
        Name = BZ["Ruins of Ahn'Qiraj"],
        Entry = {
            { ID = "AQ20Trash", Title = L["Trash Mobs"] },
            { ID = "AQ20Kurinnaxx", Title = BB["Kurinnaxx"] },
            { ID = "AQ20Rajaxx", Title = BB["General Rajaxx"] },
            { ID = "AQ20Moam", Title = BB["Moam"] },
            { ID = "AQ20Buru", Title = BB["Buru the Gorger"] },
            { ID = "AQ20Ayamiss", Title = BB["Ayamiss the Hunter"] },
            { ID = "AQ20Ossirian", Title = BB["Ossirian the Unscarred"] },
        }
    },
    ["AhnQirajTemple"] = {
        Name = BZ["Temple of Ahn'Qiraj"],
        Entry = {
            { ID = "AQ40Trash", Title = L["Trash Mobs"] },
            { ID = "AQ40Skeram", Title = BB["The Prophet Skeram"] },
            { ID = "AQ40BugTrio", Title = BB["The Bug Family"] },
            { ID = "AQ40Sartura", Title = BB["Battleguard Sartura"] },
            { ID = "AQ40Fankriss", Title = BB["Fankriss the Unyielding"] },
            { ID = "AQ40Viscidus", Title = BB["Viscidus"] },
            { ID = "AQ40Huhuran", Title = BB["Princess Huhuran"] },
            { ID = "AQ40TwinEmps", Title = BB["The Twin Emperors"] },
            { ID = "AQ40Ouro", Title = BB["Ouro"] },
            { ID = "AQ40CThun", Title = BB["C'Thun"] },
        }
    },
    ["DireMaulNorth"] = {
        Name = BZ["Dire Maul (North)"],
        Entry = {
            { ID = "DMNTrash", Title = L["Trash Mobs"] },
            { ID = "DMNGuardMoldar", Title = BB["Guard Mol'dar"] },
            { ID = "DMNStomperKreeg", Title = BB["Stomper Kreeg"] },
            { ID = "DMNGuardFengus", Title = BB["Guard Fengus"] },
            { ID = "DMNThimblejack", Title = L["Knot Thimblejack"] },
            { ID = "DMNGuardSlipkik", Title = BB["Guard Slip'kik"] },
            { ID = "DMNCaptainKromcrush", Title = BB["Captain Kromcrush"] },
            { ID = "DMNKingGordok", Title = BB["King Gordok"] },
            { ID = "DMNChoRush", Title = BB["Cho'Rush the Observer"] },
            { ID = "DMNTRIBUTERUN", Title = L["Tribute Run"] },
        }
    },
    ["DireMaulWest"] = {
        Name = BZ["Dire Maul (West)"],
        Entry = {
            { ID = "DMWTrash", Title = L["Trash Mobs"] },
            { ID = "DMWTendrisWarpwood", Title = BB["Tendris Warpwood"] },
            { ID = "DMWIllyannaRavenoak", Title = BB["Illyanna Ravenoak"] },
            { ID = "DMWMagisterKalendris", Title = BB["Magister Kalendris"] },
            { ID = "DMWTsuzee", Title = BB["Tsu'zee"].." ("..L["Rare"]..")" },
            { ID = "DMWImmolthar", Title = BB["Immol'thar"] },
            { ID = "DMWHelnurath", Title = BB["Lord Hel'nurath"].." ("..L["Rare"]..")" },
            { ID = "DMWPrinceTortheldrin", Title = BB["Prince Tortheldrin"] },
            { ID = "DMWRevanchion", Title = BB["Revanchion"].." (".."Scourge Invasion"..")" },
        }
    },
    ["DireMaulEast"] = {
        Name = BZ["Dire Maul (East)"],
        Entry = {
            { ID = "DMETrash", Title = L["Trash Mobs"] },
            { ID = "DMEPusillin", Title = BB["Pusillin"] },
            { ID = "DMEZevrimThornhoof", Title = BB["Zevrim Thornhoof"] },
            { ID = "DMEHydro", Title = BB["Hydrospawn"] },
            { ID = "DMELethtendris", Title = BB["Lethtendris"] },
            { ID = "DMEPimgib", Title = BB["Pimgib"] },
            { ID = "DMEAlzzin", Title = BB["Alzzin the Wildshaper"] },
            { ID = "DMEIsalien", Title = BB["Isalien"] },
            { ID = "DMEShard", Title = L["Felvine Shard"] },
        }
    },
    ["SunkenTemple"] = {
        Name = BZ["The Temple of Atal'Hakkar"],
        Entry = {
            { ID = "STTrash", Title = L["Trash Mobs"] },
            { ID = "STSpawnOfHakkar", Title = L["Spawn of Hakkar"] },
            { ID = "STBalconyMinibosses", Title = L["Balcony Minibosses"] },
            { ID = "STAtalalarion", Title = BB["Atal'alarion"] },
            { ID = "STAvatarofHakkar", Title = BB["Avatar of Hakkar"] },
            { ID = "STJammalan", Title = BB["Jammal'an the Prophet"] },
            { ID = "STOgom", Title = BB["Ogom the Wretched"] },
            { ID = "STMorphaz", Title = BB["Morphaz"] },
            { ID = "STHazzas", Title = BB["Hazzas"] },
            { ID = "STWeaver", Title = BB["Weaver"] },
            { ID = "STDreamscythe", Title = BB["Dreamscythe"] },
            { ID = "STEranikus", Title = BB["Shade of Eranikus"] },
        }
    },
    ["Maraudon"] = {
        Name = BZ["Maraudon"],
        Entry = {
            { ID = "MARTrash", Title = L["Trash Mobs"] },
            { ID = "MARNoxxion", Title = BB["Noxxion"] },
            { ID = "MARRazorlash", Title = BB["Razorlash"] },
            { ID = "MARLordVyletongue", Title = BB["Lord Vyletongue"] },
            { ID = "MARMeshlok", Title = BB["Meshlok the Harvester"] },
            { ID = "MARCelebras", Title = BB["Celebras the Cursed"] },
            { ID = "MARLandslide", Title = BB["Landslide"] },
            { ID = "MARTinkerer", Title = BB["Tinkerer Gizlock"] },
            { ID = "MARRotgrip", Title = BB["Rotgrip"] },
            { ID = "MARPrincess", Title = BB["Princess Theradras"] },
        }
    },
    ["ZulFarrak"] = {
        Name = BZ["Zul'Farrak"],
        Entry = {
            { ID = "ZFTrash", Title = L["Trash Mobs"] },
            { ID = "ZFAntusul", Title = BB["Antu'sul"] },
            { ID = "ZFWitchDoctorZumrah", Title = BB["Witch Doctor Zum'rah"] },
            { ID = "ZFShadowpriestSezziz", Title = BB["Shadowpriest Sezz'ziz"] },
            { ID = "ZFDustwraith", Title = L["Dustwraith"].." ("..L["Rare"]..")" },
            { ID = "ZFZerillis", Title = L["Zerillis"].." ("..L["Rare"]..")" },
            { ID = "ZFGahzrilla", Title = BB["Gahz'rilla"] },
            { ID = "ZFChiefUkorzSandscalp", Title = BB["Chief Ukorz Sandscalp"] },
        }
    },
    ["Uldaman"] = {
        Name = BZ["Uldaman"],
        Entry = {
            { ID = "ULTrash", Title = L["Trash Mobs"] },
            { ID = "ULBaelog", Title = BB["Baelog"] },
            { ID = "ULOlaf", Title = BB["Olaf"] },
            { ID = "ULEric", Title = BB["Eric \"The Swift\""] },
            { ID = "ULRevelosh", Title = BB["Revelosh"] },
            { ID = "ULIronaya", Title = BB["Ironaya"] },
            { ID = "ULObsidian", Title = BB["Obsidian Sentinel"] },
            { ID = "ULAncients", Title = BB["Ancient Stone Keeper"] },
            { ID = "ULGalgann", Title = BB["Galgann Firehammer"] },
            { ID = "ULGrimlok", Title = BB["Grimlok"] },
            { ID = "ULArchaedas", Title = BB["Archaedas"] },
        }
    },
    ["RazorfenDowns"] = {
        Name = BZ["Razorfen Downs"],
        Entry = {
            { ID = "RFDTrash", Title = L["Trash Mobs"] },
            { ID = "RFDTutenkash", Title = BB["Tuten'kash"] },
            { ID = "RFDHenryStern", Title = L["Henry Stern"] },
            { ID = "RFDLadyF", Title = BB["Lady Falther'ess"].." ("..L["Scourge Invasion"]..")" },
            { ID = "RFDPlaguemaw", Title = BB["Plaguemaw the Rotting"] },
            { ID = "RFDMordreshFireEye", Title = BB["Mordresh Fire Eye"] },
            { ID = "RFDGlutton", Title = BB["Glutton"] },
            { ID = "RFDRagglesnout", Title = BB["Ragglesnout"].." ("..L["Rare"]..")" },
            { ID = "RFDAmnennar", Title = BB["Amnennar the Coldbringer"] },
        }
    },
    ["ScarletMonastery"] = {
        Name = BZ["Scarlet Monastery"],
        Entry = {
            { ID = "SMTrash", Title = L["Trash Mobs"] },
            { ID = "SMVishas", Title = BB["Interrogator Vishas"] },
            { ID = "SMScorn", Title = BB["Scorn"].." (".."Scourge Invasion"..")" },
            { ID = "SMBloodmageThalnos", Title = BB["Bloodmage Thalnos"] },
            { ID = "SMIronspine", Title = BB["Ironspine"].." ("..L["Rare"]..")" },
            { ID = "SMAzshir", Title = BB["Azshir the Sleepless"].." ("..L["Rare"]..")" },
            { ID = "SMFallenChampion", Title = BB["Fallen Champion"].." ("..L["Rare"]..")" },
            { ID = "SMDukeDreadmoore", Title = BB["Duke Dreadmoore"] },
            { ID = "SMHoundmasterLoksey", Title = BB["Houndmaster Loksey"] },
            { ID = "SMDoan", Title = BB["Arcanist Doan"] },
            { ID = "SMBrotherWystan", Title = BB["Brother Wystan"] },
            { ID = "SMHerod", Title = BB["Herod"] },
            { ID = "SMQuartermasterDaghelm", Title = BB["Armory Quartermaster Daghelm"] },
            { ID = "SMFairbanks", Title = BB["High Inquisitor Fairbanks"] },
            { ID = "SMMograine", Title = BB["Scarlet Commander Mograine"] },
            { ID = "SMWhitemane", Title = BB["High Inquisitor Whitemane"] },
        }
    },
    ["RazorfenKraul"] = {
        Name = BZ["Razorfen Kraul"],
        Entry = {
            { ID = "RFKTrash", Title = L["Trash Mobs"] },
            { ID = "RFKAggem", Title = BB["Aggem Thorncurse"] },
            { ID = "RFKDeathSpeakerJargba", Title = BB["Death Speaker Jargba"] },
            { ID = "RFKOverlordRamtusk", Title = BB["Overlord Ramtusk"] },
            { ID = "RFKRazorfenSpearhide", Title = L["Razorfen Spearhide"].." ("..L["Rare"]..")" },
            { ID = "RFKAgathelos", Title = BB["Agathelos the Raging"] },
            { ID = "RFKBlindHunter", Title = BB["Blind Hunter"].." ("..L["Rare"]..")" },
            { ID = "RFKCharlgaRazorflank", Title = BB["Charlga Razorflank"] },
            { ID = "RFKEarthcallerHalmgar", Title = BB["Earthcaller Halmgar"].." ("..L["Rare"]..")" },
        }
    },
    ["Gnomeregan"] = {
        Name = BZ["Gnomeregan"],
        Entry = {
            { ID = "GnTrash", Title = L["Trash Mobs"] },
            { ID = "GnGrubbis", Title = BB["Grubbis"] },
            { ID = "GnViscousFallout", Title = BB["Viscous Fallout"] },
            { ID = "GnElectrocutioner6000", Title = BB["Electrocutioner 6000"] },
            { ID = "GnCrowdPummeler960", Title = BB["Crowd Pummeler 9-60"] },
            { ID = "GnDIAmbassador", Title = BB["Dark Iron Ambassador"] },
            { ID = "GnMekgineerThermaplugg", Title = BB["Mekgineer Thermaplugg"] },
        }
    },
    ["BlackfathomDeeps"] = {
        Name = BZ["Blackfathom Deeps"],
        Entry = {
            { ID = "BFDTrash", Title = L["Trash Mobs"] },
            { ID = "BFDGhamoora", Title = BB["Ghamoo-ra"] },
            { ID = "BFDLadySarevess", Title = BB["Lady Sarevess"] },
            { ID = "BFDGelihast", Title = BB["Gelihast"] },
            { ID = "BFDBaronAquanis", Title = BB["Baron Aquanis"] },
            { ID = "BFDTwilightLordKelris", Title = BB["Twilight Lord Kelris"] },
            { ID = "BFDOldSerrakis", Title = BB["Old Serra'kis"] },
            { ID = "BFDAkumai", Title = BB["Aku'mai"] },
        }
    },
    ["TheStockade"] = {
        Name = BZ["The Stockade"],
        Entry = {
            { ID = "SWStTrash", Title = L["Trash Mobs"] },
            { ID = "SWStTargorr", Title = BB["Targorr the Dread"] },
            { ID = "SWStKamDeepfury", Title = BB["Kam Deepfury"] },
            { ID = "SWStHamhock", Title = BB["Hamhock"] },
            { ID = "SWStDextren", Title = BB["Dextren Ward"] },
            { ID = "SWStBazil", Title = BB["Bazil Thredd"] },
            { ID = "SWStBruegalIronknuckle", Title = BB["Bruegal Ironknuckle"].." ("..L["Rare"]..")" },
        }
    },
    ["ShadowfangKeep"] = {
        Name = BZ["Shadowfang Keep"],
        Entry = {
            { ID = "SFKTrash", Title = L["Trash Mobs"] },
            { ID = "SFKRethilgore", Title = BB["Rethilgore"] },
            { ID = "SFKFelSteed", Title = L["Fel Steed"] },
            { ID = "SFKRazorclawtheButcher", Title = BB["Razorclaw the Butcher"] },
            { ID = "SFKSilverlaine", Title = BB["Baron Silverlaine"] },
            { ID = "SFKSpringvale", Title = BB["Commander Springvale"] },
            { ID = "SFKSever", Title = BB["Sever"].." (".."Scourge Invasion"..")" },
            { ID = "SFKOdotheBlindwatcher", Title = BB["Odo the Blindwatcher"] },
            { ID = "SFKDeathswornCaptain", Title = BB["Deathsworn Captain"].." ("..L["Rare"]..")" },
            { ID = "SFKFenrustheDevourer", Title = BB["Fenrus the Devourer"] },
            { ID = "SFKArugalsVoidwalker", Title = BB["Archmage Arugal's Voidwalker"] },
            { ID = "SFKBookofUr", Title = L["The Book of Ur"] },
            { ID = "SFKWolfMasterNandos", Title = BB["Wolf Master Nandos"] },
            { ID = "SFKArchmageArugal", Title = BB["Archmage Arugal"] },
            { ID = "SFKPrelate", Title = BB["Prelate Ironmane"] },
        }
    },
    ["WailingCaverns"] = {
        Name = BZ["Wailing Caverns"],
        Entry = {
            { ID = "WCTrash", Title = L["Trash Mobs"] },
            { ID = "WCLordCobrahn", Title = BB["Lord Cobrahn"] },
            { ID = "WCLadyAnacondra", Title = BB["Lady Anacondra"] },
            { ID = "WCKresh", Title = BB["Kresh"] },
            { ID = "WCZandara", Title = BB["Zandara Windhoof"] },
            { ID = "WCLordPythas", Title = BB["Lord Pythas"] },
            { ID = "WCSkum", Title = BB["Skum"] },
            { ID = "WCLordSerpentis", Title = BB["Lord Serpentis"] },
            { ID = "WCVerdan", Title = BB["Verdan the Everliving"] },
            { ID = "WCMutanus", Title = BB["Mutanus the Devourer"] },
            { ID = "WCDeviateFaerieDragon", Title = BB["Deviate Faerie Dragon"].." ("..L["Rare"]..")" },
        }
    },
    ["Naxxramas"] = {
        Name = BZ["Naxxramas"],
        Entry = {
            { ID = "NAXXTrash", Title = L["Trash Mobs"] },
            { ID = "NAXXAnubrekhan", Title = BB["Anub'Rekhan"] },
            { ID = "NAXXFaerlina", Title = BB["Grand Widow Faerlina"] },
            { ID = "NAXXMaexxna", Title = BB["Maexxna"] },
            { ID = "NAXXNoth", Title = BB["Noth the Plaguebringer"] },
            { ID = "NAXXHeigan", Title = BB["Heigan the Unclean"] },
            { ID = "NAXXLoatheb", Title = BB["Loatheb"] },
            { ID = "NAXXPatchwerk", Title = BB["Patchwerk"] },
            { ID = "NAXXGrobbulus", Title = BB["Grobbulus"] },
            { ID = "NAXXGluth", Title = BB["Gluth"] },
            { ID = "NAXXThaddius", Title = BB["Thaddius"] },
            { ID = "NAXXRazuvious", Title = BB["Instructor Razuvious"] },
            { ID = "NAXXGothik", Title = BB["Gothik the Harvester"] },
            { ID = "NAXXFourHorsemen", Title = BB["The Four Horsemen"] },
            { ID = "NAXXSapphiron", Title = BB["Sapphiron"] },
            { ID = "NAXXKelthuzad", Title = BB["Kel'Thuzad"] },
        }
    },
    ["WORLDEPICS"] = {
        Name = L["World Epics"],
        Entry = {
            { ID = "WorldEpics1", Title = L["World Epics"] .. " 1" },
            { ID = "WorldEpics2", Title = L["World Epics"] .. " 2" },
            { ID = "WorldEpics3", Title = L["World Epics"] .. " 3" },
        }
    },
    ["Factions"] = {
        Name = L["Factions"],
        Entry = {
            { ID = "ArgentDawn", Title = BF["Argent Dawn"] },
            { ID = "BloodsailBuccaneers", Title = BF["Bloodsail Buccaneers"] },
            { ID = "BroodofNozdormu", Title = BF["Brood of Nozdormu"] },
            { ID = "CenarionCircle", Title = BF["Cenarion Circle"] },
            { ID = "DarkmoonFaire", Title = BF["Darkmoon Faire"] },
            { ID = "HydraxianWaterlords", Title = BF["Hydraxian Waterlords"] },
            { ID = "ThoriumBrotherhood", Title = BF["Thorium Brotherhood"] },
            { ID = "TimbermawHold", Title = BF["Timbermaw Hold"] },
            { ID = "ZandalarTribe", Title = BF["Zandalar Tribe"] },
            { ID = "FrostwolfClan", Title = BF["Frostwolf Clan"] },
            { ID = "StormpikeGuard", Title = BF["Stormpike Guard"] },
            { ID = "TheDefilers", Title = BF["The Defilers"] },
            { ID = "TheLeagueofArathor", Title = BF["The League of Arathor"] },
            { ID = "SilverwingSentinels", Title = BF["Silverwing Sentinels"] },
            { ID = "WarsongOutriders", Title = BF["Warsong Outriders"] },
            { ID = "GelkisClanCentaur", Title = BF["Gelkis Clan Centaur"] },
            { ID = "MagramClanCentaur", Title = BF["Magram Clan Centaur"] },
            { ID = "WintersaberTrainers", Title = BF["Wintersaber Trainers"] },
        }
    },
    ["CraftedSets"] = {
        Name = L["Crafted Sets"],
        Entry = {
            { ID = "SteelPlate", Title = "Steel Plate" },
            { ID = "ImperialPlate", Title = BIS["Imperial Plate"] },
            { ID = "RuneEtchedArmor", Title = "Rune-Etched Armor" },
            { ID = "TheDarksoul", Title = BIS["The Darksoul"] },
            { ID = "BloodsoulEmbrace", Title = BIS["Bloodsoul Embrace"] },
            { ID = "HateforgeArmor", Title = "Hateforge Armor" },
            { ID = "TowerforgeBattlegear", Title = "Towerforge Battlegear" },
            { ID = "DreamsteelArmor", Title = "Dreamsteel Armor" },
            { ID = "AugerersAttire", Title = "Augerer's Attire" },
            { ID = "ShadoweaveSet", Title = "Shadoweave" },
            { ID = "DivinersGarments", Title = "Diviner's Garments" },
            { ID = "PillagersGarb", Title = "Pillager's Garb" },
            { ID = "MoonclothRegalia", Title = "Mooncloth Regalia" },
            { ID = "BloodvineG", Title = BIS["Bloodvine Garb"] },
            { ID = "FlarecoreRegalia", Title = "Flarecore Regalia" },
            { ID = "DreamthreadRegalia", Title = "Dreamthread Regalia" },
            { ID = "GriftersArmor", Title = "Grifter's Armor" },
            { ID = "PrimalistsTrappings", Title = "Primalist's Trappings" },
            { ID = "VolcanicArmor", Title = BIS["Volcanic Armor"] },
            { ID = "IronfeatherArmor", Title = BIS["Ironfeather Armor"] },
            { ID = "StormshroudArmor", Title = BIS["Stormshroud Armor"] },
            { ID = "DevilsaurArmor", Title = BIS["Devilsaur Armor"] },
            { ID = "BloodTigerH", Title = BIS["Blood Tiger Harness"] },
            { ID = "PrimalBatskin", Title = BIS["Primal Batskin"] },
            { ID = "ConvergenceoftheElements", Title = "Convergence of the Elements" },
            { ID = "DreamhideBattlegarb", Title = "Dreamhide Battlegarb" },
            { ID = "RedDragonM", Title = "Red Dragon Mail" },
            { ID = "GreenDragonM", Title = BIS["Green Dragon Mail"] },
            { ID = "BlueDragonM", Title = BIS["Blue Dragon Mail"] },
            { ID = "BlackDragonM", Title = BIS["Black Dragon Mail"] },
            { ID = "CraftedWeapons1", Title = L["Crafted Epic Weapons"] },
        }
    },
    ["Collections"] = {
        Name = L["Collections"],
        Entry = {
            { ID = "Tabards", Title = L["Tabards"] },
            { ID = "Legendaries", Title = L["Legendary Items"] },
            { ID = "Artifacts", Title = L["Artifact Items"] },
            { ID = "PvPMountsPvP", Title = L["PvP Mounts"] },
            { ID = "UnobMounts", Title = L["Unobtainable Mounts"] },
            { ID = "OldMounts", Title = L["Old Mounts"] },
            { ID = "RareMounts", Title = L["Rare Mounts"] },
            { ID = "RarePets1", Title = L["Rare Pets"] },
            { ID = "RarePets2", Title = L["Rare Pets"] },
        }
    },
    ["WorldBlues"] = {
        Name = L["World Blues"],
        Entry = {
            { ID = "WorldBluesHead", Title = AtlasLoot_TableNames["WorldBluesHead"][1] },
            { ID = "WorldBluesNeck", Title = AtlasLoot_TableNames["WorldBluesNeck"][1] },
            { ID = "WorldBluesShoulder", Title = AtlasLoot_TableNames["WorldBluesShoulder"][1] },
            { ID = "WorldBluesBack", Title = AtlasLoot_TableNames["WorldBluesBack"][1] },
            { ID = "WorldBluesChest", Title = AtlasLoot_TableNames["WorldBluesChest"][1] },
            { ID = "WorldBluesWrist", Title = AtlasLoot_TableNames["WorldBluesWrist"][1] },
            { ID = "WorldBluesHands", Title = AtlasLoot_TableNames["WorldBluesHands"][1] },
            { ID = "WorldBluesWaist", Title = AtlasLoot_TableNames["WorldBluesWaist"][1] },
            { ID = "WorldBluesLegs", Title = AtlasLoot_TableNames["WorldBluesLegs"][1] },
            { ID = "WorldBluesFeet", Title = AtlasLoot_TableNames["WorldBluesFeet"][1] },
            { ID = "WorldBluesRing", Title = AtlasLoot_TableNames["WorldBluesRing"][1] },
            { ID = "WorldBluesTrinket", Title = AtlasLoot_TableNames["WorldBluesTrinket"][1] },
            { ID = "WorldBluesWand", Title = AtlasLoot_TableNames["WorldBluesWand"][1] },
            { ID = "WorldBluesHeldInOffhand", Title = AtlasLoot_TableNames["WorldBluesHeldInOffhand"][1] },
            { ID = "WorldBlues1HAxes", Title = AtlasLoot_TableNames["WorldBlues1HAxes"][1] },
            { ID = "WorldBlues1HMaces", Title = AtlasLoot_TableNames["WorldBlues1HMaces"][1] },
            { ID = "WorldBlues1HSwords", Title = AtlasLoot_TableNames["WorldBlues1HSwords"][1] },
            { ID = "WorldBlues2HAxes", Title = AtlasLoot_TableNames["WorldBlues2HAxes"][1] },
            { ID = "WorldBlues2HMaces", Title = AtlasLoot_TableNames["WorldBlues2HMaces"][1] },
            { ID = "WorldBlues2HSwords", Title = AtlasLoot_TableNames["WorldBlues2HSwords"][1] },
            { ID = "WorldBluesDaggers", Title = AtlasLoot_TableNames["WorldBluesDaggers"][1] },
            { ID = "WorldBluesFistWeapons", Title = AtlasLoot_TableNames["WorldBluesFistWeapons"][1] },
            { ID = "WorldBluesPolearms", Title = AtlasLoot_TableNames["WorldBluesPolearms"][1] },
            { ID = "WorldBluesStaves", Title = AtlasLoot_TableNames["WorldBluesStaves"][1] },
            { ID = "WorldBluesBows", Title = AtlasLoot_TableNames["WorldBluesBows"][1] },
            { ID = "WorldBluesCrossbows", Title = AtlasLoot_TableNames["WorldBluesCrossbows"][1] },
            { ID = "WorldBluesGuns", Title = AtlasLoot_TableNames["WorldBluesGuns"][1] },
            { ID = "WorldBluesShields", Title = AtlasLoot_TableNames["WorldBluesShields"][1] },
        }
    },
--[[     ["RaidTrash"] = {
        Name = L["Raid Trash"],
        Entry = {
            { ID = "ZGTrash1", Title = AtlasLoot_TableNames["ZGTrash1"][1] },
            { ID = "ZGTrash2", Title = AtlasLoot_TableNames["ZGTrash2"][1] },
            { ID = "AQ40Trash1", Title = AtlasLoot_TableNames["AQ40Trash1"][1] },
            { ID = "AQ40Trash2", Title = AtlasLoot_TableNames["AQ40Trash2"][1] },
        }
    }, ]]
    ["WorldEvents"] = {
        Name = L["World Events"],
        Entry = {
            { ID = "ChildrensWeek", Title = L["Children's Week"] },
            { ID = "Winterviel1", Title = L["Feast of Winter Veil"] },
            { ID = "Winterviel2", Title = AtlasLoot_TableNames["Winterviel2"][1] },
            { ID = "WintervielSnowball", Title = "Snowball" },
            { ID = "Halloween1", Title = L["Hallow's End"] },
            { ID = "Halloween2", Title = L["Hallow's End"] },
            { ID = "HarvestFestival", Title = L["Harvest Festival"] },
            { ID = "Valentineday", Title = L["Love is in the Air"] },
            { ID = "LunarFestival1", Title = L["Lunar Festival"] },
            { ID = "LunarFestival2", Title = L["Lunar Festival"] },
            { ID = "MidsummerFestival", Title = L["Midsummer Fire Festival"] },
            { ID = "Noblegarden", Title = L["Noblegarden"] },
            { ID = "ElementalInvasion", Title = L["Elemental Invasion"] },
            { ID = "GurubashiArena", Title = L["Gurubashi Arena"] },
            { ID = "ScourgeInvasionEvent1", Title = L["Scourge Invasion"] },
            { ID = "ScourgeInvasionEvent2", Title = AtlasLoot_TableNames["ScourgeInvasionEvent2"][1] },
            { ID = "FishingExtravaganza", Title = L["Stranglethorn Fishing Extravaganza"] },
        }
    },
    ["AbyssalCouncil"] = {
        Name = L["Abyssal Council"],
        Entry = {
            { ID = "AbyssalTemplars", Title = L["Abyssal Council"].." - "..L["Templars"] },
            { ID = "AbyssalDukes", Title = L["Abyssal Council"].." - "..L["Dukes"] },
            { ID = "AbyssalLords", Title = L["Abyssal Council"].." - "..L["High Council"] },
        }
    },
    ["Alchemy"] = {
        Name = BS["Alchemy"],
        Entry = {
            { ID = "AlchemyApprentice1", Title = BS["Alchemy"]..": "..L["Apprentice"] },
            { ID = "AlchemyJourneyman1", Title = BS["Alchemy"]..": "..L["Journeyman"] },
            { ID = "AlchemyExpert1", Title = BS["Alchemy"]..": "..L["Expert"] },
            { ID = "AlchemyArtisan1", Title = BS["Alchemy"]..": "..L["Artisan"] },
            { ID = "AlchemyArtisan2", Title = BS["Alchemy"]..": "..L["Artisan"] },
            { ID = "AlchemyFlasks1", Title = L["Flasks"] },
            { ID = "AlchemyProtectionPots1", Title = L["Protection Potions"] },
            { ID = "AlchemyHealingAndMana1", Title = L["Healing and Mana Potions"] },
            { ID = "AlchemyTransmutes1", Title = L["Transmutes"] },
            { ID = "AlchemyDefensive1", Title = L["Defensive Potions and Elixirs"] },
            { ID = "AlchemyOffensive1", Title = L["Offensive Potions and Elixirs"] },
            { ID = "AlchemyOther1", Title = L["Other"] },
        }
    },
    ["Blacksmithing"] = {
        Name = BS["Blacksmithing"],
        Entry = {
            { ID = "SmithingApprentice1", Title = BS["Blacksmithing"]..": "..L["Apprentice"] },
            { ID = "SmithingJourneyman1", Title = BS["Blacksmithing"]..": "..L["Journeyman"] },
            { ID = "SmithingJourneyman2", Title = BS["Blacksmithing"]..": "..L["Journeyman"] },
            { ID = "SmithingExpert1", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingExpert2", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingExpert3", Title = BS["Blacksmithing"]..": "..L["Expert"] },
            { ID = "SmithingArtisan1", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan2", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan3", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingArtisan4", Title = BS["Blacksmithing"]..": "..L["Artisan"] },
            { ID = "SmithingHelm1", Title = BS["Blacksmithing"]..": "..L["Helm"] },
            { ID = "SmithingShoulders1", Title = BS["Blacksmithing"]..": "..L["Shoulders"] },
            { ID = "SmithingChest1", Title = BS["Blacksmithing"]..": "..L["Chest"] },
            { ID = "SmithingChest2", Title = BS["Blacksmithing"]..": "..L["Chest"] },
            { ID = "SmithingBracers1", Title = BS["Blacksmithing"]..": "..L["Bracers"] },
            { ID = "SmithingGloves1", Title = BS["Blacksmithing"]..": "..L["Gloves"] },
            { ID = "SmithingBelt1", Title = BS["Blacksmithing"]..": "..L["Belt"] },
            { ID = "SmithingPants1", Title = BS["Blacksmithing"]..": "..L["Pants"] },
            { ID = "SmithingBoots1", Title = BS["Blacksmithing"]..": "..L["Boots"] },
            { ID = "SmithingBuckles1", Title = BS["Blacksmithing"]..": "..L["Belt Buckles"] },
            { ID = "SmithingAxes1", Title = BS["Blacksmithing"]..": "..L["Axes"] },
            { ID = "SmithingSwords1", Title = BS["Blacksmithing"]..": "..L["Swords"] },
            { ID = "SmithingMaces1", Title = BS["Blacksmithing"]..": "..L["Maces"] },
            { ID = "SmithingFist1", Title = BS["Blacksmithing"]..": "..L["Fist"] },
            { ID = "SmithingDaggers1", Title = BS["Blacksmithing"]..": "..L["Daggers"] },
            { ID = "SmithingMisc1", Title = BS["Blacksmithing"]..": "..L["Misc"] },
            { ID = "SmithingMisc2", Title = BS["Blacksmithing"]..": "..L["Misc"] },
            { ID = "Armorsmith1", Title = BS["Armorsmith"] },
            { ID = "Weaponsmith1", Title = BS["Weaponsmith"] },
            { ID = "Axesmith1", Title = L["Master Axesmith"] },
            { ID = "Hammersmith1", Title = L["Master Hammersmith"] },
            { ID = "Swordsmith1", Title = L["Master Swordsmith"] },
        }
    },
    Enchanting = {
        Title = BS["Enchanting"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "EnchantingApprentice1", Title = BS["Enchanting"]..": "..L["Apprentice"] },
            { ID = "EnchantingJourneyman1", Title = BS["Enchanting"]..": "..L["Journeyman"] },
            { ID = "EnchantingJourneyman2", Title = BS["Enchanting"]..": "..L["Journeyman"] },
            { ID = "EnchantingExpert1", Title = BS["Enchanting"]..": "..L["Expert"] },
            { ID = "EnchantingExpert2", Title = BS["Enchanting"]..": "..L["Expert"] },
            { ID = "EnchantingArtisan1", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingArtisan2", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingArtisan3", Title = BS["Enchanting"]..": "..L["Artisan"] },
            { ID = "EnchantingCloak1", Title = BS["Enchanting"]..": "..L["Cloak"] },
            { ID = "EnchantingChest1", Title = BS["Enchanting"]..": "..L["Chest"] },
            { ID = "EnchantingBracer1", Title = BS["Enchanting"]..": "..L["Bracers"] },
            { ID = "EnchantingGlove1", Title = BS["Enchanting"]..": "..L["Gloves"] },
            { ID = "EnchantingBoots1", Title = BS["Enchanting"]..": "..L["Boots"] },
            { ID = "Enchanting2HWeapon1", Title = BS["Enchanting"]..": "..L["2H Weapon"] },
            { ID = "EnchantingWeapon1", Title = BS["Enchanting"]..": "..L["Weapon"] },
            { ID = "EnchantingShield1", Title = BS["Enchanting"]..": "..L["Shield"] },
            { ID = "EnchantingMisc1", Title = BS["Enchanting"]..": "..L["Misc"] },
        }
    },
    Engineering = {
        Title = BS["Engineering"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "EngineeringApprentice1", Title = BS["Engineering"]..": "..L["Apprentice"] },
            { ID = "EngineeringJourneyman1", Title = BS["Engineering"]..": "..L["Journeyman"] },
            { ID = "EngineeringJourneyman2", Title = BS["Engineering"]..": "..L["Journeyman"] },
            { ID = "EngineeringExpert1", Title = BS["Engineering"]..": "..L["Expert"] },
            { ID = "EngineeringExpert2", Title = BS["Engineering"]..": "..L["Expert"] },
            { ID = "EngineeringArtisan1", Title = BS["Engineering"]..": "..L["Artisan"] },
            { ID = "EngineeringArtisan2", Title = BS["Engineering"]..": "..L["Artisan"] },
            { ID = "EngineeringEquipment1", Title = BS["Engineering"]..": "..L["Equipment"] },
            { ID = "EngineeringTrinkets1", Title = BS["Engineering"]..": "..L["Trinkets"] },
            { ID = "EngineeringExplosives1", Title = BS["Engineering"]..": "..L["Explosives"] },
            { ID = "EngineeringWeapons1", Title = BS["Engineering"]..": "..L["Weapons"] },
            { ID = "EngineeringParts1", Title = BS["Engineering"]..": "..L["Parts"] },
            { ID = "EngineeringMisc1", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "EngineeringMisc2", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "EngineeringMisc3", Title = BS["Engineering"]..": "..L["Misc"] },
            { ID = "Gnomish1", Title = L["Gnomish Engineering"] },
            { ID = "Goblin1", Title = L["Goblin Engineering"] },
        }
    },
    Leatherworking = {
        Title = BS["Leatherworking"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "LeatherApprentice1", Title = BS["Leatherworking"]..": "..L["Apprentice"] },
            { ID = "LeatherJourneyman1", Title = BS["Leatherworking"]..": "..L["Journeyman"] },
            { ID = "LeatherJourneyman2", Title = BS["Leatherworking"]..": "..L["Journeyman"] },
            { ID = "LeatherExpert1", Title = BS["Leatherworking"]..": "..L["Expert"] },
            { ID = "LeatherExpert2", Title = BS["Leatherworking"]..": "..L["Expert"] },
            { ID = "LeatherArtisan1", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherArtisan2", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherArtisan3", Title = BS["Leatherworking"]..": "..L["Artisan"] },
            { ID = "LeatherHelm1", Title = BS["Leatherworking"]..": "..L["Helm"] },
            { ID = "LeatherShoulders1", Title = BS["Leatherworking"]..": "..L["Shoulders"] },
            { ID = "LeatherCloak1", Title = BS["Leatherworking"]..": "..L["Cloak"] },
            { ID = "LeatherChest1", Title = BS["Leatherworking"]..": "..L["Chest"] },
            { ID = "LeatherChest2", Title = BS["Leatherworking"]..": "..L["Chest"] },
            { ID = "LeatherBracers1", Title = BS["Leatherworking"]..": "..L["Bracers"] },
            { ID = "LeatherGloves1", Title = BS["Leatherworking"]..": "..L["Gloves"] },
            { ID = "LeatherGloves2", Title = BS["Leatherworking"]..": "..L["Gloves"] },
            { ID = "LeatherBelt1", Title = BS["Leatherworking"]..": "..L["Belt"] },
            { ID = "LeatherPants1", Title = BS["Leatherworking"]..": "..L["Pants"] },
            { ID = "LeatherPants2", Title = BS["Leatherworking"]..": "..L["Pants"] },
            { ID = "LeatherBoots1", Title = BS["Leatherworking"]..": "..L["Boots"] },
            { ID = "LeatherBags1", Title = BS["Leatherworking"]..": "..L["Bags"] },
            { ID = "LeatherMisc1", Title = BS["Leatherworking"]..": "..L["Misc"] },
            { ID = "Dragonscale1", Title = BS["Dragonscale Leatherworking"] },
            { ID = "Elemental1", Title = BS["Elemental Leatherworking"] },
            { ID = "Tribal1", Title = BS["Tribal Leatherworking"] },
        }
    },
    Herbalism = {
        Title = BS["Herbalism"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "Herbalism1", Title = BS["Herbalism"] },
            { ID = "Herbalism2", Title = BS["Herbalism"] },
        }
    },
    Mining = {
        Title = BS["Mining"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "Mining1", Title = BS["Mining"] },
            { ID = "Mining2", Title = BS["Mining"] },
            { ID = "Smelting1", Title = BS["Smelting"] },
        }
    },
    Tailoring = {
        Title = BS["Tailoring"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "TailoringApprentice1", Title = BS["Tailoring"]..": "..L["Apprentice"] },
            { ID = "TailoringApprentice2", Title = BS["Tailoring"]..": "..L["Apprentice"] },
            { ID = "TailoringJourneyman1", Title = BS["Tailoring"]..": "..L["Journeyman"] },
            { ID = "TailoringJourneyman2", Title = BS["Tailoring"]..": "..L["Journeyman"] },
            { ID = "TailoringExpert1", Title = BS["Tailoring"]..": "..L["Expert"] },
            { ID = "TailoringExpert2", Title = BS["Tailoring"]..": "..L["Expert"] },
            { ID = "TailoringArtisan1", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan2", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan3", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan4", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringArtisan5", Title = BS["Tailoring"]..": "..L["Artisan"] },
            { ID = "TailoringHelm1", Title = BS["Tailoring"]..": "..L["Helm"] },
            { ID = "TailoringShoulders1", Title = BS["Tailoring"]..": "..L["Shoulders"] },
            { ID = "TailoringCloak1", Title = BS["Tailoring"]..": "..L["Cloak"] },
            { ID = "TailoringChest1", Title = BS["Tailoring"]..": "..L["Chest"] },
            { ID = "TailoringChest2", Title = BS["Tailoring"]..": "..L["Chest"] },
            { ID = "TailoringBracers1", Title = BS["Tailoring"]..": "..L["Bracers"] },
            { ID = "TailoringGloves1", Title = BS["Tailoring"]..": "..L["Gloves"] },
            { ID = "TailoringBelt1", Title = BS["Tailoring"]..": "..L["Belt"] },
            { ID = "TailoringPants1", Title = BS["Tailoring"]..": "..L["Pants"] },
            { ID = "TailoringBoots1", Title = BS["Tailoring"]..": "..L["Boots"] },
            { ID = "TailoringShirt1", Title = BS["Tailoring"]..": "..L["Shirt"] },
            { ID = "TailoringBags1", Title = BS["Tailoring"]..": "..L["Bags"] },
            { ID = "TailoringMisc1", Title = BS["Tailoring"]..": "..L["Misc"] },
        }
    },
    Jewelcrafting = {
        Title = BS["Jewelcrafting"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "JewelcraftingApprentice1", Title = BS["Jewelcrafting"]..": "..L["Apprentice"] },
            { ID = "JewelcraftingJourneyman1", Title = BS["Jewelcrafting"]..": "..L["Journeyman"] },
            { ID = "JewelcraftingJourneyman2", Title = BS["Jewelcrafting"]..": "..L["Journeyman"] },
            { ID = "JewelcraftingExpert1", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingExpert2", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingExpert3", Title = BS["Jewelcrafting"]..": "..L["Expert"] },
            { ID = "JewelcraftingArtisan1", Title = BS["Jewelcrafting"]..": "..L["Artisan"] },
            { ID = "JewelcraftingArtisan2", Title = BS["Jewelcrafting"]..": "..L["Artisan"] },
            { ID = "JewelcraftingGemstones1", Title = BS["Jewelcrafting"]..": "..L["Gemstones"] },
            { ID = "JewelcraftingRings1", Title = BS["Jewelcrafting"]..": "..L["Rings"] },
            { ID = "JewelcraftingRings2", Title = BS["Jewelcrafting"]..": "..L["Rings"] },
            { ID = "JewelcraftingAmulets1", Title = BS["Jewelcrafting"]..": "..L["Amulets"] },
            { ID = "JewelcraftingHelm1", Title = BS["Jewelcrafting"]..": "..L["Head"] },
            { ID = "JewelcraftingBracers1", Title = BS["Jewelcrafting"]..": "..L["Bracers"] },
            { ID = "JewelcraftingOffHands1", Title = BS["Jewelcrafting"]..": "..L["Off-hand"] },
            { ID = "JewelcraftingStaves1", Title = BS["Jewelcrafting"]..": "..L["Staff"] },
            { ID = "JewelcraftingTrinkets1", Title = BS["Jewelcrafting"]..": "..L["Trinkets"] },
            { ID = "JewelcraftingMisc1", Title = BS["Jewelcrafting"]..": "..L["Misc"] },
            { ID = "JewelcraftingGemology1", Title = BS["Jewelcrafting"]..": "..BS["Gemology"] },
            { ID = "JewelcraftingGoldsmithing1", Title = BS["Jewelcrafting"]..": "..BS["Goldsmithing"] },
        }
    },
    Cooking = {
        Title = BS["Cooking"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "CookingApprentice1", Title = BS["Cooking"]..": "..L["Apprentice"] },
            { ID = "CookingJourneyman1", Title = BS["Cooking"]..": "..L["Journeyman"] },
            { ID = "CookingExpert1", Title = BS["Cooking"]..": "..L["Expert"] },
            { ID = "CookingArtisan1", Title = BS["Cooking"]..": "..L["Artisan"] },
        }
    },
    FirstAid = {
        Title = BS["First Aid"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "FirstAid1", Title = BS["First Aid"] },
        }
    },
    Survival = {
        Title = BS["Survival"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "Survival1", Title = BS["Survival"] },
            { ID = "Survival2", Title = BS["Garderning"] },
        }
    },
    Poisons = {
        Title = BS["Poisons"],
        Button_Type = "PROFESSION",
        Entry = {
            { ID = "Poisons1", Title = BS["Poisons"] },
        }
    },
--[[     ["Smelting"] = {
        Name = L["Smelting"],
    }, ]]
}